<?php

/**
 * @file
 *
 * General Organic Groups functionality
 */

/**
 * Helper function to get the human readable name of a group type
 *
 * @param null $node
 *
 * @internal param object $group
 *
 * @return string
 */
function c4m_og_get_group_type_name($node = NULL) {
  if (!$node) {
    $node = og_get_group_context();
  }
  if (!$node || !og_is_group_type('node', $node->type)) {
    return NULL;
  }
  return strtolower(node_type_get_name($node));
}

/**
 * Implements hook_FORM_ID_form_alter().
 */
function c4m_og_form_group_node_form_alter(&$form, &$form_state) {
  $domains = NULL;
  $restricted_organisations = array();

  // Get default domain lists.
  $ec_domains = variable_get('c4m_og_ec_domains', array(
    'ec.europa.eu',
    'echofield.eu',
    'eeas.europa.eu',
    'ext.eeas.europa.eu',
    'ext.jrc.ec.europa.eu',
    'jrc.ec.europa.eu',
  ));

  $eu_domains = variable_get('c4m_og_eu_domains', array(
    'ada.gv.at',
    'adetef.finances.gouv.fr',
    'aecid.es',
    'afd.fr',
  ));

  // Retrieve value from og_access and set pluggable_group_access accordingly.
  if ($form['group_access']['und']['#default_value']) {
    $default_value = 'private';
  }
  else {
    $default_value = 'public';
    // Check if pluggable_group_access.
    if ($entity_id = $form_state['node']->pluggable_node_access['und'][0]['target_id']) {
      $default_value = 'restricted';
      $entities = entity_load('pluggable_node_access', array($entity_id));
      $pluggable_node_access = reset($entities);
      $domains = $pluggable_node_access->data;

      // Check if "ec" should be marked.
      if (count($domains) >= count($ec_domains)) {
        $include_ec = TRUE;
        foreach ($ec_domains as $ec_domain) {
          if (!in_array($ec_domain, $domains)) {
            $include_ec = FALSE;
            break;
          }
        }
        if ($include_ec) {
          $restricted_organisations[] = 'ec';
        }
      }

      // Check if "eu" should be marked.
      if (count($domains) >= count($eu_domains)) {
        $include_eu = TRUE;
        foreach ($eu_domains as $eu_domain) {
          if (!in_array($eu_domain, $domains)) {
            $include_eu = FALSE;
            break;
          }
        }
        if ($include_eu) {
          $restricted_organisations[] = 'eu';
        }
      }
    }
  }

  // Add javascript behaviors.
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'c4m_og') . '/js/c4m_og.js',
  );

  drupal_add_js(array('c4m_og' => array(
    'ec_domains' => $ec_domains,
    'eu_domains' => $eu_domains,
  )), 'setting');

  $options = array(
    'public' => t('Public'),
    'restricted' => t('Restricted'),
    'private' => t('Private'),
  );

  $form['pluggable_group_access'] = array(
    '#type' => 'radios',
    '#title' => t('Group access'),
    '#required' => TRUE,
    '#options' => $options,
    '#default_value' => $default_value,
  );
  $form['pluggable_group_access']['public'] = array(
    '#type' => 'radio',
    '#title' => t('Public'),
    '#weight' => 10,
    '#description' => t('All users may view public content from this Group. Users must request to join this Group.'),
  );
  $form['pluggable_group_access']['restricted'] = array(
    '#type' => 'radio',
    '#title' => t('Restricted'),
    '#weight' => 20,
    '#description' => t('Define by organisation and/or email domain what users can view this Group. Only members can post content to the Group.'),
  );
  $form['pluggable_group_access']['restricted_organisations'] = array(
    '#weight' => 25,
    '#title' => t('Allow users to access this Group by their organisation'),
    '#description' => t('Users belonging to these organisations will have access to this Group. Users must request to join this Group.'),
    '#type' => 'checkboxes',
    '#options' => array(
      'ec' => t('EC/EEAS') . '<div>' . t('Accessible to users with email domains: @domains', array('@domains' => implode(', ', $ec_domains))) . '</div>',
      'eu' => t('EU') . '<div>' . t('Accessible to users with email domains: @domains', array('@domains' => implode(', ', $eu_domains))) . '</div>',
    ),
    '#states' => array(
      // Show the checkboxes only when "restricted" is selected
      'visible' => array(
        ':input[name="pluggable_group_access"]' => array('value' => 'restricted'),
      ),
    ),
    '#default_value' => $restricted_organisations,
  );
  $form['pluggable_group_access']['restricted_by_domain'] = array(
    '#weight' => 26,
    '#title' => t('Allow users to access this Group by their email domain'),
    '#description' => t('Users registered to the platform with an email domain in this list will have access to this Group. Users must request to join this Group. Add one or more email domains. The email domain is the part of the email address after the @. Example: add gmail.com to allow users with an email address like jane.doo@gmail.com.'),
    '#type' => 'textfield',
    '#states' => array(
      // Show the checkboxes only when "restricted" is selected
      'visible' => array(
        ':input[name="pluggable_group_access"]' => array('value' => 'restricted'),
      ),
    ),
    '#default_value' => implode(', ', $domains),
  );

  $form['pluggable_group_access']['private'] = array(
    '#type' => 'radio',
    '#title' => t('Private'),
    '#weight' => 30,
    '#description' => t('Only Group members will be able to access this Group.'),
  );

  // Adds submit handler.
  $form['#submit'][] = 'c4m_og_group_form_submit';

  // Hide original pluggable_node_access field.
  $form['pluggable_node_access']['#access'] = FALSE;

  // Hide group visibility field.
 // $form['group_access']['#access'] = FALSE;
}

/**
 * Submit handler.
 */
function c4m_og_group_form_submit($form, &$form_state) {
  // Check whether we already have referenced entity in pluggable_node_access.
  $node = $form_state['node'];
  $wrapper = entity_metadata_wrapper('node', $node);

  // Get the new domain values.
  $domains = array();
  $group_access = $form_state['values']['pluggable_group_access'];
  switch ($group_access) {
    case 'restricted':
      // Set og_group value to 0.
      $form_state['values']['group_access'][LANGUAGE_NONE][0]['value'] = 0;

      // Edit/create pluggable_node_access.
      foreach (explode(',', $form_state['values']['restricted_by_domain']) as $doamin) {
        $domains[] = trim($doamin);
      }

      if (!$pluggable_node_access = $wrapper->pluggable_node_access->value()) {
        // Create new pluggable_node_access entity.
        $values = array(
          'type' => 'email_domain',
          'data' => $domains,
        );
        $entity = entity_create('pluggable_node_access', $values);
        $entity->save();

        // Save reference to the new entity.
        $form_state['values']['pluggable_node_access'][LANGUAGE_NONE][0]['target_id'] = $entity->id;
      }
      else {
        $entity = reset($pluggable_node_access);
        $entity->data = $domains;
        $entity->save();
      }

      break;
    case 'public':
      // - Set og_group value to 0.
      $form_state['values']['group_access'][LANGUAGE_NONE][0]['value'] = 0;

      // - Delete pluggable_node_access entity if exist.
      $pluggable_node_access = $wrapper->pluggable_node_access->value();
      $entity = reset($pluggable_node_access);
      $entity->delete();

      $form_state['values']['pluggable_node_access'][LANGUAGE_NONE][0]['target_id'] = NULL;
      break;
    case 'private':
      // - Set og_group value to 1.
      $form_state['values']['group_access'][LANGUAGE_NONE][0]['value'] = 1;

      // - Delete pluggable_node_access entity if exist.
      $pluggable_node_access = $wrapper->pluggable_node_access->value();
      $entity = reset($pluggable_node_access);
      $entity->delete();

      $form_state['values']['pluggable_node_access'][LANGUAGE_NONE][0]['target_id'] = NULL;

    break;
  }


}

function c4m_og_node_presave($node) {
  if (!$node->type == 'group') {
    return;
  }

  // Create
}
