<?php
/**
 * @file
 * Code for the Photo content type feature.
 */

include_once 'c4m_content_photo.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function c4m_content_photo_theme_registry_alter(&$theme_registry) {
  $theme_registry['node_gallery_api_item_navigator']['path'] = drupal_get_path('module', 'c4m_content_photo') . "/theme";
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_content_photo_c4m_helper_entity_metrics_info() {
  return array(
    'c4m_og_photos' => array(
      'type'      => 'photo',
      'context'   => 'group',
      'callback'  => 'c4m_og_group_node_metric',
      'arguments' => array(array('photo')),
      'weight'    => 2,
    ),
  );
}
