<?php

/**
 * @file
 * Code for the Group Discussions feature.
 */

include_once 'c4m_features_og_discussions.features.inc';

/**
 * Implements hook_c4m_og_feature_info().
 */
function c4m_features_og_discussions_c4m_og_feature_info() {
  return array(
    'c4m_features_og_discussions' => array(
      'name' => t('Discussions'),
      'description' => t('Discussions overview.'),
      'machine_name' => 'c4m_features_og_discussions',
      'weight' => 2,
      'default' => TRUE,
      'group_types' => array('group', 'project'),
      'content_types' => array('discussion'),
    ),
  );
}

/**
 * Implements hook_preprocess().
 *
 * Add an icon to the "Add a new Discussion" button
 * that appears in the discussion related views.
 */
function c4m_features_og_discussions_preprocess_views_view(&$variables) {
  $related_views = ["c4m_overview_og_discussions_landing", "c4m_overview_og_discussions"];
  c4m_features_og_preprocess_button($variables, $related_views,'discussion', 'fa-pencil', t('Add a new Discussion'));
}
