<?php
/**
 * @file
 * Code for the Blog content type feature.
 */

include_once 'c4m_content_blog.features.inc';

/**
 * Implements hook_c4m_og_vocab_info_content().
 *
 * @return array
 */
function c4m_content_blog_c4m_og_vocab_info_content() {
  return array(
    'blog' => array(
      'entity_type' => 'node',
      'bundle' => 'blog',
      'vocabularies' => array(
        'c4m_vocab_category',
        'c4m_vocab_tag'
      ),
    ),
  );
}

