<?php
/**
 * @file
 * Installation hooks for the Group Wiki feature.
 */

/**
 * Implements hook_install().
 */
function c4m_features_og_wiki_install() {
  // Install this feature.
  c4m_og_feature_install('c4m_features_og_wiki');
}

/**
 * Implements hook_uninstall().
 */
function c4m_features_og_wiki_uninstall() {
  // Uninstall this feature.
  c4m_og_feature_uninstall('c4m_features_og_wiki');
}
