#!/bin/bash

#########################################################################################
#
# This script will setup a local copy of the capacity4more distribution.
#
# Do not change the content of this file, 
# all configuration variables are in the config.sh file.
#
#########################################################################################


# Include some colors
source scripts/helper-colors.sh




# Check if we can load the config file
if [ ! -f config.sh ]; then
	echo
    echo -e  "${BGRED}                                                                 ${RESTORE}"
    echo -e "${BGLRED}  ERROR: No configuration file found!                            ${RESTORE}"
    echo -e  "${BGRED}  > Check if the ${BGLRED}config.sh${BGRED} file exists in the same               ${RESTORE}"
    echo -e  "${BGRED}    directory of the ${BGLRED}install.sh${BGRED} script.                          ${RESTORE}"
    echo -e  "${BGRED}  > If not create one by creating a copy of ${BGLRED}default.config.sh${BGRED}.   ${RESTORE}"
    echo -e  "${BGRED}                                                                 ${RESTORE}"
    echo
    exit 1
fi


# Include the configuration file
source config.sh


# Check if we have a working Drupal bootstrap
cd www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd ..

if [ ! "$BOOTSTRAP_SUCCESS" ]; then

  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  No working Drupal installation!                                ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully.            ${RESTORE}"
  echo -e  "${BGRED}  > An update can only be run on a working environment.          ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e  "${BGRED}  Run the ${BGLRED}./install${BGRED} command to install the platform.             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1

fi





# Always ask confirmation before updating Files!
echo
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e "${BGLBLUE}  Update capacity4more                                           ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e  "${BGBLUE}  > This will update core and contrib modules & themes.          ${RESTORE}"
echo -e  "${BGBLUE}  > This will run the update db command (drush updb).            ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo

echo -e -n "${LRED}Are you sure?${RESTORE} (Y/n) "
read -e -n 1 -r
if [[ ! $REPLY =~ ^[Y]$ ]]; then
  echo 
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo -e "${BGLYELLOW}  Update aborted!                                                ${RESTORE}"
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo
  exit 0
fi
echo



# Cleanup the contrib modules
if [ -d $PROFILE_NAME/modules/contrib ]; then
  echo -e "${LBLUE}> Cleaning up the $PROFILE_NAME/modules/contrib directory${RESTORE}"
  rm -rf $PROFILE_NAME/modules/contrib
  echo
fi

# Cleanup the development modules
if [ -d $PROFILE_NAME/modules/development ]; then
  echo -e "${LBLUE}> Cleaning up the $PROFILE_NAME/modules/development directory${RESTORE}"
  rm -rf $PROFILE_NAME/modules/development
  echo
fi

# Cleanup the contrib themes
if [ -d $PROFILE_NAME/themes/contrib ]; then
  echo -e "${LBLUE}> Cleaning up the $PROFILE_NAME/themes/contrib directory${RESTORE}"
  rm -rf $PROFILE_NAME/themes/contrib
  echo
fi



# Run the build script (drush make + extra's).
echo -e "${LBLUE}> Run the build script (scripts/build)${RESTORE}"
bash scripts/build
echo



# Update the database
echo -e "${LBLUE}> Run the Update Database script (drush -y updb)${RESTORE}"
cd www
drush -y updb
echo
cd ..



# Check if we have a working bootstrap
cd www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd ..

if [ ! "$BOOTSTRAP_SUCCESS" ]; then

  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  Update failure!                                                ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1

fi



# If we managed to get here then the update was a success!
echo
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo -e "${BGLGREEN}  Update complete!                                               ${RESTORE}"
echo -e  "${BGGREEN}  > Visit the site : ${BGLGREEN}capacity4more.dev${BGGREEN}.                          ${RESTORE}"
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo

exit 0



