#!/bin/bash

################################################################################
#
# This script will update an working copy of the capacity4more distribution.
#
# Do not change the content of this file, 
# all configuration variables are in the config.sh file.
#
################################################################################


# Define the root of the GIT repository
cd ${0%/*}
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

# Load the colors
source $ROOT/scripts/helper-colors.sh

# Load the helpers
source $ROOT/scripts/helper-functions.sh

# Load the configuration
load_config_file



# Check if we have a working Drupal bootstrap
cd $ROOT/www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd $ROOT

if [ ! "$BOOTSTRAP_SUCCESS" ]; then
  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  No working Drupal installation!                                ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully.            ${RESTORE}"
  echo -e  "${BGRED}  > An update can only be run on a working environment.          ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e  "${BGRED}  Run the ${BGLRED}./install${BGRED} command to install the platform.             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1
fi



# Always ask confirmation before updating Files!
echo
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e "${BGLBLUE}  Update capacity4more                                           ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e  "${BGBLUE}  > This will update core and contrib modules & themes.          ${RESTORE}"
echo -e  "${BGBLUE}  > This will run the update db command (drush updb).            ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo

echo -e -n "${LRED}Are you sure?${RESTORE} (Y/n) "
read -e -n 1 -r
if [[ ! $REPLY =~ ^[Y]$ ]]; then
  echo 
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo -e "${BGLYELLOW}  Update aborted!                                                ${RESTORE}"
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo
  exit 0
fi
echo


# Cleanup contrib modules, themes & libraries from the profile directory.
delete_profile_contrib


# Run the build script (drush make + extra's).
echo -e "${LBLUE}> Run the build script (scripts/build)${RESTORE}"
bash $ROOT/scripts/build
echo


# Update the database
echo -e "${LBLUE}> Run the Update Database script (drush -y updb)${RESTORE}"
cd $ROOT/www
drush -y updb
cd $ROOT
echo




# Check if we have a working bootstrap
cd $ROOT/www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd $ROOT

if [ ! "$BOOTSTRAP_SUCCESS" ]; then
  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  Update failure!                                                ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1
fi



# If we managed to get here then the update was a success!
echo
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo -e "${BGLGREEN}  Update complete!                                               ${RESTORE}"
echo -e  "${BGGREEN}  > Visit the site : ${BGLGREEN}capacity4more.dev${BGGREEN}                           ${RESTORE}"
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo

exit 0



