<?php

/**
 * @file
 * Code for the Group Documents feature.
 */

include_once 'c4m_features_og_documents.features.inc';

/**
 * Implements hook_c4m_og_feature_info().
 */
function c4m_features_og_documents_c4m_og_feature_info() {
  return array(
    'c4m_features_og_documents' => array(
      'name' => t('Library'),
      'description' => t('Library overview.'),
      'machine_name' => 'c4m_features_og_documents',
      'weight' => 3,
      'default' => TRUE,
      'group_types' => array('group', 'project'),
      'content_types' => array('document'),
    ),
  );
}

/**
 * Implements hook_preprocess().
 *
 * Add an icon to the "Add an event" button
 * that appears in the event related views.
 */
function c4m_features_og_documents_preprocess_views_view(&$variables) {
  $icon = '<i class="fa fa-file-text-o" aria-hidden="true"></i>';
  $text = t('Upload a document');
  $variables['header'] = str_replace($text, $icon . ' ' . $text, $variables['header']);
}

