<?php

/**
 * @file
 * Code for the User Profile feature.
 */

include_once 'c4m_user_profile.features.inc';

define('C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE', 1);
define('C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR', 2);

/**
 * Implements hook_field_extra_fields_alter().
 */
function c4m_user_profile_field_extra_fields_alter(&$info) {
  // Make sure that the Account fields are always at the top of the user
  // profile.
  if (isset($info['user']['user']['form']['account']['weight'])) {
    $info['user']['user']['form']['account']['weight'] = -100;
  }
}

/******************************************************************************
 * BLOCK
 ******************************************************************************/

/**
 * Implements hook_block_info().
 */
function c4m_user_profile_block_info() {
  $blocks['user_menu'] = [
    'info' => t('Display user menu in the top bar'),
    'cache' => DRUPAL_CACHE_PER_USER,
  ];

  $blocks['user_notifications'] = [
    'info' => t('Display the user notifications etc...'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  $blocks['user_is_invalid_email'] = [
    'info' => t('Display the invalid email alert'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  $blocks['user_confirm_email'] = [
    'info' => t('Engage user to confirm his email'),
    'cache' => DRUPAL_NO_CACHE,
  ];

  $blocks['user_my_profile_groups'] = [
    'info' => t('My groups'),
    'cache' => DRUPAL_CACHE_PER_USER,
  ];

  $blocks['user_my_profile_projects'] = [
    'info' => t('My projects/programmes'),
    'cache' => DRUPAL_CACHE_PER_USER,
  ];

  $blocks['ecas_login_notice'] = [
    'info' => t('Display EU Login information'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function c4m_user_profile_block_view($delta = '') {
  $module_name = 'c4m_user_profile';
  module_load_include('inc', $module_name, "{$module_name}.block");
  $callback = "_{$module_name}_block_" . $delta;
  if (!function_exists($callback)) {
    return NULL;
  }

  return $callback();
}

/**
 * Implements hook_token_info().
 */
function c4m_user_profile_token_info() {
  $info['tokens']['user']['full-name'] = [
    'name' => t('User Full Name'),
    'description' => t('Returns the User Full Name)'),
  ];
  $info['tokens']['user']['url-with-name'] = [
    'name' => t("User profile URL with fallback for anonymous users"),
    'description' => t("The URL of the account profile page, with fallback if anonymous."),
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function c4m_user_profile_tokens($type, $tokens, array $data = [], array $options = []) {
  $replacements = [];
  $url_options = ['absolute' => TRUE];

  if ($type == 'user' && !empty($data['user'])) {
    $account = $data['user'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'full-name':
          $replacements[$original] = c4m_user_name($account);
          break;

        case 'url-with-name':
          $name = c4m_user_name($account);

          $wrapper = entity_metadata_wrapper('user', $account);
          if (!$account->status && $wrapper->c4m_is_deleted_anonymous->value()) {
            $name = t('Anonymous');
          }

          $replacements[$original] = !empty($account->uid) && $account->status ? l($name, "user/$account->uid", $url_options) : $name;
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Implements hook_facet_items_alter().
 */
function c4m_user_profile_facet_items_alter(&$build, &$settings) {
  switch ($settings->facet) {
    case 'c4m_country':
      _c4m_user_profile_facet_country_alter($build, $settings);
      break;
  }
}

/**
 * Helper function to alter the facet for the country.
 *
 * Display full country name instead of country code.
 *
 * @param array $build
 *   The facets.
 * @param object $settings
 *   Facet settings.
 */
function _c4m_user_profile_facet_country_alter(array &$build, $settings) {
  $field = field_info_field($settings->facet);
  $allowed_values = list_allowed_values($field);
  foreach ($build as $key => $item) {
    $build[$key]["#markup"] = ucwords(drupal_strtolower($allowed_values[drupal_strtoupper($key)]));
  }
}

/**
 * Implements hook_theme().
 */
function c4m_user_profile_theme() {
  $theme['c4m_user_profile_picture_fullname'] = [
    'variables' => [
      'user' => [],
      'link' => [],
    ],
    'file' => 'c4m_user_profile.theme.inc',
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/includes',
  ];

  $theme['c4m_user_profile_menu'] = [
    'variables' => [
      'menu_items' => [],
      'attributes' => [],
    ],
    'file' => 'c4m_user_profile.theme.inc',
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/includes',
  ];

  $theme['c4m_user_profile_groups_top_bar'] = [
    'variables' => [
      'groups' => [],
      'link' => [],
    ],
    'file' => 'c4m_user_profile.theme.inc',
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/includes',
  ];

  $theme['c4m_user_profile_projects_top_bar'] = [
    'variables' => [
      'projects' => [],
      'link' => [],
    ],
    'file' => 'c4m_user_profile.theme.inc',
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/includes',
  ];

  $theme['c4m_user_profile_my_profile_groups'] = [
    'variables' => [
      'groups' => NULL,
    ],
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/templates',
    'template' => 'my-profile-groups',
  ];

  $theme['c4m_user_profile_my_profile_projects'] = [
    'variables' => [
      'projects' => NULL,
    ],
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/templates',
    'template' => 'my-profile-projects',
  ];

  $theme['c4m_user_profile_ecas_login_notice'] = [
    'variables' => [
      'eu_flag_img' => '',
      'ecas_login' => '',
      'ecas_about' => '',
    ],
    'path' => drupal_get_path('module', 'c4m_user_profile') . '/templates',
    'template' => 'ecas-login-notice',
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_page().
 *
 * Remove tabs for registration page.
 */
function c4m_user_profile_preprocess_page(&$variables) {
  if (request_path() == 'user/register') {
    unset($variables['tabs']);
  }
}

/**
 * Implements hook_menu().
 */
function c4m_user_profile_menu() {
  $items = [];

  $items['user/change-mail-resend'] = [
    'title' => 'Change e-mail',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['c4m_user_profile_resend_email_change_confirmation_email_form'],
    'access callback' => TRUE,
    'file' => 'c4m_user_profile.pages.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['user/%user/unsubscribe/%/%/%'] = [
    'title' => 'Unsubscribe user',
    'page callback' => 'c4m_user_profile_unsubscribe_user',
    'page arguments' => [1, 3, 4, 5],
    'access callback' => 'c4m_user_profile_unsubscribe_user_access',
    'access arguments' => [1, 3, 4, 5],
    'type' => MENU_CALLBACK,
  ];

  $items['user/%user/leave'] = [
    'title' => 'Leave platform',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['c4m_user_profile_remove_account_form', 1],
    'access callback' => 'c4m_user_profile_leave_user_access',
    'access arguments' => [1],
    'file' => 'c4m_user_profile.pages.inc',
    'type' => MENU_CALLBACK,
  ];

  $items['user/%user/settings'] = [
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['c4m_user_profile_settings_form', 1],
    'access callback' => 'user_edit_access',
    'access arguments' => [1],
    'type' => MENU_LOCAL_TASK,
    'file' => 'c4m_user_profile.pages.inc',
  ];

  $items['user-organisations'] = [
    'page callback' => '_c4m_user_profile_organisations',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'c4m_user_profile.pages.inc',
  ];

  return $items;
}

/**
 * Implements hook_user_login().
 *
 * It uses the same checks as email_confirm module.
 */
function c4m_user_profile_user_login(&$edit, $user) {
  if (!isset($user->data['email_confirm'])) {
    return;
  }
  if (!isset($user->data['email_confirm']['pending_email']) || $user->data['email_confirm']['expiration_time'] <= REQUEST_TIME) {
    return;
  }
  drupal_set_message(t('You currently have a pending change of your e-mail address to %email. !link to resend the email.', [
    '%email' => $user->data['email_confirm']['pending_email'],
    '!link' => l(t('Click here'), 'user/change-mail-resend'),
  ]), 'warning');
}

/**
 * Implements hook_mail_alter().
 *
 * For users that requested email notifications format to be plaintext,
 * sets 'email confirmation' mail format accordingly.
 */
function c4m_user_profile_mail_alter(&$message) {
  // Mime mail module converts notification mails to 'plain text' format,
  // in case user enabled this option at his profile (loads user profile by
  // mail, and checks if 'mimemail_textonly' is enabled).
  // 'change mail' confirmation notification is special case, since it's not
  // possible to load user by the new email.
  // Therefore, we handle this case explicitly here.
  if ($message['id'] != 'email_confirm_confirmation_email') {
    return;
  }

  // Set 'plain text' format option, as per definition at user profile.
  $message['params']['plain'] = $message['params']['account']->data['mimemail_textonly'];
}

/**
 * Implements hook_email_confirm().
 *
 * Triggers the update info after the email change is confirmed.
 */
function c4m_user_profile_email_confirm($type, $uid) {
  if ($type != 'email confirmation') {
    return;
  }
  $account = user_load($uid);
  // Reset the invalid email flag.
  $edit['c4m_is_invalid_email'][LANGUAGE_NONE]['0']['value'] = 0;
  user_save($account, $edit);

  c4m_user_update_information($account);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_profile_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  // Set the title to `Registration` only if the user did not get to this page
  // via an invitation to join a group.
  if (empty($_SESSION['c4m_og_invite_visitors_gid_join'])) {
    drupal_set_title(t('Registration'));
  }

  $form['eu_login_intro'] = [
    '#type' => 'markup',
    '#markup' =>
    '<p>' .
    t('Complete the form below to register with Capacity4dev.') .
    '<br/>' .
    t('EU staff must authenticate via EU Login') .
    ' - ' .
    t('<a href="@eulogin_url">sign in</a> with EU Login - <a href="@about_eulogin">click here</a> to find more.', [
      '@eulogin_url' => url('ecas', ['absolute' => TRUE]),
      '@about_eulogin' => url('about-eu-login', ['absolute' => TRUE]),
    ]) .
    '</p>',
    '#weight' => -30,
  ];

  // Add checkbox for contact options.
  // @see contact_form_user_profile_form_alter().
  $form['contact'] = [
    '#type' => 'checkbox',
    '#title' => t('Members are allowed to contact you through your personal contact form'),
    '#default_value' => variable_get('contact_default_status', 1),
    '#weight' => 14,
    '#group' => 'group_public_profile',
  ];

  c4m_user_profile_alter_user_form($form, $form_state, TRUE);

  // Add Cancel button.
  $form['actions']['cancel'] = [
    '#type' => 'markup',
    '#markup' => l(t('Cancel'), '<front>', [
      'attributes' => [
        'class' => [
          'btn',
          'btn-default',
        ],
      ],
    ]),
  ];

  // Remove wrapper of the legal accept.
  $form['legal'] = $form['legal']['legal_accept'];

  // Hide some fields from the registration form.
  _c4m_user_profile_alter_registration_form_user($form);

  if (user_access('administer users')) {
    // Hide/rework some additional fields for admins.
    _c4m_user_profile_alter_registration_form_admin($form);
  }

  // Add custom submit handler.
  $form['#submit'][] = 'c4m_user_profile_form_user_register_form_submit';
}

/**
 * Hide non-obligatory fields on the registration form for regular users.
 *
 * @param array $form
 *   Drupal form array.
 */
function _c4m_user_profile_alter_registration_form_user(array &$form) {
  $form['c4m_job_title']['#access'] = FALSE;

  // Hide the public profile group (about me, topics of expertise, geo...).
  field_group_hide_field_groups($form, ['group_public_profile']);
}

/**
 * Hide/disable/rename some fields for administrators on the registration form.
 *
 * @param array $form
 *   Drupal form array.
 */
function _c4m_user_profile_alter_registration_form_admin(array &$form) {
  // Hide status fields - SA-created user is always active.
  $form['account']['status']['#access'] = FALSE;
  // Alter 'notify user' checkbox title.
  $form['account']['notify']['#title'] = t('Send password reset link');

  // When SA creates a user from 'admin/people/create' path, hide roles field,
  // as there's a Drupal bug when SA creates administrators.
  // See: https://issuetracker.amplexor.com/jira/browse/CFM-159.
  // SA can edit user to assign him administrator role though.
  if (drupal_get_path_alias() == 'admin/people/create') {
    $form['account']['roles']['#access'] = FALSE;
  }
}

/**
 * Alters user register / edit profile form.
 *
 * @param array $form
 *   Form array.
 * @param array $form_state
 *   Form state.
 * @param bool $is_registration
 *   Indicate if the form is registration or edit form.
 */
function c4m_user_profile_alter_user_form(array &$form, array &$form_state, $is_registration) {

  $form['#prefix'] = '<div id="user-register-form-wrapper">';
  $form['#suffix'] = '</div>';

  $form['c4m_is_organisation_user'][LANGUAGE_NONE]['#type'] = 'hidden';
  $form['c4m_is_invalid_email'][LANGUAGE_NONE]['#type'] = 'hidden';

  // Move the email input first.
  $form['mail'] = $form['account']['mail'];
  $form['mail']['#weight'] = -25;
  unset($form['account']['mail']);

  // Disable the name field.
  $form['account']['name']['#access'] = FALSE;

  $form['mail']['#ajax'] = [
    'callback' => 'c4m_user_profile_element_validate_mail_ajax',
    'event' => 'blur',
    'method' => 'replace',
    'wrapper' => 'user-register-form-wrapper',
  ];

  // Add wrappers for AJAX replacement.
  $form['mail']['#prefix'] = '<div id="edit-mail-wrapper">';
  $form['mail']['#suffix'] = '</div>';
  $form['c4m_country']['#prefix'] = '<div id="edit-c4m-country-wrapper">';
  $form['c4m_country']['#suffix'] = '</div>';
  $form['c4m_organisation']['#prefix'] = '<div id="edit-c4m-organisation-wrapper">';
  $form['c4m_organisation']['#suffix'] = '</div>';
  $form['c4m_organisation_type']['#prefix'] = '<div id="edit-c4m-organisation-type-wrapper">';
  $form['c4m_organisation_type']['#suffix'] = '</div>';

  if (isset($form_state['values']['mail'])) {
    // Trim whitespace from mail, to prevent confusing 'e-mail not valid'
    // warnings often caused by cutting and pasting.
    $mail = trim($form_state['values']['mail']);
    $validation_messages = [];

    $data['mail'] = $mail;
    $data['minimum_error_level'] = C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE;
    $data['form'] = &$form;
    $data['form_state'] = &$form_state;
    $data['alter_form'] = $is_registration;
    $data['validation_messages'] = &$validation_messages;

    drupal_alter('c4m_user_profile_validate_email', $data);
    uasort($validation_messages, 'element_sort');

    if ($validation_messages) {
      $messages = [];
      foreach ($validation_messages as $validation_message) {
        $type = $validation_message['type'] === C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE ? 'info' : 'danger';
        $messages[] = '<div class="text-' . $type . '">' . $validation_message['message'] . '</div>';

        // Drupal_add_js not working in AJAX context.
        if (!empty($validation_message['js'])) {
          $messages[] = '<script type="text/javascript">' . $validation_message['js'] . '</script>';
        }
      }
      $suffix = '<div id="user-form-mail-validation-message">' . implode("", $messages) . '</div>';
    }
    else {
      $suffix = '<div id="user-form-mail-validation-message" class="hidden"></div>';
    }

    $form['mail']['#suffix'] = $suffix . $form['mail']['#suffix'];
  }

  // Add autocomplete functionality to the Organisation field.
  $form['c4m_organisation'][LANGUAGE_NONE][0]['value']['#autocomplete_path'] = 'user-organisations';

  // Adjust validators.
  // Remove default one and replace it with a custom one.
  if (($key = array_search('user_account_form_validate', $form['#validate'])) !== FALSE) {
    unset($form['#validate'][$key]);
  }
  array_unshift($form['#validate'], 'c4m_user_profile_account_form_validate');
  // Add validator for the email field.
  $form['mail']['#element_validate'][] = 'c4m_user_profile_element_validate_mail';

  // Add custom submit handler.
  $form['#submit'][] = 'c4m_user_profile_form_user_profile_form_submit';
}

/**
 * Simple callback to redirect to user profile.
 */
function c4m_user_profile_simple_cancel(array &$form, array &$form_state) {
  $form_state['redirect'] = 'user';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_profile_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  // Custom title for edit form.
  drupal_set_title(t('Edit profile'));

  $account = $form['#user'];
  $account_wrapper = entity_metadata_wrapper('user', $account);

  $ecas_user = _ecas_is_ecas_user($account);

  // Disable fields if the user is an organisation user and the field has a
  // default value.
  if ($account_wrapper->c4m_is_organisation_user->value()) {
    if (!empty($form['c4m_organisation'][LANGUAGE_NONE][0]['value']['#default_value'])) {
      $form['c4m_organisation'][LANGUAGE_NONE][0]['value']['#attributes']['disabled'] = 'disabled';
    }
    if (!empty($form['c4m_organisation_type'][LANGUAGE_NONE]['#default_value'])) {
      $form['c4m_organisation_type'][LANGUAGE_NONE]['#attributes']['disabled'] = 'disabled';
    }
  }

  c4m_user_profile_alter_user_form($form, $form_state, FALSE);

  if (!$ecas_user) {
    $form['mail']['#description'] = 'Please note you will have to provide your password and confirm your new address to change your e-mail address.';
  }

  // Disable ECAS provided fields.
  _c4m_user_profile_alter_profile_form_disable_ecas_fields($form, $ecas_user);

  // Disable Overlay, Email, Locale and Contact settings.
  // They are moved to Settings page.
  _c4m_user_profile_alter_profile_form_disable_settings_fields($form);

  // Hide the spammer / deleted checkboxes.
  _c4m_user_profile_alter_profile_form_disable_extra_fields($form);

  // Hide OG related fields for non-admin users.
  if (!in_array('administrator', $user->roles)) {
    $form['og_user_node']['#access'] = FALSE;
  }

  // Introduce simple Cancel button (goes to user profile)
  $form['actions']['cancel']['#access'] = FALSE;
  $form['actions']['simple_cancel'] = [
    '#type' => 'button',
    '#submit' => ['c4m_user_profile_simple_cancel'],
    "#executes_submit_callback" => TRUE,
    '#value' => t('Cancel'),
  ];

  if ($account->uid == $user->uid) {
    $form['actions']['delete'] = [
      '#type' => 'markup',
      '#markup' => l(t('Delete account'), 'user/' . $account->uid . '/leave'),
    ];
  }
}

/**
 * Completely disable some user_profile form fields.
 *
 * @param array $form
 *   Render array of the form.
 */
function _c4m_user_profile_alter_profile_form_disable_extra_fields(array &$form) {
  $form['masquerade']['#access'] = FALSE;
  $form['c4m_is_deleted']['#access'] = FALSE;
  $form['c4m_is_deleted_by_uid']['#access'] = FALSE;
  $form['c4m_is_deleted_anonymous']['#access'] = FALSE;
  $form['c4m_is_spammer']['#access'] = FALSE;
  // Hide status field.
  $form['account']['status']['#access'] = FALSE;
  // Remove Terms and conditions fieldset.
  $form['legal']['#access'] = FALSE;
}

/**
 * Disable fields on the user_profile form, that are moved to the settings page.
 *
 * @param array $form
 *   Render array of the form.
 */
function _c4m_user_profile_alter_profile_form_disable_settings_fields(array &$form) {
  $form['overlay_control']['#access'] = FALSE;
  $form['mimemail']['#access'] = FALSE;
  $form['timezone']['#access'] = FALSE;
  $form['contact']['#access'] = FALSE;
}

/**
 * Disable fields on the user_profile form, that are moved to the settings page.
 *
 * @param array $form
 *   Render array of the form.
 */
function _c4m_user_profile_alter_profile_form_disable_ecas_fields(array &$form, $ecas_user) {
  if (!$ecas_user) {
    return;
  }

  $form['c4m_first_name']['#disabled'] = TRUE;
  $form['c4m_last_name']['#disabled'] = TRUE;
  $form['c4m_organisation']['#disabled'] = TRUE;
}

/**
 * AJAX callback for mail field validation.
 */
function c4m_user_profile_element_validate_mail_ajax($form, $form_state) {
  $ajax = [
    '#type' => 'ajax',
    '#commands' => [
      ajax_command_replace('#edit-mail-wrapper', render($form['mail'])),
      ajax_command_replace('#edit-c4m-country-wrapper', render($form['c4m_country'])),
      ajax_command_replace('#edit-c4m-organisation-wrapper', render($form['c4m_organisation'])),
      ajax_command_replace('#edit-c4m-organisation-type-wrapper', render($form['c4m_organisation_type'])),
    ],
  ];
  return $ajax;
}

/**
 * Implements hook_c4m_captcha_form_info().
 */
function c4m_user_profile_c4m_captcha_form_info() {
  return ['user_register_form'];
}

/**
 * Submit callback for user_register_form form.
 */
function c4m_user_profile_form_user_register_form_submit($form, &$form_state) {
  global $language;

  // Accept legal terms and conditions.
  $conditions = legal_get_conditions($language->language);
  legal_save_accept($conditions['version'], $conditions['revision'], $conditions['language'], $form['#user']->uid);

  // Alter the default welcome message from user_registrationpassword module.
  // See user_registrationpassword_form_user_register_submit() to see how it
  // does it too.
  $message = t('A welcome message with further instructions has been sent to your e-mail address.');

  // Unset all messages that contain the $message.
  foreach ($_SESSION['messages']['status'] as $status => $statusmessage) {
    if ($message == $statusmessage) {
      unset($_SESSION['messages']['status'][$status]);
    }
  }
  $_SESSION['messages']['status'] = array_values($_SESSION['messages']['status']);

  $name = $form_state['values']['c4m_first_name'][LANGUAGE_NONE][0]['value'] . ' ' . $form_state['values']['c4m_last_name'][LANGUAGE_NONE][0]['value'];

  // Set success message.
  drupal_set_message(t('Hey @name, thank you for submitting your details. Please activate your account by clicking the link sent to your e-mail.', ['@name' => $name]));

  // Always send "welcome" mail for user created by admin.
  if (user_access('administer users')) {
    _user_mail_notify('status_activated', $form['#user']);
  }
}

/**
 * Submit callback for user_profile_form form.
 */
function c4m_user_profile_form_user_profile_form_submit($form, &$form_state) {
  // Redirect to user profile after submit.
  $form_state['redirect'] = 'user/' . $form_state['user']->uid;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_profile_form_campaignmonitor_admin_settings_general_alter(&$form, &$form_state, $form_id) {
  $form['campaignmonitor_account']['#weight'] = -2;
  $form['campaignmonitor_list'] = [
    '#type' => 'fieldset',
    '#title' => 'List settings',
    '#collapsible' => TRUE,
    '#collapsed' => !$form['campaignmonitor_account']['#collapsed'] || !empty(variable_get('campaignmonitor_list_title')),
    '#weight' => -1,
  ];
  $form['campaignmonitor_list']['campaignmonitor_list_title'] = [
    '#type' => 'textfield',
    '#title' => 'List Title',
    '#default_value' => variable_get('campaignmonitor_list_title'),
  ];
  $form['#submit'][] = 'c4m_user_profile_form_campaignmonitor_admin_settings_general_submit';
}

/**
 * Submit callback for campaignmonitor_admin_settings_general form.
 */
function c4m_user_profile_form_campaignmonitor_admin_settings_general_submit($form, &$form_state) {
  if (isset($form_state['values'])) {
    variable_set('campaignmonitor_list_title', $form_state['values']['campaignmonitor_list_title']);
  }
}

/**
 * Implements hook_module_implements_alter().
 *
 * Our implementation needs to fire after legal module.
 */
function c4m_user_profile_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['c4m_user_profile'])) {
      $c4m_user_profile = $implementations['c4m_user_profile'];
      unset($implementations['c4m_user_profile']);
      $implementations['c4m_user_profile'] = $c4m_user_profile;

      // In order to alter the login/register form on the "c4m_user_og" module
      // we have no other way but use this hook to set the order, because of the
      // alphabetic order of the modules names.
      if (isset($implementations['c4m_user_og'])) {
        $c4m_user_profile = $implementations['c4m_user_og'];
        unset($implementations['c4m_user_og']);
        $implementations['c4m_user_og'] = $c4m_user_profile;
      }
    }

    // In order to alter the login/register form on the "c4m_user" module we
    // have no other way but use this hook to set the order, because of the
    // alphabetic order of the modules names.
    if (isset($implementations['c4m_user'])) {
      $c4m_user_profile = $implementations['c4m_user'];
      unset($implementations['c4m_user']);
      $implementations['c4m_user'] = $c4m_user_profile;
    }
  }
}

/**
 * Validator callback c4m_user_profile_account_form_validate().
 *
 * Replaces user_account_form_validate() and removes the code related to email
 * validation.
 */
function c4m_user_profile_account_form_validate($form, &$form_state) {
  if ($form['#user_category'] != 'account' && $form['#user_category'] != 'register') {
    return;
  }

  // Make sure the signature isn't longer than the size of the database field.
  // Signatures are disabled by default, so make sure it exists first.
  if (isset($form_state['values']['signature'])) {
    // Move text format for user signature into 'signature_format'.
    $form_state['values']['signature_format'] = $form_state['values']['signature']['format'];
    // Move text value for user signature into 'signature'.
    $form_state['values']['signature'] = $form_state['values']['signature']['value'];

    $user_schema = drupal_get_schema('users');
    if (drupal_strlen($form_state['values']['signature']) > $user_schema['fields']['signature']['length']) {
      form_set_error('signature', t('The signature is too long: it must be %max characters or less.', ['%max' => $user_schema['fields']['signature']['length']]));
    }
  }
}

/**
 * Validator callback for mail field.
 */
function c4m_user_profile_element_validate_mail($element, &$form_state, &$form) {
  // Trim whitespace from mail, to prevent confusing 'e-mail not valid'
  // warnings often caused by cutting and pasting.
  $mail = trim($form_state['values']['mail']);
  form_set_value($form['mail'], $mail, $form_state);
  $validation_messages = [];

  $data['mail'] = $mail;
  $data['minimum_error_level'] = C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR;
  $data['form'] = &$form;
  // We need to always alter the form otherwise on AJAX calls (image upload),
  // the validation is run the form is cached but with wrong state for inputs.
  $data['alter_form'] = TRUE;
  $data['form_state'] = &$form_state;
  $data['validation_messages'] = &$validation_messages;

  drupal_alter('c4m_user_profile_validate_email', $data);
  drupal_alter('c4m_user_profile_validate_email_validation_messages', $data['validation_messages']);
  uasort($validation_messages, 'element_sort');

  if ($validation_messages) {
    $messages = [];
    foreach ($validation_messages as $validation_message) {
      $messages[] = $validation_message['message'];
    }
    form_error($element, implode("<br>", $messages));
  }
}

/**
 * Implements hook_c4m_user_profile_validate_email_alter().
 */
function c4m_user_profile_c4m_user_profile_validate_email_alter(&$data) {
  if (!valid_email_address($data['mail'])) {
    $data['validation_messages'][] = [
      'message' => t('The e-mail address %mail is not valid.', ['%mail' => $data['mail']]),
      'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
      '#weight' => -6,
    ];
    return;
  }

  $staff_user = new C4mStaffUser($data['mail']);

  if ($staff_user->isValidStaff()) {
    $ecas_url = url('ecas', ['absolute' => TRUE]);
    if (user_is_anonymous()) {
      $data['validation_messages'][] = [
        'message' => t('EU staff must authenticate via EU Login - Please <a href="@eulogin_url">click here</a> if you are not automatically redirected within a few seconds.', ['@eulogin_url' => $ecas_url]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        'js' => 'window.setTimeout(function(){ window.location.href = "' . $ecas_url . '";}, 5000);',
        '#weight' => -5,
      ];
      return;
    }
    else {
      $data['validation_messages'][] = [
        'message' => t('EU staff must authenticate via EU Login from now on - If you change your email address now, you will need to login with EU Login in the future.'),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE,
        '#weight' => -5,
      ];
    }
  }

  $country = '';
  $organisation_name = '';
  $organisation_type = '';

  $organisation_user = new C4mOrganisationUser($data['mail']);
  if ($organisations = $organisation_user->getOrganisationsInfo()) {
    $organisation = array_shift($organisations);
    $organisation = entity_metadata_wrapper('node', $organisation);

    $organisation_type = $organisation->c4m_organisation_type->value();
    if (empty($organisation_name)) {
      $organisation_name = $organisation->title->value();
    }

    $data['alter_form'] && $data['form']['c4m_is_organisation_user'][LANGUAGE_NONE]['#value'] = 1;

    if ($data['minimum_error_level'] <= C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE) {
      $data['validation_messages'][] = [
        'message' => t('<p>You are recognized as member of !logo - %name<br />If you do not want to be associated with this organization, please !use_another_email.</p>', [
          '!logo' => theme('image_style', [
            'path' => $organisation->c4m_icon->value()['uri'],
            'style_name' => 'icon_small',
          ]),
          '%name' => $organisation->title->value(),
          '!use_another_email' => l(t('use another email address'), '', [
            'fragment' => ' ',
            'external' => TRUE,
            'attributes' => ['class' => ['use-another-email']],
          ]),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_MESSAGE,
        '#weight' => 4,
      ];
    }
  }

  if ($data['alter_form']) {
    if ($country) {
      $data['form']['c4m_country'][LANGUAGE_NONE]['#attributes']['disabled'] = 'disabled';
      $data['form']['c4m_country'][LANGUAGE_NONE]['#value'] = $country;
    }
    if ($organisation_name) {
      $data['form']['c4m_organisation'][LANGUAGE_NONE][0]['value']['#attributes']['disabled'] = 'disabled';
      $data['form']['c4m_organisation'][LANGUAGE_NONE][0]['value']['#value'] = $organisation_name;
    }
    if ($organisation_type) {
      $data['form']['c4m_organisation_type'][LANGUAGE_NONE]['#attributes']['disabled'] = 'disabled';
      $data['form']['c4m_organisation_type'][LANGUAGE_NONE]['#value'] = $organisation_type;
    }
  }

  // Search for error messages.
  $has_errors = FALSE;
  foreach ($data['validation_messages'] as $key => $message) {
    if (isset($message['type']) && $message['type'] == C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR) {
      $has_errors = TRUE;
      break;
    }
  }

  // Only keep the error messages if there're.
  if ($has_errors) {
    foreach ($data['validation_messages'] as $key => $message) {
      if (isset($message['type']) && $message['type'] != C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR) {
        unset($data['validation_messages'][$key]);
      }
    }
  }

  if (!($other_user = user_load_by_mail($data['mail'])) || isset($data['form_state']['user']->uid) && $other_user->uid == $data['form_state']['user']->uid) {
    return;
  }

  $other_user_wrapper = entity_metadata_wrapper('user', $other_user);
  if ($other_user_wrapper->status->value()) {
    if ($staff_user->isValidStaff() || _ecas_is_ecas_user($other_user)) {
      $data['validation_messages'][] = [
        'message' => t('This account is already in use. If this is you, please !login_ecas.', [
          '!login_ecas' => l(t('log in with your EU login account'), 'ecas'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => -5,
      ];
    }
    else {
      $data['validation_messages'][] = [
        'message' => t('This account is already in use. If this is you, please !login or !request_password.', [
          '!login' => l(t('log in'), 'user/login'),
          '!request_password' => l(t('request a new password'), 'user/password'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => -5,
      ];
    }
  }
  else {
    $error = FALSE;

    if (!$other_user_wrapper->last_login->value() && !$other_user_wrapper->last_access->value()) {
      $data['validation_messages'][] = [
        'message' => t('This email address is already in use. Please activate your account, or !resend_activation.', [
          '!resend_activation' => l(t('re-send the activation mail'), 'user/' . $other_user_wrapper->uid->value() . '/resend-activation-email'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => -4,
      ];
      $error = TRUE;
    }
    if ($other_user_wrapper->c4m_is_spammer->value()) {
      $data['validation_messages'][] = [
        'message' => t('This account has been blocked. !contact site administrator for more information.', [
          '!contact' => l(t('Contact'), 'contact'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => 1,
      ];
      $error = TRUE;
    }
    if ($other_user_wrapper->c4m_is_deleted->value()) {
      $data['validation_messages'][] = [
        'message' => t('There is a problem with your account, please !contact the site administrators.', [
          '!contact' => l(t('contact'), 'contact'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => 2,
      ];
      $error = TRUE;
    }

    if (!$error) {
      // No specific error given, add the default one.
      // Migrated users can be inactive without specific spammer/deleted status.
      $data['validation_messages'][] = [
        'message' => t('There is a problem with your account, please !contact the site administrators.', [
          '!contact' => l(t('contact'), 'contact'),
        ]),
        'type' => C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR,
        '#weight' => -10,
      ];
    }
  }
}

/**
 * Implements hook_c4m_user_profile_validate_email_validation_messages_alter().
 */
function c4m_user_profile_c4m_user_profile_validate_email_validation_messages_alter(&$messages) {
  // Search for error messages.
  $has_errors = FALSE;
  foreach ($messages as $key => $message) {
    if (isset($message['type']) && $message['type'] == C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR) {
      $has_errors = TRUE;
      break;
    }
  }

  // Only keep the error messages if there're.
  if ($has_errors) {
    foreach ($messages as $key => $message) {
      if (isset($message['type']) && $message['type'] != C4M_USER_PROFILE_VALIDATION_MESSAGE_TYPE_ERROR) {
        unset($messages[$key]);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Replace the user_login_name_validate() from the user_login form.
 */
function c4m_user_profile_form_user_login_alter(&$form, &$form_state, $form_id) {
  // If Drupal Core's "user_login_name_validate"-function is present, remove it.
  if (($key = array_search('user_login_name_validate', $form['#validate'])) !== FALSE) {
    unset($form['#validate'][$key]);
  }

  // Add our custom "user_login_validate" instead.
  array_unshift($form['#validate'], 'c4m_user_profile_user_login_validate');

  $form['#validate'][] = 'c4m_user_profile_user_login_validate_ecas';
}

/**
 * Wrapper around user module to check if user is known as ecas user.
 *
 * @param string $username
 *   Drupal user name user tries to log in with.
 *
 * @return bool
 *   TRUE if user is recognized in the db as ecas user.
 */
function c4m_user_profile_is_user_ecas($username) {
  if (!module_exists('ecas')) {
    return FALSE;
  }

  $maps = user_get_authmaps($username);
  if (!array_key_exists('ecas', (array) $maps)) {
    return FALSE;
  }
  return $maps['ecas'] === $username;
}

/**
 * Check if a user has a valid staff domain mail address.
 *
 * @param string $mail
 *   Email address to check for valid staff doma/in.
 *
 * @return bool
 *   TRUE if the user's mail domain belongs to EC Staff.
 */
function c4m_user_profile_is_email_ecas_staff($mail) {
  $staffUser = new C4mStaffUser($mail);
  return $staffUser->isValidStaff();
}

/**
 * Validate callback for user_login form.
 *
 * @see user_login_name_validate()
 */
function c4m_user_profile_user_login_validate($form, &$form_state) {
  if (empty($form_state['values']['name'])) {
    return;
  }
  $username = $form_state['values']['name'];
  $account = user_load_by_name($username);

  // Username not found.
  if (!$account) {
    return;
  }

  // User is active.
  if (!empty($account->status)) {
    return;
  }

  $account = entity_metadata_wrapper('user', $account);
  if (!$account->c4m_is_deleted->value() && !$account->c4m_is_spammer->value() && !$account->last_login->value()) {
    $message = t('You used valid credentials but your account is not activated yet. Use the !password_recovery form to resend the activation email.', ['!password_recovery' => l(t('password recovery'), 'user/password')]);
  }
  elseif ($account->c4m_is_spammer->value()) {
    $message = t('This account has been blocked, for more information please !contact an administrator.', ['!contact' => l(t('contact'), 'contact')]);
  }
  elseif ($account->c4m_is_deleted->value()) {
    $message = t('There is a problem with your account, please !contact the site administrators.', ['!contact' => l(t('contact'), 'contact')]);
  }
  else {
    $message = t('Sorry, unrecognized username or password. <a href="@password">Have you forgotten your password?</a>', ['@password' => url('user/password')]);
  }
  form_set_error('name', $message);
}

/**
 * Validate user login form to see if username/email is linked to EU Login user.
 */
function c4m_user_profile_user_login_validate_ecas($form, &$form_state) {
  if (empty($form_state['values']['name'])) {
    return;
  }
  $username = $form_state['values']['name'];
  if (c4m_user_profile_is_user_ecas($username)) {
    // Clear errors.
    form_clear_error();
    // Clear error messages.
    drupal_get_messages('error');

    form_set_error('name', t("You're account is linked with an EU login account. Please login via !eu_login or !contact if you have no longer access to this account.", [
      '!eu_login' => l(t('EU Login'), 'ecas'),
      '!contact' => l(t('contact us'), 'contact'),
    ]));
    return;
  }

  if (c4m_user_profile_is_email_ecas_staff($username)) {
    // Clear errors.
    form_clear_error();
    // Clear error messages.
    drupal_get_messages('error');

    form_set_error('name', t("You're account is recognized as an EC Staff domain. Please login via !eu_login or !contact if you have no longer access to this account.", [
      '!eu_login' => l(t('EU Login'), 'ecas'),
      '!contact' => l(t('contact us'), 'contact'),
    ]));
    return;
  }
}

/**
 * Implements hook_context_registry().
 */
function c4m_user_profile_context_registry() {
  $registry['conditions'] = [
    'c4m_user' => [
      'title' => t('C4M User Profile'),
      'plugin' => 'c4m_user_profile_context_user',
    ],
  ];
  return $registry;
}

/**
 * Implements hook_context_plugins().
 */
function c4m_user_profile_context_plugins() {
  $plugins['c4m_user_profile_context_user'] = [
    'handler' => [
      'path' => drupal_get_path('module', 'c4m_user_profile') . '/plugins',
      'file' => 'c4m_user_profile_context_user.inc',
      'class' => 'c4m_user_profile_context_user',
      'parent' => 'context_condition',
    ],
  ];
  return $plugins;
}

/**
 * Implements hook_init().
 */
function c4m_user_profile_init() {
  global $user;

  if ($user->uid && $plugin = context_get_plugin('condition', 'c4m_user')) {
    $plugin->execute($user);
  }
}

/**
 * Gets the unsubscribe hash.
 *
 * @param int $uid
 *   The user ID.
 * @param string $flag_suffix
 *   The flag suffix to unsubscribe from.
 * @param string $entity_id
 *   The ID of the entity to unsubscribe from.
 *
 * @return string
 *   The unsubscribe hash.
 */
function c4m_user_profile_get_unsubscribe_hash($uid, $flag_suffix, $entity_id) {
  $hash = md5($uid . ':::' . $flag_suffix . ':::' . $entity_id . ':::' . drupal_get_private_key());
  return $hash;
}

/**
 * Access callback; Unsubscribe a user.
 *
 * @param object $account
 *   The user account.
 * @param string $flag_suffix
 *   The flag suffix to unsubscribe from.
 * @param string $entity_id
 *   The ID of the entity to unsubscribe from.
 * @param string $hash
 *   The unsubscribe hash string.
 *
 * @return bool
 *   TRUE if user has access.
 */
function c4m_user_profile_unsubscribe_user_access($account, $flag_suffix, $entity_id, $hash) {
  if (!$account || c4m_user_is_spammer($account) || $account->status === 0) {
    return FALSE;
  }

  if (c4m_user_profile_get_unsubscribe_hash($account->uid, $flag_suffix, $entity_id) !== $hash) {
    return FALSE;
  }

  // Validate entity ID.
  try {
    if ($flag_suffix === 'group' || $flag_suffix === 'comment') {
      $entity_type = 'node';
    }
    else {
      $entity_type = $flag_suffix;
    }
    $wrapper = entity_metadata_wrapper($entity_type, $entity_id);
    if (!$wrapper->value()) {
      return FALSE;
    }
  }
  catch (\EntityMetadataWrapperException $e) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Access callback for "Leave platform" page.
 *
 * @param object $account
 *   The user object.
 *
 * @return bool
 *   TRUE if user has access.
 */
function c4m_user_profile_leave_user_access($account) {
  global $user;

  if ($account->uid != $user->uid) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Page callback; Unsubscribe a user.
 *
 * @param object $account
 *   The user account.
 * @param string $entity_type
 *   The flag suffix to unsubscribe from.
 * @param string $entity_id
 *   The ID of the entity to unsubscribe from.
 */
function c4m_user_profile_unsubscribe_user($account, $entity_type, $entity_id) {
  $flag = flag_get_flag('subscribe_c4m_follow_' . ($entity_type === 'taxonomy_term' ? 'term' : $entity_type));
  module_load_include('inc', 'c4m_user_profile', 'c4m_user_profile.pages');
  $flaggings = c4m_user_profile_get_flag_flaggings($flag, $account);

  foreach ($flaggings as $flagging_id) {
    $flagging = flagging_load($flagging_id);

    if ($flagging->entity_id !== $entity_id) {
      continue;
    }

    $flagging->preference = C4M_MESSAGE_DIGEST_FREQUENCY_NEVER;
    c4m_message_digest_set_preference($flagging);
    break;
  }

  drupal_set_message(t('Successfully unsubscribed'));
  drupal_goto();
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_user_profile_c4m_helper_entity_metrics_info() {
  return [
    'c4m_user_expertise_topics' => [
      'type' => 'expertise_topics',
      'context' => 'user',
      'callback' => 'c4m_user_profile_get_expertise_topics',
    ],
  ];
}

/**
 * Gets the IDs of the topics (interests) of a user.
 *
 * @param object|int $account
 *   The user object or ID (optional).
 *   If not given then use the current user.
 *
 * @return array
 *   The terms IDs of the topics.
 */
function c4m_user_profile_get_interests($account = NULL) {
  if (!$account) {
    global $user;
    $account = $user;
  }

  $wrapper = entity_metadata_wrapper('user', $account);

  return $wrapper->c4m_vocab_topic->raw();
}

/**
 * Returns the expertise topics count for an user.
 *
 * @param int $uid
 *   User id.
 *
 * @return int
 *   Count.
 */
function c4m_user_profile_get_expertise_topics($uid) {
  $query = db_select('field_data_c4m_vocab_topic_expertise', 'e');
  $query->fields('e', ['delta']);
  $query->condition('entity_type', 'user');
  $query->condition('entity_id', $uid);

  $query = $query->execute();
  $amount = $query->rowCount();

  return $amount;
}

/**
 * Gets the custom cancellations methods we should reassign the content.
 *
 * @return array
 *   The c4m custom cancellations methods machine names.
 */
function c4m_user_profile_get_cancel_methods_to_reassign() {
  return [
    'c4m_user_admin_block_anonymous',
  ];
}

/**
 * Implements hook_user_cancel().
 *
 * Implements the functionality for the custom cancellation method that blocks
 * and reassigns.
 * Removes all user cookies and session information when an user leaves the
 * platform.
 */
function c4m_user_profile_user_cancel($edit, $account, $method) {
  global $user;

  $wrapper = entity_metadata_wrapper('user', $account);

  $wrapper->c4m_is_deleted->set(TRUE);
  $wrapper->c4m_is_deleted_by_uid->set($user->uid);

  // By default, the cancellation blocks the user, so we only care about the
  // content reassign that is already implemented in the node hook
  // implementation.
  if (in_array($method, c4m_user_profile_get_cancel_methods_to_reassign())) {
    $wrapper->c4m_is_deleted_anonymous->set(TRUE);
    node_user_cancel($edit, $account, 'user_cancel_reassign');
  }

  user_save($account);

  // Remove all the session information of the account.
  $query = db_delete('sessions');
  $query->condition('uid', $account->uid);
  $query->execute();

  // We should not clear the cookies for admins that canceling a different user
  // account.
  if ($user->uid !== $account->uid && c4m_user_is_site_admin()) {
    return;
  }

  // Remove all the cookies.
  // @see http://www.php.net/manual/en/function.setcookie.php#73484
  if (isset($_SERVER['HTTP_COOKIE'])) {
    $cookies = explode(';', $_SERVER['HTTP_COOKIE']);

    foreach ($cookies as $cookie) {
      $parts = explode('=', $cookie);
      $name = trim($parts[0]);
      // Cookies can't be really deleted as they are in the user browser.
      // Instead of deleted, we set a expiration date in the past so the brower
      // sees the cookie has expired and removes it.
      // The two set cookies is to ensure that the cookie is removed
      // independently if is set on the current path or the full site.
      unset($_COOKIE[$name]);
      setcookie($name, '', -1);
      setcookie($name, '', -1, '/');
    }
  }
}
