<?php

/**
 * @file
 * Invite new members to a group or project.
 */

/**
 * Implements hook_menu().
 *
 * Defines a path for the page/form used to invite visitors into a group.
 */
function c4m_og_invite_visitors_menu() {
  $items = [];

  $items['group/%/%/admin/people/overview'] = [
    'title' => 'Manage memberships',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  ];

  $items['group/%/%/admin/people/invite-visitors'] = [
    'title' => 'Invite members',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['_c4m_og_invite_visitors_new_users_form', 2],
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    'access callback' => 'c4m_og_invite_visitors_user_access',
    'access arguments' => [2],
  ];

  $items['user/registration/join-group/%node/%'] = [
    'title' => 'Join Capacity 4 More',
    'type' => MENU_CALLBACK,
    'page callback' => 'c4m_og_invite_visitors_process_acceptance',
    'page arguments' => [3, 4],
    'access callback' => 'c4m_og_invite_visitors_process_acceptance_access',
    'access arguments' => [3, 4],
  ];

  return $items;
}

/**
 * Validate the token in the group invitation link.
 *
 * @param object $group
 *   The group to join.
 * @param string $token
 *   The invitation random token to validate.
 *
 * @return bool
 *   Redirect or return positive access to process the invitation.
 */
function c4m_og_invite_visitors_process_acceptance_access($group, $token) {
  // No group loaded.
  if (!$group) {
    return FALSE;
  }

  // Retrieve the invitation object from the DB.
  $invitation = _c4m_og_invite_visitors_get_invitation_by_token($group->nid, $token);

  // Invitation with the requested token could not be found.
  if (!$invitation) {
    // Clear all previous messages.
    drupal_get_messages('error');
    drupal_set_message('The requested group invitation was not found.', 'error');

    return FALSE;
  }

  // The invitation has been used before.
  if ($invitation->inv_expired) {
    // Clear all previous messages.
    drupal_get_messages('error');
    drupal_set_message('The requested group invitation has expired.', 'error');

    return FALSE;
  }

  return TRUE;
}

/**
 * Get an invitation object from the DB by group ID and token.
 *
 * @param int $gid
 *   ID of the group we are checking for.
 * @param string $token
 *   The invitation random token.
 *
 * @return bool|object
 *   Invitation object from the DB or FALSE on failure.
 */
function _c4m_og_invite_visitors_get_invitation_by_token($gid, $token) {
  $result = &drupal_static(__FUNCTION__);

  $key = 'invitation-' . $token;

  if (!isset($result[$key])) {
    $invite_db_fields = [
      'inv_id',
      'inv_email',
      'inv_expired',
    ];

    $result[$key] = db_select('c4m_og_invite_visitors', 'inv')
      ->fields('inv', $invite_db_fields)
      ->condition('inv_group_id', $gid)
      ->condition('inv_token', $token)
      ->range(0, 1)
      ->execute()
      ->fetchObject();
  }

  return $result[$key];
}

/**
 * Get an invitation object from the DB by group ID and email.
 *
 * @param int $gid
 *   ID of the group we are checking for.
 * @param string $email
 *   The invitation email.
 *
 * @return bool|object
 *   Invitation object from the DB or FALSE on failure.
 */
function _c4m_og_invite_visitors_get_invitation_by_email($gid, $email) {
  $result = &drupal_static(__FUNCTION__);

  $key = 'invitation-' . $gid . ':' . $email;

  if (!isset($result[$key])) {
    $invite_db_fields = [
      'inv_id',
      'inv_email',
      'inv_expired',
    ];

    $result[$key] = db_select('c4m_og_invite_visitors', 'inv')
      ->fields('inv', $invite_db_fields)
      ->condition('inv_group_id', $gid)
      ->condition('inv_email', $email)
      ->range(0, 1)
      ->execute()
      ->fetchObject();
  }

  return $result[$key];
}

/**
 * Validate the accept invitation url before displaying the registration form.
 *
 * Make sure the invitation and the URL itself are legitimate.
 *
 * @param object $group
 *   The group object should be loaded from the acceptance URL.
 */
function c4m_og_invite_visitors_process_acceptance($group, $token) {
  global $user;

  // Retrieve the invitation object from the DB.
  $invitation = _c4m_og_invite_visitors_get_invitation_by_token($group->nid, $token);

  if (user_is_logged_in()) {

    // The invited visitor registered himself and logged in to the site before
    // clicking on the invitation link.
    if ($user->mail == $invitation->inv_email) {

      // The user is not a member. Add the user to the group.
      if (!og_is_member('node', $group->nid, 'user', $user)) {
        og_group('node', $group, ['entity' => $user]);
      }
    }
    // A different user is logged in. Display an error.
    else {
      drupal_set_message('Another user is logged in. Please log out and try again.', 'error');
    }

    // The invited email is registered. Proceed to the group dashboard.
    drupal_goto($group->purl);
  }

  // The invited email is not registered. Redirect to the registration form.
  // Set the group to join in a session variable and redirect to user/register.
  $_SESSION['c4m_og_invite_visitors_gid_join'] = $group->nid;
  drupal_goto('user/register');
}

/**
 * Implements hook_og_ui_get_group_admin().
 *
 * Adds a menu item (Invite visitors) to the group administration page. Links to
 * the invite visitors form.
 */
function c4m_og_invite_visitors_og_ui_get_group_admin($group_type, $gid) {
  $items = [];
  if (og_user_access($group_type, $gid, 'invite visitors')) {
    $items['c4m_og_invite_visitors'] = [
      'title' => t('Invite members'),
      'description' => t('Invite users or create new users and add them as group members.'),
      'href' => 'admin/people/invite-visitors',
    ];
  }

  return $items;
}

/**
 * Invite access. Checks if the user is allowed to invite visitors to the group.
 *
 * Checks by user role and og_role against group visibility (Public/Private) and
 * Membership requests setting (Open/Moderated).
 *
 * @param int $gid
 *   The group #ID from the URL.
 *
 * @return bool
 *   Grand/deny access for inviting visitors.
 */
function c4m_og_invite_visitors_user_access($gid) {

  return c4m_og_invite_access('node', $gid);
}

/**
 * Implements hook_og_permission().
 *
 * Adds a group permissions to invite visitors to a group.
 */
function c4m_og_invite_visitors_og_permission() {
  $items = [];
  $items['invite visitors'] = [
    'title' => t('Invite visitors'),
    'description' => t('Users may invite visitors to the group.'),
    'default role' => [OG_ADMINISTRATOR_ROLE],
  ];

  return $items;
}

/**
 * Main OG Invite visitors form.
 *
 * Defines the form structure for inviting visitors to join a group.
 *
 * @param object $form
 *   Form object.
 * @param object $form_state
 *   Form state object.
 * @param int $gid
 *   Group ID.
 *
 * @return object
 *   Newly created form object.
 */
function _c4m_og_invite_visitors_new_users_form($form, &$form_state, $gid) {
  $group = node_load($gid);
  og_set_breadcrumb('node', $group->nid, [l(t('Group'), "node/" . $group->nid . "/group")]);
  $label = entity_label('node', $group);

  $form['gid'] = [
    '#type' => 'value',
    '#value' => $group->nid,
  ];
  // str_replace result is the path to `Manage the group members`.
  $form['manage_group_people'] = [
    '#type' => 'link',
    '#href' => str_replace('/invite-visitors', '', $_GET['q']),
    '#title' => 'Manage all group memberships',
    '#access' => c4m_features_og_members_is_power_user(),
  ];
  $form['c4m_og_invite_visitors'] = [
    '#type' => 'fieldset',
    '#title' => t('Invite new users to %group', ['%group' => $label]),
  ];
  $form['c4m_og_invite_visitors']['invitee'] = [
    '#type' => 'textarea',
    '#title' => t('User email(s)'),
    '#description' => t("Use commas or new lines to split email addresses. The new users will be created and invited as members of this group. A one time login link will be sent to the invitees\' email."),
    '#required' => TRUE,
  ];
  $form['c4m_og_invite_visitors']['personal_subject'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t('Add a personal subject to the invitation email.'),
  ];
  $form['c4m_og_invite_visitors']['personal_message'] = [
    '#type' => 'textarea',
    '#title' => t('Add a message (optional)'),
    '#description' => t('Add a personal message to the invitation email.'),
  ];

  $form['actions'] = [
    '#type' => 'actions',
    'submit' => [
      '#type' => 'submit',
      '#value' => t('Invite user(s)'),
    ],
  ];

  return $form;
}

/**
 * Validation handler for _c4m_og_invite_visitors_new_users_form.
 *
 * Check the list of emails to invite and filter out invalid entries. File an
 * error for the filtered addresses (if any).
 */
function _c4m_og_invite_visitors_new_users_form_validate($form, &$form_state) {
  // Split the list of email addresses by comma, newline or white space.
  $invitee_emails = preg_split('/\s*[,\n]\s*/', $form_state['values']['invitee']);
  $gid = $form_state['values']['gid'];
  $form_state['invitees'] = [];

  foreach (array_filter($invitee_emails) as $invitee_email) {
    if (!valid_email_address($invitee_email)) {
      form_set_error('invitee', t('Invalid email @email.', ['@email' => $invitee_email]));
      continue;
    }
    $result = _c4m_og_invite_visitors_determine_user_action($invitee_email, $gid);
    if ($result === 0) {
      // Not a registered user.
      $result = _c4m_og_invite_visitors_get_invitation_by_email($gid, $invitee_email);
      if ($result) {
        // Already invited.
        form_set_error('invitee', t('@email has already been invited.', ['@email' => $invitee_email]));
      }
      else {
        // Not already invited.
        $form_state['invitees'][$invitee_email] = FALSE;
      }
    }
    elseif ($result > 0) {
      // Registered user.
      $form_state['invitees'][$invitee_email] = $result;
    }
    else {
      // Spammer or member of the group. Message is already set.
      form_set_error('invitee');
    }
  }
}

/**
 * Submit handler for _c4m_og_invite_visitors_new_users_form.
 *
 * Creates a new user for each invited visitor. Creates an OG membership and
 * adds the user to the group.
 */
function _c4m_og_invite_visitors_new_users_form_submit($form, &$form_state) {
  global $user;
  $gid = $form_state['values']['gid'];
  $invitees = $form_state['invitees'];
  $form_fields = [
    'subject' => $form_state['values']['personal_subject'],
    'body' => $form_state['values']['personal_message'],
  ];

  foreach ($invitees as $invitee => $uid) {
    if (!$uid) {
      _c4m_og_invite_visitors_action_invite_visitors($user->uid, $gid, $invitee, $form_fields);
    }
    else {
      // Invoke the invite_user functionality.
      $field_name = key(og_get_group_audience_fields());
      c4m_og_invite_users_invite($gid, $field_name, $uid, $form_fields['body'], $form_fields['subject']);
      drupal_set_message(t('An email notification was sent to %address.', ['%address' => $invitee]));
    }
  }
}

/**
 * Determine if an existing user should be invited.
 *
 * Allows the invitation only if the user is not marked as a spammer and not
 * already a member of the group.
 *
 * @param string $invitee_email
 *   Invitee email address to check.
 * @param int $gid
 *   Group ID for the invitation.
 *
 * @return int
 *   - 0 if the provided email address doesn't correspond to a registered user.
 *   - -1 if the provided email address corresponds to a member of the group or
 *   to a spammer user. An error message is also set.
 *   - uid - The uid of the user registered with that email address.
 */
function _c4m_og_invite_visitors_determine_user_action($invitee_email, $gid) {
  // Try to load the user by email or return early.
  if (!$account = user_load_by_mail($invitee_email)) {
    return 0;
  }

  $wrapper = entity_metadata_wrapper('user', $account);

  // Do not invite a user who is already a member of the group.
  if ($og_membership = og_get_membership('node', $gid, 'user', $account->uid)) {
    // Member is blocked, display a link to the manage people page.
    if ($og_membership->state == OG_STATE_BLOCKED) {
      $link = l(t('Manage the group members.'), 'group/node/' . $og_membership->gid . '/admin/people');
      drupal_set_message(t('%user is a blocked member of this group. !people-page-link', [
        '%user' => $invitee_email,
        '!people-page-link' => $link,
      ]), 'error');
    }
    else {
      drupal_set_message(t('%user is already a member of this group.', ['%user' => $invitee_email]), 'warning');
    }

    return -1;
  }

  // Do not invite a user who is marked as a spammer.
  if ($wrapper->c4m_is_spammer->value()) {
    $message = t('We encountered a problem inviting %address. Please <a href="@contact-page">contact the site administrator</a>.', [
      '%address' => $wrapper->mail->value(),
      '@contact-page' => url('contact', ['purl' => ['disabled' => TRUE]]),
    ]);
    drupal_set_message($message, 'error');

    return -1;
  }

  // To invite an existing user we need his / her uid.
  return $account->uid;
}

/**
 * Saves an invitation in the DB and sends a email with the acceptance link.
 *
 * @param int $inviter_uid
 *   User ID of the inviting member.
 * @param int $gid
 *   Group ID.
 * @param string $invitee_email
 *   Invited visitor's email address.
 * @param array $form_fields
 *   Email personal message and subject.
 */
function _c4m_og_invite_visitors_action_invite_visitors($inviter_uid, $gid, $invitee_email, array $form_fields) {
  // Saves invitation in the DB and invites the visitor.
  $invitation = c4m_og_invite_visitors_store_invitation($inviter_uid, $gid, $invitee_email);

  // An error saving the invitation to the DB.
  if (!$invitation) {
    drupal_set_message(t('An error occurred inviting %address to the group.', ['%address' => $invitee_email]), 'error');
    return;
  }

  $from = c4m_message_get_from_field_default_pattern();

  // Send the invitation email.
  drupal_mail('c4m_og_invite_visitors', 'invite_group_member', $invitee_email, NULL, [
    'form_fields' => $form_fields,
    'invitation' => $invitation,
  ], $from);

  drupal_set_message(t('An email notification was sent to %address.', ['%address' => $invitee_email]));
}

/**
 * Implements hook_mail().
 *
 * Alters the email sent to visitors when they are invited to join a group. The
 * email subject and body are loaded from template files with the same name as
 * the email identification $key.
 */
function c4m_og_invite_visitors_mail($key, &$message, $params) {
  $variables = [
    'message' => $message,
    'form_fields' => $params['form_fields'],
    'invitation' => $params['invitation'],
  ];
  $message['subject'] .= _c4m_og_invite_visitors_get_email_template($key . '_subject', $variables);
  $message['body'][] = _c4m_og_invite_visitors_get_email_template($key . '_body', $variables);
}

/**
 * Returns a mail template for a variable name.
 *
 * Used by c4m_og_invite_visitors_mail() and the settings forms to retrieve
 * strings.
 *
 * @param string $key
 *   Email identification key.
 * @param array $variables
 *   Data array needed to fill in the tokens in the email template.
 * @param bool $replace
 *   Replace token in the email template.
 *
 * @return string|null
 *   An email string or NULL.
 */
function _c4m_og_invite_visitors_get_email_template($key, array $variables = [], $replace = TRUE) {
  // Load the template from variable.
  $text = variable_get($key, FALSE);

  // Replace the tokens in the template with the correct data.
  if ($replace) {
    return token_replace($text, $variables, [
      'callback' => 'c4m_og_invite_visitors_mail_tokens',
      'sanitize' => FALSE,
      'clear' => TRUE,
    ]);
  }

  return $text;
}

/**
 * Token callback to add unsafe tokens for user mails.
 *
 * This function is used by the token_replace() call at the end of
 * _c4m_og_invite_visitors_mail_text() to set up some additional tokens that can
 * be used in email messages generated by c4m_og_invite_visitors_mail().
 *
 * @param array $replacements
 *   An associative array variable containing mappings from token names to
 *   values (for use with strtr()).
 * @param array $data
 *   An associative array of token replacement values. If the 'user' element
 *   exists, it must contain a user account object with the following
 *   properties:
 *   - login: The UNIX timestamp of the user's last login.
 *   - pass: The hashed account login password.
 * @param array $options
 *   Unused parameter required by the token_replace() function.
 */
function c4m_og_invite_visitors_mail_tokens(array &$replacements, array $data, array $options) {
  global $user, $base_url;

  $group = c4m_og_current_group();
  $url_options = ['absolute' => TRUE];

  $replacements['[user:full_name]'] = c4m_user_name($user);
  $replacements['[user:public-profile-url]'] = $base_url . '/users/' . c4m_og_human_to_machine_readable($replacements['[user:full_name]']);
  $replacements['[group:node_type]'] = $group->type;
  $replacements['[group:node_title]'] = $group->title;
  $replacements['[group:accept_invite_url]'] = url('user/registration/join-group/' . $group->nid . '/' . $data['invitation']['token'], $url_options);
  $replacements['[personal:subject]'] = $data['form_fields']['subject'];
  $replacements['[personal:body]'] = $data['form_fields']['body'];
  $replacements['[site:name]'] = variable_get('site_name', 'Capacity 4 More');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Change the submit button value for the invite visitors registration form and
 * add a custom submit handler.
 */
function c4m_og_invite_visitors_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  if (empty($_SESSION['c4m_og_invite_visitors_gid_join'])) {
    return;
  }

  $group = node_load($_SESSION['c4m_og_invite_visitors_gid_join']);

  list($join_phrase, $button_label) = _c4m_og_registration_form_labels_by_group($group->nid);

  $variables = [
    'join_phrase' => $join_phrase,
    'group_title' => $group->title,
    'group_type' => c4m_og_get_group_type_from_node($group, TRUE),
    'login_link' => l(t('Log in.'), 'user/login'),
  ];
  drupal_set_title(theme('c4m_unified_workflow_register', $variables), PASS_THROUGH);

  $form['#submit'][] = 'c4m_og_invite_visitors_register_submit';
  $form['actions']['submit']['#value'] = $button_label;
}

/**
 * A submit handler for the invite visitors registration.
 *
 * Setting a message to the user and redirect back to the group.
 */
function c4m_og_invite_visitors_register_submit($form, &$form_state) {
  if (empty($_SESSION['c4m_og_invite_visitors_gid_join'])) {
    return;
  }

  $gid = $_SESSION['c4m_og_invite_visitors_gid_join'];

  // Void the invitation token in the database after registration completes and
  // add the new user ID.
  $account = $form_state['user'];
  c4m_og_invite_visitors_void_invitation($account->uid, $account->mail, $gid);
  $edit['data'] = [
    'join_group' => $gid,
  ];
  user_save($account, $edit);
  unset($_SESSION['c4m_og_invite_visitors_gid_join']);

  // drupal_goto has a fallback to the 'destination' so we must remove it.
  unset($_GET['destination']);
}

/**
 * Invalidate invitation record in the DB.
 *
 * @param int $uid
 *   User ID to add to the invitation record.
 * @param string $email
 *   Invitee email address to find.
 * @param int $gid
 *   ID of the group for which to find an invitation.
 *
 * @return int
 *   Number of invitations set as expired.
 */
function c4m_og_invite_visitors_void_invitation($uid, $email, $gid) {
  try {
    $num_updated = db_update('c4m_og_invite_visitors')
      ->fields([
        'inv_uid' => $uid,
        'inv_updated' => REQUEST_TIME,
        'inv_expired' => 1,
      ])
      ->condition('inv_email', $email, '=')
      ->condition('inv_group_id', $gid, '=')
      ->execute();
  }
  catch (PDOException $e) {
    watchdog('c4m_og_invite_visitors', $e->getMessage(), NULL, WATCHDOG_ERROR);
    $num_updated = 0;
  }

  return $num_updated;
}

/**
 * Implements hook_user_update().
 *
 * When account is activated, add the user, as active member,
 * to the group he was invited into.
 */
function c4m_og_invite_visitors_user_update(&$edit, $account, $category) {
  // Original status was "Active".
  // For some reason the status in the original object is string.
  if ($account->original->status != '0') {
    return;
  }

  // Current status is "Not active".
  if ($account->status != 1) {
    return;
  }

  if (empty($account->data['join_group'])) {
    return;
  }

  $group = node_load($account->data['join_group']);
  // Removing the original message of the user_register_form.
  drupal_get_messages('status');
  $message = t('Welcome to group @group_title.', ['@group_title' => $group->title]);

  drupal_set_message($message);
  $form_state['redirect'] = drupal_get_path_alias('node/' . $group->nid);

  // Add the user to the group.
  og_group('node', $group, ['entity' => $account]);

  // Add the administrator role for users joining a project.
  $bundle = 'project';
  if ($group->type === $bundle) {
    $role = c4m_og_user_role_load_by_name('administrator member', $bundle);
    og_role_grant('node', $group->nid, $account->uid, $role->rid);
  }
}

/**
 * Store invitation entry in the DB table c4m_og_invite_visitors.
 *
 * @param int $inviter_id
 *   ID of the inviting user.
 * @param int $group_id
 *   ID of the group for which the invitation is created.
 * @param string $email
 *   Email address of the invitee.
 *
 * @return array|bool
 *   The token that was hashed and stored to validate the invitation and the
 *   invitation ID.
 */
function c4m_og_invite_visitors_store_invitation($inviter_id, $group_id, $email) {

  $token = drupal_hash_base64($email . drupal_random_key() . REQUEST_TIME);

  try {
    $invId = db_insert('c4m_og_invite_visitors')->fields([
      'inv_inviter_id' => $inviter_id,
      'inv_group_id' => $group_id,
      'inv_email' => $email,
      'inv_created' => REQUEST_TIME,
      'inv_token' => $token,
    ])->execute();
  }
  catch (PDOException $e) {
    watchdog('c4m_og_invite_visitors', $e->getMessage(), NULL, WATCHDOG_ERROR);

    return FALSE;
  }

  return [
    'token' => $token,
    'invId' => $invId,
  ];
}

/**
 * Show the pending invitations by email.
 *
 * @param string $group_id
 *   Group id.
 *
 * @return string
 *   Output.
 */
function c4m_og_invite_visitors_pending_invitations($group_id) {
  $output = theme('html_tag', [
    'element' => [
      '#tag' => 'h2',
      '#value' => 'E-mail addresses',
    ],
  ]);

  $invitations = db_select('c4m_og_invite_visitors', 'inv')
    ->fields('inv', [
      'inv_id',
      'inv_email',
      'inv_inviter_id',
      'inv_created',
    ])
    ->condition('inv_group_id', $group_id)
    ->condition('inv_expired', 0)
    ->execute()
    ->fetchAllAssoc('inv_id');

  if ($invitations) {
    $header = [
      'Email',
      'Invited by',
      'Invited on',
      'Actions',
    ];
    $rows = [];
    foreach ($invitations as $inv_id => $invitation) {
      $user = entity_metadata_wrapper('user', $invitation->inv_inviter_id);
      $rows[] = [
        $invitation->inv_email,
        $user->name->value(),
        format_date($invitation->inv_created, 'short'),
        l(t('delete'), 'group/node/' . $group_id . '/admin/people/invitations/email/delete/' . $invitation->inv_id),
      ];
    }

    $output .= theme('table', ['header' => $header, 'rows' => $rows]);
  }
  else {
    $output .= theme('html_tag', [
      'element' => [
        '#tag' => 'p',
        '#value' => 'No invitations.',
      ],
    ]);
  }

  return $output;
}

/**
 * Delete invitation.
 *
 * @param string $group_id
 *   The group id.
 * @param string $inv_id
 *   The invitation id.
 */
function c4m_og_invite_visitors_delete_invitation($group_id, $inv_id) {
  return db_delete('c4m_og_invite_visitors')
    ->condition('inv_group_id', $group_id)
    ->condition('inv_id', $inv_id)
    ->execute();
}
