<?php

/**
 * @file
 * Invite new members to a group or project.
 */

/**
 * Implements hook_menu().
 *
 * Defines a path for the page/form used to invite visitors into a group.
 */
function c4m_og_invite_visitors_menu() {
  $items = array();
  $items['group/%/%/admin/members/invite'] = array(
    'page callback' => 'drupal_get_form',
    'title' => 'Invite visitors',
    'page arguments' => array('_c4m_og_invite_visitors_new_users_form', 1, 2),
    'type' => MENU_LOCAL_TASK,
    'weight' => 4,
    'access callback' => 'c4m_og_invite_visitors_user_access',
    'access arguments' => array('invite visitors', 1, 2),
  );

  return $items;
}

/**
 * Implements hook_og_ui_get_group_admin().
 *
 * Adds a menu item (Invite visitors) to the group administration page. Links to
 * the invite visitors form.
 */
function c4m_og_invite_visitors_og_ui_get_group_admin($group_type, $gid) {
  $items = array();
  if (og_user_access($group_type, $gid, 'invite visitors')) {
    $items['c4m_og_invite_visitors'] = array(
      'title' => t('Invite visitors'),
      'description' => t('Create new users and add them as group members.'),
      'href' => 'admin/members/invite',
    );
  }

  return $items;
}

/**
 * Invite access. Checks if the user is allowed to invite visitors to the group.
 *
 * Checks by user role and og_role against group visibility (Public/Private) and
 * Membership requests setting (Open/Moderated).
 */
function c4m_og_invite_visitors_user_access($perm, $group_type, $gid) {
  global $user;

  $group = entity_load_single($group_type, $gid);
  if (!$group || !og_is_group($group_type, $group)) {
    return FALSE;
  }

  // SAs, GOs and GAs can invite new members.
  if (_c4m_features_og_members_is_power_user($group)) {
    return TRUE;
  }

  // Get request type (open/moderated).
  $membership_request_value = c4m_og_get_group_membership_request($group);
  // Get access type (public/private).
  $access_type = c4m_og_get_access_type($group);

  // For private or moderated groups, return false. Else check for member.
  if ($access_type['type'] == 'private' || $membership_request_value == 'moderated') {
    return FALSE;
  }

  return og_is_member($group->type, $group->nid, 'user', $user);
}

/**
 * Implements hook_og_permission().
 *
 * Adds a group permissions to invite visitors to a group.
 */
function c4m_og_invite_visitors_og_permission() {
  $items = array();
  $items['invite visitors'] = array(
    'title' => t('Invite visitors'),
    'description' => t('Users may invite visitors to the group.'),
    'default role' => array(OG_ADMINISTRATOR_ROLE),
  );

  return $items;
}

/**
 * Main OG Invite visitors form.
 *
 * Defines the form structure for inviting visitors to join a group.
 */
function _c4m_og_invite_visitors_new_users_form($form, &$form_state, $group_type, $gid) {
  og_set_breadcrumb($group_type, $gid, array(l(t('Group'), "$group_type/$gid/group")));
  $group = entity_load_single($group_type, $gid);
  $label = entity_label($group_type, $group);

  $form['group_type'] = array(
    '#type' => 'value',
    '#value' => $group_type,
  );

  $form['gid'] = array(
    '#type' => 'value',
    '#value' => $gid,
  );

  $form['c4m_og_invite_visitors'] = array(
    '#type' => 'fieldset',
    '#title' => t('Invite new users to %group', array('%group' => $label)),
  );
  $form['c4m_og_invite_visitors']['invitee'] = array(
    '#type' => 'textarea',
    '#title' => t('User email(s)'),
    '#description' => t("Use commas or new lines to split email addresses. The new users will be created and invited as members of this group. A one time login link will be sent to the invitees\' email."),
    '#required' => TRUE,
  );
  $form['c4m_og_invite_visitors']['personal_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#description' => t('Add a personal subject to the invitation email.'),
  );
  $form['c4m_og_invite_visitors']['personal_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Add a message (optional)'),
    '#description' => t('Add a personal message to the invitation email.'),
  );

  // Get the name of the group-audience type field = The name of the field
  // holding the group ID the OG membership is associated with.
  $field_names = og_get_group_audience_fields('user', 'user', $group_type);
  $field_name = key($field_names);

  // There is only a single field name, so just pass it as a value.
  $form['c4m_og_invite_visitors']['field_name'] = array(
    '#type' => 'value',
    '#value' => $field_name,
  );

  $form_state['field_name'] = $field_name;

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Invite user(s)'),
  );

  return $form;
}

/**
 * Validation handler for _c4m_og_invite_visitors_new_users_form.
 *
 * Check the list of emails to invite and filter out invalid entries. File an
 * error for the filtered addresses (if any).
 */
function _c4m_og_invite_visitors_new_users_form_validate($form, &$form_state) {
  // Split the list of email addresses by comma, newline or white space.
  $invitee_emails = preg_split('/\s*[,\n]\s*/', $form_state['values']['invitee']);
  $form_state['invitee_emails'] = array();

  foreach (array_filter($invitee_emails) as $invitee_email) {
    if (!valid_email_address($invitee_email)) {
      form_set_error('invitee', t('Invalid email @email', array('@email' => $invitee_email)));
    }
    else {
      $form_state['invitee_emails'][] = $invitee_email;
    }
  }
}

/**
 * Submit handler for _c4m_og_invite_visitors_new_users_form.
 *
 * Creates a new user for each invited visitor. Creates an OG membership and
 * adds the user to the group.
 */
function _c4m_og_invite_visitors_new_users_form_submit($form, &$form_state) {
  global $user;
  $group_type = $form_state['values']['group_type'];
  $gid = $form_state['values']['gid'];
  $invitee_emails = $form_state['invitee_emails'];
  $form_fields = array(
    'subject' => $form_state['values']['personal_subject'],
    'body' => $form_state['values']['personal_message'],
  );
  $entity_type = 'user';

  foreach ($invitee_emails as $invitee_email) {
    // Try to load the user by email and see if exists.
    if ($account = user_load_by_mail($invitee_email)) {
      // Check if user is already assigned to the group.
      // Any "state" (active, pending,... counts as existing).
      if ($og_membership = og_get_membership($group_type, $gid, $entity_type, $account->uid)) {
        // Load OG membership.
        $message = t('%user is already a member of this group.', array('%user' => format_username($account)));
      }
      else {
        // Save invitation to MySQL.
        $invitation = c4m_og_invite_visitors_store_invitation($user->uid, $gid, $invitee_email);
        $message = t('An email notification was sent to %address.', array('%address' => $invitee_email));
        $field_name = key(og_get_group_audience_fields());

        // Invoke the invite_user functionality.
        og_invite_invite($group_type, $gid, $field_name, $account->uid);
      }
    }
    else {
      // Save invitation to MySQL.
      $invitation = c4m_og_invite_visitors_store_invitation($user->uid, $gid, $invitee_email);
      $message = t('An email notification was sent to %address.', array('%address' => $invitee_email));

      // Send the e-mail.
      drupal_mail('c4m_og_invite_visitors', 'invite_group_member', $invitee_email, NULL, array(
        'form_fields' => $form_fields,
      ), variable_get('site_mail', NULL));
    }

    // Print the message for each user.
    drupal_set_message($message);
  }
}

/**
 * Implements hook_mail().
 *
 * Alters the email sent to visitors when they are invited to join a group. The
 * email subject and body are loaded from template files with the same name as
 * the email identification $key.
 */
function c4m_og_invite_visitors_mail($key, &$message, $params) {
  $language = $message['language'];
  $variables = array(
    'message' => $message,
    'form_fields' => $params['form_fields'],
  );
  $message['subject'] .= _c4m_og_invite_visitors_mail_text($key . '_subject', $language, $variables);
  $message['body'][] = _c4m_og_invite_visitors_mail_text($key . '_body', $language, $variables);
}

/**
 * Returns a mail string for a variable name.
 *
 * Used by c4m_og_invite_visitors_mail() and the settings forms to retrieve
 * strings.
 */
function _c4m_og_invite_visitors_mail_text($key, $language = NULL, $variables = array(), $replace = TRUE) {
  global $language;

  // Try to load the text first from variable.
  $text = variable_get($key, FALSE);

  if ($replace) {
    // We do not sanitize the token replacement since we do not output the
    // result to the browser.
    return token_replace($text, $variables, array(
      'language' => $language,
      'callback' => 'c4m_og_invite_visitors_mail_tokens',
      'sanitize' => FALSE,
      'clear' => TRUE,
    )
    );
  }

  return $text;
}

/**
 * Token callback to add unsafe tokens for user mails.
 *
 * This function is used by the token_replace() call at the end of
 * _c4m_og_invite_visitors_mail_text() to set up some additional tokens that can
 * be used in email messages generated by c4m_og_invite_visitors_mail().
 *
 * @param array $replacements
 *   An associative array variable containing mappings from token names to
 *   values (for use with strtr()).
 * @param array $data
 *   An associative array of token replacement values. If the 'user' element
 *   exists, it must contain a user account object with the following
 *   properties:
 *   - login: The UNIX timestamp of the user's last login.
 *   - pass: The hashed account login password.
 * @param array $options
 *   Unused parameter required by the token_replace() function.
 */
function c4m_og_invite_visitors_mail_tokens(&$replacements, $data, $options) {
  global $user, $base_url;

  $group = c4m_og_current_group();
  $url_options = array(
    'absolute' => TRUE,
    'purl' => array(
      'provider' => 'og_purl|node',
      'id' => $group->nid,
    ),
  );

  $replacements['[user:full_name]'] = c4m_user_name($user);
  $replacements['[user:public-profile-url]'] = $base_url . '/users/' . c4m_og_human_to_machine_readable($replacements['[user:full_name]']);
  $replacements['[group:node_type]'] = $group->type;
  $replacements['[group:node_title]'] = $group->title;
  // TODO c4m_user_registrationpassword_confirmation_url($data['user']);.
  $replacements['[group:accept_invite_url]'] = '';
  $replacements['[group:dashboard_url]'] = url('<front>', $url_options);
  $replacements['[personal:subject]'] = $data['form_fields']['subject'];
  $replacements['[personal:body]'] = $data['form_fields']['body'];
  $replacements['[site:name]'] = variable_get('site_name', 'Capacity 4 More');
  return;
}

/**
 * Implements hook_drupal_goto_alter().
 *
 * When new users accepts an invitation, redirect them to edit their profile so
 * they can enter their name and choose a password.
 */
function c4m_og_invite_visitors_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  global $user;

  if ($path != 'user/' . $user->uid || !empty($user->c4m_first_name) || !empty($user->c4m_last_name)) {
    return;
  }

  $path .= '/edit';
}

/**
 * Creates a token hash to safely store in MySQL.
 *
 * The token will be saved with the invitation and used to verify the identity
 * of the accepting user.
 */
function c4m_og_invite_visitors_generate_invitation_hash($email, $created) {
  // Generate a random token.
  $token = '?e=' . $email . '&rk=' . drupal_random_key() . '&ts=' . preg_replace('/[^0-9]/', '', $created);
  return array(
    'hash' => password_hash($token, PASSWORD_DEFAULT),
    'token' => $token,
  );
}

/**
 * Store invitation entry in the DB table c4m_og_invite_visitors.
 */
function c4m_og_invite_visitors_store_invitation($inviter_id, $group_id, $email) {
  // Format date for MySQL datetime field.
  $date = new DateTime();
  $created = $date->date;

  $hash = c4m_og_invite_visitors_generate_invitation_hash($email, $created);

  try {
    $invId = db_insert('c4m_og_invite_visitors')
      ->fields(
        array(
          'inv_inviter_id' => $inviter_id,
          'inv_group_id' => $group_id,
          'inv_email' => $email,
          'inv_created' => $created,
          'inv_token' => $hash['hash'],
        )

      )
      ->execute();
  } catch (PDOException $e) {
    echo 'Error: ', $e->getMessage(), "\n";
  }

  return [$hash['token'], $invId];
}
