<?php
/**
 * @file
 * Code for the Articles Overview feature.
 */

include_once 'c4m_features_overview_articles.features.inc';

/**
 * Implements hook_c4m_search_page_info().
 */
function c4m_features_overview_articles_c4m_search_page_info() {
  return array(
    'c4m_features_overview_articles' => array(
      'name' => t('Articles'),
      'description' => t('Search articles.'),
      'machine_name' => 'c4m_features_overview_articles',
      'path' => 'articles',
      'weight' => 1,
      'default' => FALSE,
      'purl' => FALSE,
      'group' => t('Search in all site content'),
    ),
  );
}
