<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_ds_fields_info().
 */
function c4m_field_og_ds_fields_info($entity_type) {
  $fields = array();

  $path = drupal_get_path('module', 'c4m_field_og');

  // A field to indicate the group a group node belongs to
  $fields['node']['c4m_field_og_group'] = array(
    'title'      => t('Group'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit'   => array('*|*'),
    'file'       => $path . '/includes/c4m_field_og.theme.node.inc',
    'function'   => 'theme_c4m_field_og_group',
    'properties' => array(
      'formatters' => array(
        'default' => t('Default'),
      ),
    ),
  );

  return $fields;
}

/**
 * Implements hook_field_access().
 */
function c4m_field_og_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] != 'c4m_og_status') {
    // Not a status field.
    return;
  }

  if (user_access('administer site', $account)) {
    // This is site administrator.
    return TRUE;
  }

  if (!$account->uid) {
    // This is an anonymous user.
    return FALSE;
  }

  if (empty($entity->nid)) {
    // Entity isn't saved yet.
    return FALSE;
  }

  // Get current Status field value.
  $wrapper = entity_metadata_wrapper($entity_type, $entity);
  $value = $wrapper->c4m_og_status->value();

  if ($account->uid == $entity->uid) {
    // Group owner.

    $allowed_values = array(
      'requested',
      'draft',
      'published',
    );
    if ($op == 'view' || in_array($value, $allowed_values)) {
      return TRUE;
    }
  }

  if (og_user_access($entity_type, $entity->nid, 'administer group', $account)) {
    // Group administrator.

    $allowed_values = array(
      'draft',
      'published',
    );
    if ($op == 'view' || in_array($value, $allowed_values)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Implements hook_form_alter().
 */
function c4m_field_og_form_alter(&$form, &$form_state, $form_id) {
  if (!isset($form_state['field']['c4m_og_status'])) {
    return;
  }
  global $user;

  $account = user_load($user->uid);
  $entity = $form_state['node'];
  $wrapper = entity_metadata_wrapper('node', $entity);
  $value = $wrapper->c4m_og_status->value();

  if ($account->uid == $entity->uid) {
    // Group owner.

    $allowed_values = array(
      'requested' => array(
        'requested' =>'Requested',
        'deleted' => 'Deleted'
      ),
      'draft' => array(
        'draft' => 'Draft',
        'deleted' => 'Deleted',
        'published' => 'Published',
      ),
      'published' => array(
        'published' => 'Published',
        'archived' => 'Archived',
        'deleted' => 'Deleted',
      ),
    );
    if (array_key_exists($value, $allowed_values)) {
      $form['c4m_og_status']['und']['#options'] = $allowed_values[$value];
    }
    return;
  }

  if (og_user_access('node', $entity->nid, 'administer group', $account)) {
    // Group administrator.

    $allowed_values = array(
      'draft' => array(
        'draft' => 'Draft',
        'published' => 'Published',
        'deleted' => 'Deleted',
      ),
      'published' => array(
        'published' => 'Published',
        'deleted' => 'Deleted',
      ),
    );
    if (array_key_exists($value, $allowed_values)) {
      $form['c4m_og_status']['und']['#options'] = $allowed_values[$value];
    }
  }
}
