<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_field_widget_info().
 */
function c4m_vocab_language_field_widget_info() {
  $widgets['c4m_taxonomy_reference'] = array(
    'label' => t('C4M Taxonomy'),
    'description' => t('Taxonomy widget using Angular.'),
    'field types' => array('entityreference', 'taxonomy_term_reference'),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_CUSTOM,
      'default value' => FIELD_BEHAVIOR_NONE,
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 */
function c4m_vocab_language_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $entity_type = $instance['entity_type'];
  $entity = isset($element['#entity']) ? $element['#entity'] : NULL;

  if (!$entity) {
    return;
  }

  // Load Angular.
  $bower_path = libraries_get_path('bower_components');

  // AngularJs.
  drupal_add_js($bower_path . '/angular/angular.min.js');

  // Upload file library.
  drupal_add_js($bower_path . '/danialfarid-angular-file-upload/dist/angular-file-upload-shim.min.js');
  drupal_add_js($bower_path . '/danialfarid-angular-file-upload/dist/angular-file-upload.min.js');

  // Angular-animate.
  drupal_add_js($bower_path . '/angular-animate/angular-animate.min.js');

  // JSON pretty print library.
  drupal_add_css($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.css');
  drupal_add_js($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.js');

  // CKEditor library.
  drupal_add_css($bower_path . '/ng-ckeditor/ng-ckeditor.css');
  drupal_add_js($bower_path . '/ng-ckeditor/libs/ckeditor/ckeditor.js');
  drupal_add_js($bower_path . '/ng-ckeditor/ng-ckeditor.js');

  // Select UI
  drupal_add_css($bower_path . '/select2/select2.css');
  drupal_add_css($bower_path . '/select2/select2-bootstrap.css');
  drupal_add_js($bower_path . '/select2/select2.js');
  drupal_add_js($bower_path . '/angular-ui-select2/src/select2.js');

  // Bootstrap DatePicker.
  drupal_add_js($bower_path . '/angular-bootstrap/ui-bootstrap.min.js');
  drupal_add_js($bower_path . '/angular-bootstrap/ui-bootstrap-tpls.min.js');

  // Font-awesome library.
  drupal_add_css($bower_path . '/components-font-awesome/css/font-awesome.min.css');

  // Filesize library.
  drupal_add_js($bower_path . '/filesize/lib/filesize.min.js');

  // Load our custom app.
  $app_path = $bower_path . '/c4m-app/dist';
  drupal_add_js($app_path . '/c4m-app.js');
  drupal_add_css($app_path . '/css/c4m-app.css');

  dpm($field);
  $vocabulary_name = $field['settings']['allowed_values'][0]['vocabulary'];
  $vocabulary = taxonomy_vocabulary_machine_name_load($field['settings']['allowed_values'][0]['vocabulary']);
  $terms = taxonomy_get_tree($vocabulary->vid);
  $options = array();
  foreach($terms as $term) {
    $options[$term->tid]['label'] = $term->name;
    $options[$term->tid]['id'] = $term->tid;
  }


  $settings['c4m'] = array(
    'data' => array(
      'vocabularies' => array()
    )
  );
  $settings['c4m']['data']['vocabularies'][$vocabulary_name] = $options;

  drupal_add_js($settings, 'setting');

  // Add the directive.
  $directive =
    '<div class="form-group btn-group ' . $vocabulary_name . '">
      <div class="checkboxes-wrapper">
        <div>
          <button type="button" ng-click="togglePopover(\'' . $vocabulary_name . '\', $event)" class="btn btn-primary fa fa-plus">&nbsp;' . t('Select @name', array('@name' => $vocabulary->name)) . '</button>
        </div>
        <!-- Hidden language checkboxes.-->
        <div class="popover right hidden-checkboxes" ng-show="popups.' . $vocabulary_name . ' == 1">
          <div class="arrow"></div>
          <div class="popover-content">
            <form action="#" class="search">
              <input ng-model="searchTerm" ng-change="updateSearch()" class="form-control" type="text" placeholder="Search"/>
            </form>
            <div class="checkbox" ng-repeat="item in data.' . $vocabulary_name . '">
              <label>
                <input type="checkbox" ng-name="type" title="{{item.label}}" ng-model="model[item.id]" ng-change="updateSelectedTerms(item.id)"> {{item.label}}
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>';

  $form['directive-' . $vocabulary_name] = array(
    '#markup' => $directive,
  );
  $form['#attributes']['ng-app'] = 'c4mApp';
  $form['#attributes']['ng-controller'] = 'DrupalFormCtrl';

  // Add the checkboxes hidden.
  $instance['widget']['type'] = 'options_buttons';
  $instance['widget']['active'] = 1;
  unset($element['#weight']);
  $element = options_field_widget_form($form, $form_state, $field, $instance, $langcode, $items, $delta, $element);
//  $element['#prefix'] = '<div class="default-widget hidden-checkboxes">';
//  $element['#suffix'] = '</div>';

  return $element;
}

function c4m_vocab_language_node_presave($node) {
//  dpm($node);
}
