<?php

/**
 * @file
 * Code for the social feature.
 */

/**
 * Implements hook_c4m_content_actions_info().
 */
function c4m_features_social_c4m_content_actions_info() {
  return array(
    'social_share' => array(
      'context'   => array('global', 'group'),
      'callback'  => 'c4m_features_social_actions_share',
      'weight'    => '10',
    ),
  );
}

/**
 * Callback to show the enabled social media.
 *
 * @param object $node
 *    The node object.
 *
 * @return string
 *    Rendered output of the share social media.
 */
function c4m_features_social_actions_share($node) {
  // Get the social settings.
  $social = variable_get('c4m_social_share', array());
  $social = array_keys($social);

  // Print is always required and is added separately as is not supported by
  // the EC widget.
  unset($social['c4m_print']);

  $social = array_filter($social, 'c4m_features_social_share_icons_filter');

  $settings = array(
    'service' => 'sbkm',
    'popup' => FALSE,
    'icon' => TRUE,
    'to' => $social,
    'counter' => array('atleast' => 1),
    'selection' => FALSE,
  );
  $data = json_encode($settings);
  $items = '<script type="application/json">' . $data . '</script>';
  $items .= '
    <div id="c4m-print">
      <div class="share_list share_style_link share_style_icon_24">
        <a href="#" title="Print" onclick="window.print();return false;"></a>
      </div>
    </div>';

  $output = '<div class="social-actions-share"><h3>' . t('Share this page') . '</h3>' . $items . '</div>';
  drupal_add_js('//europa.eu/webtools/load.js', 'external');

  return $output;
}

/**
 * Callback for array filter.
 *
 * Allows share icons depending on the group membership type.
 *
 * @param string $icon
 *   The key identificator of the share icon.
 *
 * @return bool
 *   If the icon is allowed in the group context or not.
 */
function c4m_features_social_share_icons_filter($icon) {
  $group = c4m_og_current_group();

  // If group is FALSE means we are in a normal page and we display all links.
  if ($group === FALSE) {
    return TRUE;
  }

  $access_type = c4m_og_get_access_type($group);
  $access_type = $access_type['type'];

  switch ($access_type) {
    case 'public':
      // All share icons are allowed.
      return TRUE;

    case 'restricted':
      return in_array($icon, array('e-mail', 'yammer'));

    case 'private':
      return in_array($icon, array('e-mail'));
  }
}
