<?php
/**
 * @file
 * This file specifies the command to be executed on install and uninstall.
 */

/**
 * Implements hook_install().
 */
function c4m_comment_delete_install() {
  db_query('UPDATE {system} SET weight = 1 WHERE name = "c4m_comment_delete"');

  variable_set('c4m_comment_delete_replies', 2);
}

/**
 * Implements hook_uninstall().
 */
function c4m_comment_delete_uninstall() {
  variable_del('c4m_comment_delete_replies');
  variable_del('c4m_comment_delete_clock');
}
