<?php
/**
 * @file
 * Code for the C4M Display Suite feature.
 */

include_once 'c4m_ds.features.inc';

/**
 * Define fields.
 *
 * These fields are not overridden through the interface.
 * If you want those, look at hook_ds_custom_fields_info().
 *
 * @param string $entity_type
 *   The name of the entity which we are requesting fields for, e.g. 'node'.
 *
 * @return array
 *   A collection of fields which keys are the entity type name and values
 *   a collection fields.
 *
 * @see ds_get_fields()
 */
function c4m_ds_ds_fields_info($entity_type) {
  $fields = array();

  $path = drupal_get_path('module', 'c4m_ds');

  $fields['c4m_ds_node_meta'] = array(
    'title' => t('Node meta data'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('*|*'),
    'file' => $path . '/includes/c4m_ds.theme.inc',
    'function' => 'theme_c4m_ds_node_meta',
    'properties' => array(
      'formatters' => array(
        'default' => t('Default'),
        'minimal' => t('Minimal (no image, no prefix'),
      ),
    ),
  );

  return array('node' => $fields);
}