<?php
/**
 * @file
 * Code for the C4M Display Suite feature.
 */

// Link types that support purl.
define ('C4M_DS_LINK_TYPE_PURL_AUTO', 'purl_auto');
define ('C4M_DS_LINK_TYPE_PURL_DISABLED', 'purl_disabled');
define ('C4M_DS_LINK_TYPE_PURL_OG_DASHBOARD', 'purl_og_dashboard');


include_once 'c4m_ds.features.inc';

// DS specific files.
include_once 'c4m_ds.ds_field_formatter.inc';
include_once 'c4m_ds.ds_fields_info.inc';
include_once 'c4m_ds.ds_layout_info.inc';
include_once 'c4m_ds.ds_render_field.inc';
include_once 'c4m_ds.ds_view_modes_info.inc';

// Fallback to avoid missing bootstrap functionality.
require_once(drupal_get_path('theme', 'bootstrap') . '/includes/process.inc');


/**
 * Implements hook_theme().
 */
function c4m_ds_theme() {
  return array(
    'c4m_ds_formatter_link_and_size' => array(
      'variables' => array('file' => NULL, 'icon_directory' => NULL, 'text' => NULL),
      'file'      => 'includes/c4m_ds.theme.file.inc',
    ),
  );
}

/**
 *  Implements hook_ds_pre_render_alter().
 */
function c4m_ds_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {
  // DS and field_group together sometimes break weight.
  // We can use field key in region as weight as fields are ordered now.
  foreach ($layout_render_array as $region_name => $content) {
    foreach ($content as $key => $field) {
      $layout_render_array[$region_name][$key]['#weight'] = $key;
    }
  }
}
