<?php

/**
 * @file
 * Administration functionality.
 */

/**
 * Implements hook_menu().
 */
function c4m_admin_menu() {
  $items = array();

  $items['admin/config/c4m'] = array(
    'title' => 'capacity4more',
    'description' => 'capacity4more admin configuration.',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'position' => 'right',
  );

  $items['admin/config/c4m/disclaimer'] = array(
    'title' => 'Disclaimer text settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('c4m_admin_manage_disclaimer_form'),
    'access arguments' => array('administer disclaimer settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'c4m_admin.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function c4m_admin_permission() {
  $perms['administer disclaimer settings'] = array(
    'title' => t('Administer disclaimer settings'),
    'description' => t('Allows the user to modify the disclaimer text.'),
  );

  return $perms;
}
