<?php

/**
 * @file
 * Code for the C4M notifications triggers.
 */

/**
 * Include handlers.
 */
module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.helper');
module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.logger');
module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.dispatch');
module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.notify');
module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.notify_subscribe');

/**
 * Implements hook_og_membership_insert().
 */
function c4m_user_notifications_og_membership_insert($og_membership) {
  _c4m_user_notifications_og_membership_insert($og_membership);
}

/**
 * Implements hook_og_membership_update().
 */
function c4m_user_notifications_og_membership_update($og_membership) {
  _c4m_user_notifications_dispatch_og_membership_update($og_membership);
}

/**
 * Implements hook_og_role_grant().
 */
function c4m_user_notifications_og_role_grant($entity_type, $gid, $uid, $rid) {
  _c4m_user_notifications_og_role_grant($gid, $uid, $rid);
}

/**
 * Implements hook_og_role_revoke().
 */
function c4m_user_notifications_og_role_revoke($entity_type, $gid, $uid, $rid) {
  _c4m_user_notifications_og_role_revoke($gid, $uid, $rid);
}

/**
 * Implements hook_node_insert().
 */
function c4m_user_notifications_node_insert($node) {
  _c4m_user_notifications_node_insert($node);
}

/**
 * Implements hook_node_update().
 */
function c4m_user_notifications_node_update($node) {
  _c4m_user_notifications_node_update($node);
}

/**
 * Implements hook_comment_insert().
 */
function c4m_user_notifications_comment_insert($comment) {
  _c4m_user_notifications_comment_insert($comment);
}

/**
 * Implements hook_flag_flag().
 */
function c4m_user_notifications_flag_flag($flag, $entity_id, $account, $flagging) {
  _c4m_user_notifications_flag_flag($flag, $entity_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_notifications_form_og_ui_add_users_alter(array &$form, array &$form_state) {
  module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.form_alters');

  _c4m_user_notifications_form_og_ui_add_users_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_notifications_form_c4m_og_reject_membership_request_alter(array &$form, array &$form_state) {
  module_load_include('inc', 'c4m_user_notifications', 'includes/c4m_user_notifications.form_alters');

  _c4m_user_notifications_form_c4m_og_reject_membership_request_alter($form, $form_state);
}

/**
 * Implements hook_message_subscribe_get_subscribers().
 */
function c4m_user_notifications_message_subscribe_get_subscribers($message, $subscribe_options, $context) {
  return _c4m_user_notifications_message_subscribe_get_subscribers($message, $context);
}
