<?php
/**
 * @file
 * Code for the Group content type feature.
 */

include_once 'c4m_content_group.features.inc';

/**
 * Implements hook_c4m_og_vocab_info_groups().
 *
 * @return array
 */
function c4m_content_group_c4m_og_vocab_info_groups() {
  return array(
    'group' => array(
      'c4m_vocab_category',
      'c4m_vocab_tag',
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function c4m_content_group_ctools_plugin_directory($module, $plugin_type) {
  if ($module == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_block_info().
 */
function c4m_content_group_block_info() {
  $blocks['header_name_banner'] = array(
    'info' => t('Group header'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function c4m_content_group_block_view($delta = '') {
  module_load_include('inc', 'c4m_content_group', 'c4m_content_group.block');
  $callback = '_c4m_content_group_block_' . $delta;
  if (!function_exists($callback)) {
    return NULL;
  }

  return $callback();
}

/**
 * Preprocess for blocks of this module.
 *
 * @param $variables
 */
function c4m_content_group_preprocess_block(&$variables) {
  module_load_include('inc', 'c4m_content_group', 'c4m_content_group.block');
  if ($variables['block']->module == 'c4m_content_group' &&
      !empty($variables['block']->delta)) {
    $callback = '_c4m_content_group_preprocess_' . $variables['block']->delta;
    if (function_exists($callback)) {
      $callback($variables);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_content_group_form_group_node_form_alter(&$form, &$form_state, $form_id) {
  // Hide fields for authenticated users.
  global $user;
  if (!in_array('anonymous user', $user->roles)
    && !in_array('administrator', $user->roles)
    && strpos($form['#action'], 'add')) {
    $form['c4m_related_group']['#access'] = FALSE;
    $form['c4m_related_projects']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;

    // After a form is submitted, run a redirect function.
    $form['#submit'][] = 'c4m_content_group_submit_redirect';
  }
}

/**
 * Submit form function.
 *
 * @param $form
 * @param $form_state
 */
function c4m_content_group_submit_redirect(&$form, &$form_state) {
  // Set a successful message for a user.
  drupal_set_message(t('The group you requested is pending review by one of the administrators. You will receive an email with the outcome of that review.'));
  // Redirect a user to homepage.
  drupal_goto('');
}
