<?php

/**
 * @file
 * Code for the Group content type feature.
 */

define('C4M_CONTENT_GROUP_ACCESS_REALM', 'c4m_group_status');
define('C4M_CONTENT_GROUP_ACCESS_REALM_ALL', 'c4m_group_status_admin');
define('C4M_CONTENT_GROUP_STATUS_VIEW_REQUESTED', 0);
define('C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT', 1);
define('C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED', 2);
define('C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED', 3);
define('C4M_CONTENT_GROUP_STATUS_VIEW_REJECTED', 4);
define('C4M_CONTENT_GROUP_STATUS_VIEW_DELETED', 5);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_REQUESTED', 6);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT', 7);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED', 8);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED', 9);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_REJECTED', 10);
define('C4M_CONTENT_GROUP_STATUS_UPDATE_DELETED', 11);

include_once 'c4m_content_group.features.inc';

/**
 * Implements hook_c4m_og_vocab_info_groups().
 */
function c4m_content_c4m_og_vocab_info_groups() {
  return array(
    'group' => array(
      'c4m_vocab_category',
      'c4m_vocab_tag',
    ),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function c4m_content_group_ctools_plugin_directory($module, $plugin_type) {
  if ($module == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_block_info().
 */
function c4m_content_group_block_info() {
  $blocks['header_name_banner'] = array(
    'info' => t('Group header'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  $blocks['c4m_block_create_group'] = array(
    'info' => t('Group: Create group'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_module_implements_alter().
 *
 * Make sure that:
 * - c4m_content_group_node_insert().
 * - c4m_content_group_node_update().
 * Are called last.
 */
function c4m_content_group_module_implements_alter(&$implementations, $hook) {
  $last_hooks = array('node_insert', 'node_update');

  if (in_array($hook, $last_hooks)) {
    $group = $implementations['c4m_content_group'];
    unset($implementations['c4m_content_group']);
    $implementations['c4m_content_group'] = $group;
  }
}

/**
 * Implements hook_node_insert().
 *
 * Sends notifications (By email) to site administrators to notify
 * about a new group request.
 */
function c4m_content_group_node_insert($node) {
  // Only for OG enabled content type.
  if (!og_is_group_type('node', $node->type)) {
    return;
  }

  // Don't send notifications during migration.
  if (!empty($node->migrate)) {
    return;
  }

  // Get all site administrators.
  $admin_role = user_role_load_by_name('administrator');
  $results = db_select('users_roles', 'r')
            ->fields('r', array('uid'))
            ->condition('rid', $admin_role->rid, '=')
            ->execute()
            ->fetchAll();

  // Send a notification for each site admin.
  if (!empty($results)) {
    foreach ($results as $result) {
      $admin = user_load($result->uid);

      // Send the actual mail.
      $key = 'group_pending_approval_admin';
      c4m_content_group_send_mail($key, $admin, $node);
    }
  }
}

/**
 * Implements hook_node_update().
 *
 * Sends notifications (By email) to the group author,
 * when the group status changes (Rejected/ Approved).
 */
function c4m_content_group_node_update($node) {
  // Only for OG enabled content type.
  if (!og_is_group_type('node', $node->type)) {
    return;
  }

  // Do not send notifications if it's not a group.
  // Don't send notifications during migration.
  if ($node->type != 'group' || !empty($node->migrate)) {
    return;
  }

  // Status now and before update.
  $status_new = isset($node->c4m_og_status)
    ? $node->c4m_og_status[LANGUAGE_NONE][0]['value']
    : NULL;
  $status_original = (isset($node->original->c4m_og_status))
    ? $node->original->c4m_og_status[LANGUAGE_NONE][0]['value']
    : NULL;

  // Don't do anything if status did NOT change.
  if ($status_original === $status_new) {
    return;
  }

  $key = NULL;
  switch ($status_new) {
    case 'rejected':
      $key = 'group_rejected_user';
      break;

    case 'draft':
    case 'published':
      $key = 'group_approved_user';
      break;
  }

  // Send mail only if there's a key.
  if ($key) {
    $account = user_load($node->uid);
    c4m_content_group_send_mail($key, $account, $node);
  }
}

/**
 * Helper to send out an email.
 *
 * @param string $key
 *   The message type key.
 * @param object $account
 *   The user where to send the mail to.
 * @param object $group
 *   The group to send the mail for.
 *
 * @return array
 *   The $message array structure containing all details of the
 *   message. If already sent ($send = TRUE), then the 'result' element
 *   will contain the success indicator of the e-mail, failure being already
 *   written to the watchdog. (Success means nothing more than the message being
 *   accepted at php-level, which still doesn't guarantee it to be delivered.)
 */
function c4m_content_group_send_mail($key, $account, $group) {
  $language = user_preferred_language($account, language_default());

  $module = 'c4m_content_group';
  $params = array('group' => $group);

  $to = $account->mail;
  $from = variable_get('site_mail', ini_get('sendmail_from'));

  return drupal_mail($module, $key, $to, $language, $params, $from);
}

/**
 * Implements hook_mail().
 *
 * Defines the Subject and Body of the message depending on the "key".
 */
function c4m_content_group_mail($key, &$message, $variables) {
  module_load_include('inc', 'c4m_content_group', 'c4m_content_group.mail');

  $language = isset($message['language'])
    ? $message['language']
    : NULL;

  $message['subject'] .= _c4m_content_group_mail_text(
    $key . '_subject',
    $language,
    $variables
  );
  $message['body'][] = _c4m_content_group_mail_text(
    $key . '_body',
    $language,
    $variables
  );
}

/**
 * Token callback to add unsafe tokens for user mails.
 *
 * This function is used by the token_replace() call at the end of
 * _user_mail_text() to set up some additional tokens that can be
 * used in email messages generated by user_mail().
 *
 * @param array $replacements
 *   An associative array variable containing mappings from token names to
 *   values (for use with strtr()).
 * @param array $data
 *   An associative array of token replacement values. If the 'group' element
 *   exists, it must contain a group node object.
 * @param mixed $options
 *   Unused parameter required by the token_replace() function.
 */
function c4m_content_group_mail_tokens(array &$replacements, array $data, $options) {
  if (isset($data['group'])) {
    $group = $data['group'];
    $owner = user_load($group->uid);

    $url_options = array(
      'absolute' => TRUE,
      'purl' => array(
        'provider' => 'og_purl|node',
        'id' => $group->nid,
      ),
    );

    $replacements['[group:dashboard_url]'] = url('<front>', $url_options);
    $replacements['[group:owner]'] = $owner->name;
    $replacements['[group:title]'] = $group->title;
  }
}

/**
 * Implements hook_block_view().
 */
function c4m_content_group_block_view($delta = '') {
  module_load_include('inc', 'c4m_content_group', 'c4m_content_group.block');
  $callback = '_c4m_content_group_block_' . $delta;
  if (!function_exists($callback)) {
    return NULL;
  }

  return $callback();
}

/**
 * Preprocess for blocks of this module.
 *
 * @param array $variables
 *   The block variables.
 */
function c4m_content_group_preprocess_block(array &$variables) {
  module_load_include('inc', 'c4m_content_group', 'c4m_content_group.block');
  if ($variables['block']->module == 'c4m_content_group' &&
      !empty($variables['block']->delta)) {
    $callback = '_c4m_content_group_preprocess_' . $variables['block']->delta;
    if (function_exists($callback)) {
      $callback($variables);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide fields for authenticated users and set submit function.
 */
function c4m_content_group_form_group_node_form_alter(&$form, &$form_state) {
  global $user;
  if ($user->uid && !user_access('administer nodes', $user)
    && strpos($form['#action'], 'add')) {
    // Hide fields for authenticated users.
    $form['c4m_related_group']['#access'] = FALSE;
    $form['c4m_related_projects']['#access'] = FALSE;
    $form['revision_information']['#access'] = FALSE;
    // After a form is submitted, run a redirect function.
    $form['actions']['submit']['#submit'][] = 'c4m_content_group_submit_redirect';
  }
}

/**
 * Submit form function.
 *
 * Set redirect and successful message.
 *
 * @param array $form
 *   Form definition.
 * @param array $form_state
 *   The current form state.
 */
function c4m_content_group_submit_redirect(array &$form, array &$form_state) {
  // Set a successful message for a user.
  drupal_set_message(t('The group you requested is pending review by one of the administrators. You will receive an email with the outcome of that review.'));
  // Redirect a user to homepage.
  $form_state['redirect'] = url('', array('absolute' => TRUE));
}

/**
 * Implements hook_og_user_access_alter().
 *
 * Set permissions to users based on OG role and group status.
 */
function c4m_content_group_og_user_access_alter(&$perm, $context) {
  $account = $context['account'];
  $group = $context['group'];

  if ($group->type != 'group' || !$account->uid) {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $group);
  $status = $wrapper->c4m_og_status->value();

  $site_admin = user_access('administer site configuration', $account);
  $group_owner = $account->uid == $group->uid;
  $group_admin = !empty($perm['administer group']) ? $perm['administer group'] : FALSE;

  if ($site_admin || $group_owner || $group_admin) {
    // Site admin/group owner/group admin can invite/approve group members only
    // for Draft and Published groups.
    $allowed_values = array('draft', 'published');
    if (!in_array($status, $allowed_values)) {
      $perm['add user'] = FALSE;
      $perm['approve and deny subscription'] = FALSE;
    }
  }
  else {
    // Not site admin/group owner/group admin can't invite/approve group
    // members.
    $perm['add user'] = FALSE;
    $perm['approve and deny subscription'] = FALSE;
  }

  if (!og_is_member('node', $group->nid, 'user', $account) && $status != 'published') {
    // Users that are not members can ask membership only for published groups.
    $perm['subscribe'] = FALSE;
  }
}

/**
 * Implements hook_node_grants().
 *
 * Set user permissions based on his OG role.
 */
function c4m_content_group_node_grants($account = NULL, $op = 'view') {
  $grants = array();
  if (empty($account)) {
    global $user;
    $account = user_load($user->uid);
  }

  $nodes = og_get_entity_groups();

  $grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_not_member'] = array(
    C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
    C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
  );

  if (!$account->uid || empty($nodes)) {
    // Anonymous user or user that is not a member of any group.
    $anonymous_grant_ids = array(
      C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
      C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
    );

    $grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_anon'] = $op == 'view' ? $anonymous_grant_ids : array();
    return $grants;
  }

  if (user_access('administer site configuration', $account)) {
    // Site admin.
    $grants[C4M_CONTENT_GROUP_ACCESS_REALM_ALL] = array(
      C4M_CONTENT_GROUP_STATUS_VIEW_REQUESTED,
      C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
      C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
      C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
      C4M_CONTENT_GROUP_STATUS_VIEW_REJECTED,
      C4M_CONTENT_GROUP_STATUS_VIEW_DELETED,
      C4M_CONTENT_GROUP_STATUS_UPDATE_REQUESTED,
      C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT,
      C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED,
      C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED,
      C4M_CONTENT_GROUP_STATUS_UPDATE_REJECTED,
      C4M_CONTENT_GROUP_STATUS_UPDATE_DELETED,
    );
    return $grants;
  }

  // Go through all user's group he is owner, admin or member of.
  foreach (og_get_entity_groups() as $group_type => $gids) {
    foreach ($gids as $gid) {
      $node = node_load($gid);

      if ($account->uid == $node->uid) {
        // Group owner.
        $grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $gid] = array(
          C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
          C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
          C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
          C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT,
          C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED,
          C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED,
        );
        continue;
      }
      // Group admin or group member.
      elseif (og_user_access('node', $gid, 'administer group', $account)) {
        // Group admin.
        $grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $gid] = array(
          C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
          C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
          C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
          C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED,
          C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED,
          C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT,
        );
        continue;
      }
      else {
        $member_grant_ids = array(
          C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
          C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
          C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
        );
        $grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $gid] = $op == 'view' ? $member_grant_ids : array();
        continue;
      }
    }
  }
  return $grants;
}

/**
 * Implements hook_node_access_records().
 *
 * Add grants based on group status field.
 */
function c4m_content_group_node_access_records($node) {
  // Only for group nodes.
  if ($node->type != 'group') {
    return;
  }
  $wrapper = entity_metadata_wrapper('node', $node);
  $grants = array();
  $realm_grants = array();

  switch ($wrapper->c4m_og_status->value()) {
    case 'requested':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_REQUESTED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_REQUESTED,
            'grant_update' => 1,
          ),
        ),
      );
      break;

    case 'draft':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $node->nid => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT,
            'grant_update' => 1,
          ),
        ),
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_DRAFT,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_DRAFT,
            'grant_update' => 1,
          ),
        ),
      );
      break;

    case 'published':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $node->nid => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED,
            'grant_update' => 1,
          ),
        ),
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_PUBLISHED,
            'grant_update' => 1,
          ),
        ),
      );

      if (!$wrapper->{OG_ACCESS_FIELD}->value()) {
        // Only for public groups.
        $realm_grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_anon'] = array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
            'grant_update' => 0,
          ),
        );
        $realm_grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_not_member'] = array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_PUBLISHED,
            'grant_update' => 0,
          ),
        );
      }
      break;

    case 'archived':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $node->nid => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED,
            'grant_update' => 1,
          ),
        ),
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_ARCHIVED,
            'grant_update' => 1,
          ),
        ),
      );
      if (!$wrapper->{OG_ACCESS_FIELD}->value()) {
        // Only for public groups.
        $realm_grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_anon'] = array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
            'grant_update' => 0,
          ),
        );
        $realm_grants[C4M_CONTENT_GROUP_ACCESS_REALM . '_not_member'] = array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_ARCHIVED,
            'grant_update' => 0,
          ),
        );
      }
      break;

    case 'rejected':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_REJECTED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_REJECTED,
            'grant_update' => 1,
          ),
        ),
      );
      break;

    case 'deleted':
      $realm_grants = array(
        C4M_CONTENT_GROUP_ACCESS_REALM . '_' . $node->nid => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_DELETED,
            'grant_update' => 0,
          ),
        ),
        C4M_CONTENT_GROUP_ACCESS_REALM_ALL => array(
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_VIEW_DELETED,
            'grant_update' => 0,
          ),
          array(
            'gid' => C4M_CONTENT_GROUP_STATUS_UPDATE_DELETED,
            'grant_update' => 1,
          ),
        ),
      );
      break;
  }

  c4m_content_group_add_grants($realm_grants, $grants);
  return $grants;
}

/**
 * Add new grants to the grunts list.
 *
 * @param array $rows
 *   List of realms and related to it grunt ids and permissions.
 * @param array $grants
 *   List of grants.
 */
function c4m_content_group_add_grants(array $rows, array &$grants) {
  foreach ($rows as $realm => $row) {
    foreach ($row as $grant) {
      $grants[] = array(
        'realm' => $realm,
        'gid' => $grant['gid'],
        'grant_view' => 1,
        'grant_update' => $grant['grant_update'],
        'grant_delete' => 0,
        'priority' => 0,
      );
    }
  }
}

/**
 * Implements hook_admin_paths_alter().
 *
 * @see og_ui_admin_paths()
 * Set the 'node/add/group' path as not admin.
 */
function c4m_content_group_admin_paths_alter(&$paths) {
  $paths['node/*/group'] = FALSE;
}

/**
 * Returns the updated date of the latest updated content item (in a group).
 *
 * @param int $og_id
 *   The Organic group ID to eventually limit the query for.
 *
 * @return int
 *   The updated date of the latest updated content (in a group).
 */
function c4m_content_group_get_latest_activity($og_id = NULL) {
  // Find last updated node.
  $query_nodes = db_select('node', 'n');
  $query_nodes->addField('n', 'changed');
  $query_nodes->condition('n.status', 1);

  if (is_numeric($og_id)) {
    $query_nodes->join('og_membership', 'ogm', 'ogm.etid = n.nid');
    $query_nodes->condition('ogm.gid', (int) $og_id);
    $query_nodes->condition('ogm.entity_type', 'node');
  }

  $latest_updated_node = $query_nodes->execute()->fetchField();

  // Find last updated comment.
  $query_comments = db_select('comment', 'c');
  $query_comments->addField('c', 'changed');
  $query_comments->join('node', 'n', 'n.nid = c.nid');
  $query_comments->condition('c.status', 1);
  $query_comments->condition('n.status', 1);

  if (is_numeric($og_id)) {
    $query_comments->join('og_membership', 'ogm', 'ogm.etid = n.nid');
    $query_comments->condition('ogm.gid', (int) $og_id);
    $query_comments->condition('ogm.entity_type', 'node');
  }

  $latest_updated_comment = $query_comments->execute()->fetchField();

  // Find and return latest activity by comparing latest update node & comment.
  $latest_activity = max($latest_updated_node, $latest_updated_comment);
  return empty($latest_activity) ? 0 : $latest_activity;
}

/**
 * Implements hook_c4m_content_statistics_info().
 */
function c4m_content_group_c4m_content_statistics_info() {
  return array(
    'global' => array(
      'c4m_groups' => array(
        'type'        => 'group',
        'entity_type' => 'node',
        'bundles'     => array('group'),
        'singular'    => 'Group',
        'plural'      => 'Groups',
        'state'       => 1,
        'aggregate'   => array(),
        'weight'      => -4,
        'attributes'  => array(
          'class' => array('groups'),
        ),
        'link' => array(
          'path' => 'groups',
        ),
      ),
    ),
    'topic' => array(
      'c4m_topic_groups' => array(
        'type'        => 'group',
        'entity_type' => 'node',
        'bundles'     => array('group'),
        'singular'    => 'Group',
        'plural'      => 'Groups',
        'state'       => 1,
        'aggregate'   => array(),
        'weight'      => 0,
        'attributes'  => array(
          'class' => array('topic-groups'),
        ),
        'link' => array(
          'path' => 'groups',
          'options' => array(
            'query' => array(
              'f' => array(
                'c4m_vocab_topic:@TOPIC_ID',
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_content_group_c4m_helper_entity_metrics_info() {
  return array(
    'c4m_groups_latest_activity' => array(
      'type'     => 'latest_activity',
      'context'  => 'group',
      'callback' => 'c4m_content_group_get_latest_activity',
      'weight'   => 0,
    ),
    'c4m_user_groups' => array(
      'type' => 'groups',
      'context'  => 'user',
      'callback'  => 'c4m_user_get_node_metric',
      'arguments' => array(array('group')),
    ),
    'c4m_user_groups_administered' => array(
      'type' => 'groups_administered',
      'context'  => 'user',
      'callback' => 'c4m_user_get_administered_groups_count',
    ),
  );
}

/**
 * Implements hook_ds_fields_info().
 */
function c4m_content_group_ds_fields_info($entity_type) {
  $fields = array();

  $path = drupal_get_path('module', 'c4m_content_group');

  $fields['node']['c4m_content_group_statistics'] = array(
    'title'      => t('Group statistics'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    // Only for group nodes.
    'ui_limit'   => array('group|*'),
    'file'       => $path . '/includes/c4m_content_group_statistics.theme.inc',
    'function'   => 'c4m_content_group_statistics',
  );

  return $fields;
}

/**
 * Returns the administered groups count for an user.
 *
 * @param int $uid
 *   User id.
 *
 * @return int
 *   Count.
 */
function c4m_user_get_administered_groups_count($uid) {
  return c4m_og_get_user_administered_groups_count($uid, 'group');
}

/**
 * Implements hook_c4m_helper_entity_label_info().
 */
function c4m_content_group_c4m_helper_entity_label_info() {
  return array(
    'group' => array(
      'article' => t('a'),
      'singular' => t('group'),
      'plural' => t('groups'),
      'insert action' => t('created a new group'),
      'update action' => t('updated the group'),
      'icon' => 'fa-users',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function c4m_content_group_theme() {
  $theme['c4m_content_group_header_title'] = array(
    'variables' => array(
      'title' => '',
      'group_type' => '',
      'group_access' => '',
      'group_status' => '',
      'organisations' => array(),
      'organisation_icons' => array(),
      'organisation_ellipsis' => FALSE,
      'emails' => array(),
    ),
    'path' => drupal_get_path('module', 'c4m_content_group') . '/theme',
    'template' => 'c4m-content-group-header-title',
  );

  $theme['c4m_og_vocab'] = array(
    'template' => 'c4m_og_vocab',
    'path' => drupal_get_path('module', 'c4m_content_group') . '/templates',
    'variables' => array(),
  );

  return $theme;
}

/**
 * Implements hook_TYPE_alter().
 *
 * Using hook_c4m_offcanvas_trigger_label_left_alter().
 */
function c4m_content_group_c4m_offcanvas_trigger_label_left_alter(&$trigger_label) {
  if (arg(0) == 'groups' && empty(arg(1))) {
    $trigger_label['label'] = t('Filter results');
    $trigger_label['icon'] = 'filter';
  }
}

/**
 * Implements hook_field_extra_fields().
 *
 * Add the 'Group Admins' field in the group dashboard management.
 */
function c4m_content_group_field_extra_fields() {
  $extra_fields['node']['group']['display']['group_admins'] = array(
    'label' => t('Group Admins'),
    'description' => t('Group Admins'),
    'weight' => 0,
  );

  return $extra_fields;
}

/**
 * Implements hook_node_view_alter().
 *
 * Adding the 'Group administrators' view for the group_admins field.
 */
function c4m_content_group_node_view($node, $view_mode, $langcode) {
  if ($view_mode != "group_dashboard") {
    return;
  }

  $accounts = c4m_og_get_group_admins($node->nid);

  $links = array();
  foreach ($accounts as $account) {
    $uri = entity_uri('user', $account);
    $links[] = l(c4m_user_name($account), $uri['path']);
  }

  $node->content['group_admins'] = array(
    '#type' => 'item',
    '#title' => t('Group administrators'),
    '#title_display' => 'above',
    '#markup' => implode(",", $links),
  );

  c4m_content_group_taxonomy_tree_build($node, 'c4m_vocab_topic');
  c4m_content_group_taxonomy_tree_build($node, 'c4m_vocab_geo');
}

/**
 * Build a tree of a hierarchical_taxonomy, for custom theming.
 *
 * @param object $node
 *   The node tree.
 * @param string $content
 *   The content type name.
 */
function c4m_content_group_taxonomy_tree_build(&$node, $content) {
  $options = array(
    'absolute' => TRUE,
    'purl' => array('disabled' => TRUE),
  );

  foreach ($node->content[$content]['#items'] as $index => $item) {
    $taxonomy = $item['taxonomy_term'];

    $options['query'] = array(
      'f[0]' => 'c4m_vocab_topic:' . $taxonomy->tid,
    );

    // Create different link for 'Topic' tags and 'Regions' tags.
    if ($taxonomy->vocabulary_machine_name == 'c4m_vocab_topic') {
      $taxonomy_link = l($taxonomy->name, 'groups', $options);
    }
    else {
      $taxonomy_link = l($taxonomy->name, "/taxonomy/term/" . $taxonomy->tid);
    }

    // Create the tree.
    $tree_name = array();
    $tree = hierarchical_taxonomy_get_tree($taxonomy->vid, $taxonomy->tid);
    foreach ($tree as $term) {
      $tree_name[] = l($term->name, "/taxonomy/term/" . $term->tid);
    }

    $variables = array(
      'root' => $taxonomy_link,
      'tree' => implode(', ', $tree_name),
    );

    $node->content[$content][$index]['#markup'] = theme('c4m_og_vocab', $variables);
  }
}
