<?php

/**
 * @file
 * Installation hooks for the Group Discussions feature.
 */

/**
 * Implements hook_install().
 */
function c4m_features_og_discussions_install() {
  // Install this feature.
  c4m_og_feature_install('c4m_features_og');
}

/**
 * Implements hook_uninstall().
 */
function c4m_features_og_discussions_uninstall() {
  // Uninstall this feature.
  c4m_og_feature_uninstall('c4m_features_og');
}
