<?php

/**
 * @file
 * Code for the Media feature.
 */

include_once 'c4m_features_og_media.features.inc';

define('C4M_FEATURES_OG_MEDIA_SORT_BY_COMMENT_COUNT', 'Comment count');

/**
 * Implements hook_c4m_og_feature_info().
 */
function c4m_features_og_media_c4m_og_feature_info() {
  return array(
    'c4m_features_og_media' => array(
      'name' => t('Media'),
      'description' => t('Media overview.'),
      'machine_name' => 'c4m_features_og_media',
      'weight' => 3,
      'default' => TRUE,
      'group_types' => array('group', 'project'),
      'content_types' => array('photo', 'photoalbum'),
    ),
  );
}

/**
 * Implements custom hook_search_api_sorts_alter().
 *
 * See Class c4m_views_handler_area_search_api_sorts.
 * Unfortunately search_api_sorts module provides one sort block and not a
 * block per view, so we need to alter some stuff. Here we remove superfluous
 * sorts.
 */
function c4m_features_og_media_search_api_sorts_alter(&$block, $view) {
  // Remove 'Comment count' sort if this is the media overview.
  if ($view->name === 'overview_og_media') {
    foreach ($block['content']['#items'] as $key => $item) {
      if (C4M_FEATURES_OG_MEDIA_SORT_BY_COMMENT_COUNT === $item['#name']) {
        unset($block['content']['#items'][$key]);
        break;
      }
    }
  }
}

/**
 * Implements hook_wysiwyg_filter_elements_blacklist_alter().
 *
 * Remove iframe from WYSIWYG Filter blacklist.
 */
function c4m_features_og_media_wysiwyg_filter_elements_blacklist_alter(&$blacklist) {
  $new_blacklist = array();
  foreach ($blacklist as $value) {
    if ($value !== 'iframe') {
      $new_blacklist[] = $value;
    }
  }
  $blacklist = $new_blacklist;
}

/**
 * Implements hook_media_browser_params_alter().
 *
 * Make sure Media Browser settings are picked up correctly.
 */
function c4m_features_og_media_media_browser_params_alter(&$stored_params) {
  // Set the default browser params from settings form if not already set.
  if (empty($stored_params['enabledPlugins'])) {
    $stored_params['enabledPlugins'] = variable_get('media_wysiwyg_wysiwyg_browser_plugins', array());
  }
  if (empty($stored_params['file_directory'])) {
    $stored_params['file_directory'] = variable_get('media_wysiwyg_wysiwyg_upload_directory', '');
  }
  if (empty($stored_params['types'])) {
    $stored_params['types'] = variable_get('media_wysiwyg_wysiwyg_allowed_types', array(
      'audio',
      'image',
      'video',
      'document',
    ));
  }
}
