<?php
/**
 * @file
 * Code for the Media feature.
 */

include_once 'c4m_features_og_media.features.inc';

/**
 * Implements hook_c4m_og_feature_info().
 */
function c4m_features_og_media_c4m_og_feature_info() {
  return array(
    'c4m_features_og_media' => array(
      'name' => t('Media'),
      'description' => t('Media overview.'),
      'machine_name' => 'c4m_features_og_media',
      'weight' => 3,
      'default' => TRUE,
      'group_types' => array('group', 'project'),
      'content_types' => array('photo', 'photoalbum'),
    ),
  );
}
