<?php

/**
 * @file
 * Code for the Book content type feature.
 */

include_once 'c4m_content_book.features.inc';

/**
 * Implements hook_menu().
 */
function c4m_content_book_menu() {
  $items['help-guidance/rearrange'] = array(
    'title' => 'Rearrange',
    'page callback' => 'c4m_content_book_help_rearrange_page',
    'access callback' => array('c4m_content_book_help_access'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function c4m_content_book_help_access($perm) {
  return 1;
}

/**
 * Page callback for the help pages rearrange menu item.
 *
 * @return mixed
 *   Returns help and guidance rearrange view.
 */
function c4m_content_book_help_rearrange_page() {
  drupal_set_title('Rearrange');

  // Get the node ID of the Help & Guidance book
  $help_book_title = variable_get('help_book', 'Help & Guidance');
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'book')
    ->propertyCondition('title', $help_book_title)
    ->propertyCondition('status', 1)
    ->propertyOrderBy('nid')
    ->range(0,1)
    ->execute();
  $nid = array_shift(array_keys($entities['node']));

  return views_embed_view('c4m_help_guidance', 'help_rearrange_page', 9);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_content_book_form_book_node_form_alter(&$form, &$form_state, $form_id) {


}
