<?php
/**
 * @file
 * Code for the Photo Album content type feature.
 */

include_once 'c4m_content_photoalbum.features.inc';

/**
 * Implements hook_c4m_og_vocab_info_content().
 */
function c4m_content_photoalbum_c4m_og_vocab_info_content() {
  return array(
    'photoalbum' => array(
      'entity_type' => 'node',
      'bundle' => 'photoalbum',
      'vocabularies' => array(
        'c4m_vocab_category',
        'c4m_vocab_tag',
      ),
    ),
  );
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_content_photoalbum_c4m_helper_entity_metrics_info() {
  return array(
    'c4m_og_photoalbums' => array(
      'type'      => 'photoalbum',
      'context'   => 'group',
      'callback'  => 'c4m_og_group_node_metric',
      'arguments' => array(array('photoalbum')),
      'weight'    => 2,
    ),
  );
}

/**
 * Implements hook_c4m_content_share_fields_info().
 */
function c4m_content_photoalbum_c4m_content_share_fields_info() {
  return array(
    'photoalbum' => array(
      'type',
    ),
  );
}

/**
 * Implements hook_c4m_helper_entity_label_info().
 */
function c4m_content_photoalbum_c4m_helper_entity_label_info() {
  return array(
    'photoalbum' => array(
      'article' => t('a'),
      'singular' => t('photo album'),
      'plural' => t('photo albums'),
      'insert action' => t('created a new photo album'),
      'update action' => t('updated the photo album'),
      'icon' => 'fa-picture-o',
    ),
  );
}
