<?php

/**
 * @file
 * Code for the C4M notifications feature.
 */


/**
 * Triggers email notification for different states of membership update.
 *
 * Notified states:
 *   Pending -> Accepted
 *   Pending -> Rejected
 *
 * Implements hook_entity_update.
 */
function c4m_notifications_entity_update($entity, $type) {
  if ($type != 'og_membership') {
    return;
  }

  if (empty($entity->original)) {
    // Must have original state.
    return;
  }

  if($entity->original->state != OG_STATE_PENDING) {
    // State change has to be initiated when state is Pending.
    return;
  }

  switch($entity->state)
  {
    case OG_STATE_ACTIVE:
      c4m_notifications_notify_membership_accepted($entity);
      break;
    case OG_STATE_BLOCKED:
      c4m_notifications_notify_membership_rejected($entity);
      break;
  }
}

function c4m_notifications_notify_membership_accepted($membership) {
  // Send activation message to member.
  $message = message_create('c4m_welcome_to_group', array('uid' => $membership->etid));
  c4m_message_load__c4m_welcome_to_group($message);

  $wrapper = entity_metadata_wrapper('message', $message);
  $wrapper->field_group_node->set($membership->gid);
  // Message will be saved in message_notify_send_message().
  message_notify_send_message($wrapper->value());

  return;
}

function c4m_notifications_notify_membership_rejected($entity) {
  return;
}

