<?php
/**
 * @file
 * Code for the Quick Post feature.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function c4m_features_overview_quick_post_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_theme().
 */
function c4m_features_overview_quick_post_theme() {
  $theme['c4m_features_overview_quick_post_angular_form'] = array(
    'template' => 'quick-post-form',
    'path' => drupal_get_path('module', 'c4m_features_overview_quick_post') . '/templates',
    'variables' => NULL,
  );

  return $theme;
}

/**
 * Page callback; Load the AngularJs form.
 *
 * @param int $node
 *  The ID of the current group.
 *
 * @param bool $debug
 *  Determines if to show the server side response.
 *
 * @return string
 *  A rendered form of the Quick Post.
 */
function c4m_features_overview_quick_post_form($node, $debug = FALSE) {
  $bower_path = libraries_get_path('bower_components');

  // Load the libraries.
  drupal_add_js($bower_path . '/angular/angular.js');

  // JSON pretty print library.
  drupal_add_js($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.js');
  drupal_add_css($bower_path . '/ng-prettyjson/dist/ng-prettyjson.min.css');

  // Load our custom app.
  $app_path = $bower_path . '/c4m-app/dist';
  drupal_add_js($app_path . '/c4m-app.js');
  drupal_add_css($app_path . '/css/c4m-app.css');

  // Pass info via Drupal.settings.
  $options = array(
    'purl' => array(
      'disabled' => TRUE,
    ),
    'absolute' => TRUE,
  );
  $settings['c4m'] = array(
    'basePath' => url('', $options),
    'csrfToken' => drupal_get_token(\RestfulInterface::TOKEN_VALUE),
    'debug' => $debug,
    'data' => array(
      'entity' => array(
        'label' => NULL,
        'group' => $node,
      ),
    ),
  );
  drupal_add_js($settings, 'setting');

  // Theme function adds the Quick post form.
  return theme('c4m_features_overview_quick_post_angular_form');
}
