<?php
/**
 * @file
 * Helper functionality around $entity objects.
 */

function c4m_helper_entity_get_entity_type_label($entity, $entity_type = 'node') {
  $variables = array(
    'entity' => $entity,
    'entity_type' => $entity_type,
    'label' => $entity_type,
  );

  if ($entity_type == 'node') {
    $variables['label'] = $entity->type;
  }

  $field_name = 'c4m_' . $entity->type . '_type';

  if (!empty($entity->$field_name)) {
    $object_wrapper = entity_metadata_wrapper('node', $entity);
    $variables['label'] = $object_wrapper->$field_name->value();
  }

  drupal_alter('entity_type_label', $variables);

  return $variables['label'];
}

/**
 * Helper function to sort objects on their title.
 *
 * @usage usort($array_entitiy_objects, 'c4m_sort_object_by_title');
 *
 * @param $a
 * @param $b
 *
 * @return int
 */
function c4m_sort_object_by_title($a, $b) {
  return strcasecmp($a->title, $b->title);
}

/**
 * Helper function to get the count per entity type and bundle.
 * @param $entity_type
 * @param array $bundles
 * @param null $published
 * @param null $group_id
 * @return int
 */
function c4m_helper_entity_get_number_of_entities($entity_type, $bundles = array(), $published = NULL, $og_id = NULL) {
  $amount = 0;

  if ($entity_type) {
    switch ($entity_type) {
      case 'user':
        $query = db_select('users', 'u');
        $query->fields('u');
        $query->condition('u.login', 0, '<>');
        break;
      case 'node':
        if (!empty($bundles)) {
          $query = db_select('node', 'n');
          $query->fields('n');
          $query->condition('n.type', $bundles, 'IN');
          if (!is_null($published)) {
            $query->condition('n.status', $published, '=');
          }
        }
        break;
      case 'comment':
        $query = db_select('comment', 'c');
        $query->fields('c');
        $query->join('node', 'n', 'c.nid = n.nid');
        break;
    }

    // Add group condition if given.
    if ($og_id) {
      switch ($entity_type) {
        case 'user':
          $query->join('og_membership', 'og', 'u.uid = og.etid');
          break;
        case 'node':
          $query->join('og_membership', 'og', 'n.nid = og.etid');
          break;
        case 'comment':
          $query->join('og_membership', 'og', 'n.nid = og.etid');
          break;
        default:
          return $amount;
          break;
      }

      $query->condition('og.gid', $og_id, '=');
    }

    $query  = $query->execute();
    $amount = $query->rowCount();
  }

  return $amount;
}