<?php
/**
 * @file
 * Code for the Search Content feature.
 */

include_once 'c4m_search_nodes.features.inc';


/**
 * Implements hook_c4m_search_page_info().
 */
function c4m_search_nodes_c4m_search_page_info() {
  return array(
    'c4m_search_nodes' => array(
      'name' => t('Site'),
      'description' => t('Search in all the site.'),
      'machine_name' => 'c4m_search_nodes',
      'path' => 'search',
      'weight' => 0,
      'default' => TRUE,
      'purl' => FALSE,
      'group' => t('Search in all site content'),
    ),
  );
}

/**
 * Mark a node for re-indexing.
 *
 * @param int $nid
 *   The Node ID of the node that needs to be re-indexed.
 */
function c4m_search_nodes_track_change($nid) {
  search_api_track_item_change('node', array($nid));
}

/**
 * Implements hook_views_pre_render().
 *
 * Set search page title to "Search <site-name>".
 */
function c4m_search_nodes_views_pre_render(&$view) {
  if ($view->name === 'c4m_search_nodes') {
    $site_name = variable_get('site_name');
    $title = t('Search @site-name', array('@site-name' => $site_name));
    $view->build_info['title'] = $title;
  }
}

