<?php

/**
 * @file
 * Code for the Groups overview feature.
 */

include_once 'c4m_features_overview_groups.features.inc';

/**
 * Implements hook_c4m_search_page_info().
 */
function c4m_features_overview_groups_c4m_search_page_info() {
  return array(
    'search_api_views_c4m_overview_groups' => array(
      'name' => t('Groups'),
      'description' => t('Search groups.'),
      'machine_name' => 'search_api_views_c4m_overview_groups',
      'path' => 'groups',
      'weight' => 2,
      'default' => FALSE,
      'type' => 'global',
    ),
  );
}

/**
 * Implements hook_views_data_alter().
 */
function c4m_features_overview_groups_views_data_alter(&$data) {
  $data['node']['title']['field']['handler'] = 'c4m_overview_groups_handler_title_no_purl';
}
