<?php

/**
 * @file
 * Functionality to provide missing info about a user.
 *
 * And his (activity within) groups.
 */

/**
 * Check if a user has a specific permission within the group.
 *
 * @param string $permission
 *   The permission name.
 * @param object $group
 *   (optional) If no group is given, the current group will be used.
 *
 * @return bool
 *   Has access to the given permission.
 */
function c4m_user_og_has_group_permission($permission, $group = NULL) {
  if (!og_context_is_init()) {
    // OG context was not determined yet, so register the path and return
    // early. The next time this access callback will be called, it will not
    // enter here.
    og_context_access_callback_register_path($_GET['q']);

    return NULL;
  }

  if (is_null($group) || is_object($group)) {
    $group = c4m_og_current_group();
  }

  if (!$group) {
    return FALSE;
  }

  // Re-use built-in og user access checks.
  return og_ui_user_access_group($permission, 'node', $group->nid);
}

/**
 * Get the role a user has within the given group.
 *
 * Only the highest role will be returned.
 * Possible roles (highest order to lowest):
 * - owner : the user is the owner (creator) of the group.
 * - administrator : the user can manage the group.
 * - member : the user is a member of the group.
 * - blocked : the user is blocked or his membership request was rejected.
 * - pending : the membership was requested and waiting for approval.
 *
 * @param object $user
 *   The user for who we are collecting his role.
 * @param object $group
 *   The group where we are trying to determine the users role for.
 *
 * @return string
 *   The user role.
 */
function c4m_user_og_get_role_in_group($user, $group) {
  // Group has no owner, return early to prevent showing an "Owner" label for
  // all anonymous visitors (since their uid is 0, they falsely match the group
  // owner id).
  if (empty($group->uid)) {
    return NULL;
  }

  // Is user the owner of the group node?
  if ((int) $user->uid === (int) $group->uid) {
    return 'owner';
  }

  // Has the user a membership for the given group?
  $membership = og_get_membership('node', $group->nid, 'user', $user->uid);
  if (!$membership) {
    return NULL;
  }

  // Check if not pending or blocked.
  switch ($membership->state) {
    case OG_STATE_PENDING:
      return 'pending';

    case OG_STATE_BLOCKED:
      return 'blocked';
  }

  // Check if the user has the administrator role.
  $roles = og_roles('node', $group->type, $group->nid);
  $admin_role = array_search(C4M_FEATURES_OG_MEMBERS_ADMINISTRATOR_ROLE_NAME, $roles);
  if ($admin_role) {
    $user_roles = og_get_user_roles('node', $group->nid, $user->uid);
    if (array_search(C4M_FEATURES_OG_MEMBERS_ADMINISTRATOR_ROLE_NAME, $user_roles)) {
      return 'administrator';
    }
  }

  // Ok, normal member.
  return 'member';
}

/**
 * Get the human name of the role a user has within a group.
 *
 * Is a wrapper around c4m_user_og_get_role_in_group(). It translates the
 * machine name of the role into a human label.
 *
 * @param object $user
 *   The user for who we are collecting his role.
 * @param object $group
 *   The group where we are trying to determine the users role for.
 *
 * @return string
 *   The human readable name of the user role.
 */
function c4m_user_og_get_role_in_group_human($user, $group) {
  $role = c4m_user_og_get_role_in_group($user, $group);
  $role_human = c4m_user_og_get_human_role_name($role, $group);
  return $role_human;
}

/**
 * Translate a machine user role name into a human name.
 *
 * @param string $role
 *   The machine name of the role.
 * @param object $group
 *   The (optional) group node for who we are translating the role name.
 *
 * @return string
 *   The human name of the role.
 */
function c4m_user_og_get_human_role_name($role, $group = NULL) {
  if (!$group) {
    $group = c4m_og_current_group();
  }
  if (!$group) {
    return FALSE;
  }

  $role_human = $role;
  $group_type = ucfirst(node_type_get_name($group));

  switch ($role) {
    case 'owner':
      $role_human = t('@group_type Owner', ['@group_type' => $group_type]);
      break;

    case 'administrator':
    case 'administrator member':
      $role_human = t('@group_type Administrator', ['@group_type' => $group_type]);
      break;

    case 'member':
      $role_human = t('@group_type Member', ['@group_type' => $group_type]);
      break;

    case 'blocked':
      $role_human = t('Blocked/Rejected Membership');
      break;

    case 'pending':
      $role_human = t('Requested Membership');
      break;
  }

  return $role_human;
}

/**
 * Get the number of posts (nodes) for the given user within the given group.
 *
 * @param int $uid
 *   The User ID.
 * @param int $gid
 *   The Group ID (node id).
 *
 * @return int
 *   Number of posts from user within group.
 */
function c4m_user_og_count_nodes_in_group($uid, $gid) {
  $query = db_select('node', 'n');
  $query->join('og_membership', 'ogm', 'n.nid = ogm.etid');
  $query->fields('n', ['nid'])
    ->condition('n.status', 1)
    ->condition('n.uid', (int) $uid)
    ->condition('ogm.gid', (int) $gid)
    ->condition('ogm.entity_type', 'node');

  return (int) $query->countQuery()->execute()->fetchField();
}

/**
 * Get the number of comments for the given user within the given group.
 *
 * @param int $uid
 *   The User ID.
 * @param int $gid
 *   The Group ID (node id).
 *
 * @return int
 *   Number of comments from user within group.
 */
function c4m_user_og_count_comments_in_group($uid, $gid) {
  $query = db_select('comment', 'c');
  $query->join('node', 'n', 'c.nid = n.nid');
  $query->join('og_membership', 'ogm', 'n.nid = ogm.etid');
  $query->fields('c', ['cid'])
    ->condition('c.status', 1)
    ->condition('n.status', 1)
    ->condition('c.uid', (int) $uid)
    ->condition('ogm.gid', (int) $gid)
    ->condition('ogm.entity_type', 'node');

  return (int) $query->countQuery()->execute()->fetchField();
}

/**
 * Check if a user has groups.
 *
 * @param mixed $account
 *   Optional account object, defaults to the active user.
 * @param string $bundle
 *   Optional bundle type, can be 'group' (default) or 'project'.
 * @param int $status
 *   Optional status of the groups to filter on, default published.
 *
 * @return bool
 *   Boolean indication if the user has groups.
 */
function c4m_user_og_has_groups($account = NULL, $bundle = 'group', $status = NODE_PUBLISHED) {
  $groups = og_get_groups_by_user($account);
  if (empty($groups)) {
    return FALSE;
  }

  // Count groups of bundle type.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $bundle)
    ->entityCondition('entity_id', $groups['node'], 'IN')
    ->propertyCondition('status', $status)
    ->count();
  $count = $query->execute();

  return $count > 0;
}

/**
 * Get groups a user belongs to.
 *
 * @param mixed $account
 *   Optional account object, defaults to the active user.
 * @param string $bundle
 *   Optional bundle type, can be 'group' (default) or 'project'.
 * @param int $status
 *   Optional status of the groups to filter on, default published.
 * @param bool $sort
 *   Optional sort boolean (sort by group status).
 * @param bool $allow_pending
 *   Optional include requested groups (pending status).
 *
 * @return array|void
 *   An array with the groups or an empty array.
 */
function c4m_user_og_get_groups($account = NULL, $bundle = 'group', $status = NODE_PUBLISHED, $sort = TRUE, $allow_pending = FALSE) {
  $groups = og_get_groups_by_user($account);
  // Include requested groups (pending status).
  if ($allow_pending) {
    $pending_groups = c4m_og_get_pending_groups_by_user(NULL, NULL, TRUE);
    if (isset($groups['node'])) {
      if (isset($pending_groups['node'])) {
        $groups['node'] += $pending_groups['node'];
      }
    }
    else {
      $groups = $pending_groups;
    }
  }

  if (empty($groups)) {
    return [];
  }

  // Load groups of bundle type.
  $conditions = is_null($bundle) ? [] : ['type' => $bundle];
  $group_nodes = node_load_multiple($groups['node'], $conditions);

  if (empty($group_nodes)) {
    return [];
  }

  // Sort groups by status.
  if ($sort && !empty($group_nodes)) {
    usort($group_nodes, 'c4m_sort_object_by_title');
    usort($group_nodes, '_c4m_og_sort_by_status');
  }

  return $group_nodes;
}

/**
 * Returns the amount of (group) contributors.
 *
 * @param int $og_id
 *   The Organic Group ID to eventually limit the query for.
 *
 * @return int
 *   The amount of contributors.
 */
function c4m_user_og_get_number_of_contributors($og_id = NULL) {
  $query = db_select('users', 'u');
  $query->join('node', 'n', 'n.uid = u.uid');
  $query->fields('u', ['uid']);
  $query->groupBy('u.uid');
  $query->condition('u.status', 1);
  $query->condition('n.status', 1);

  if (is_numeric($og_id)) {
    $query->join('og_membership', 'ogm', 'ogm.etid = n.nid');
    $query->condition('ogm.gid', (int) $og_id);
    $query->condition('ogm.entity_type', 'node');
  }

  return (int) $query->countQuery()->execute()->fetchField();
}

/**
 * Returns the amount of pending members in a group.
 *
 * @param int $og_id
 *   The Organic Group ID to limit the query for.
 *
 * @return int
 *   The amount of pending members of a group.
 */
function c4m_user_og_get_number_of_pending_members($og_id = NULL) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'og_membership');
  $query->propertyCondition('type', 'og_membership_type_default');
  $query->propertyCondition('entity_type', 'user');
  $query->propertyCondition('group_type', 'node');
  $query->propertyCondition('state', OG_STATE_PENDING);

  if (is_numeric($og_id)) {
    $query->propertyCondition('gid', $og_id);
  }

  return (int) $query->count()->execute();
}

/**
 * Returns the amount of active members in a group.
 *
 * @param int $og_id
 *   The Organic Group ID to limit the query for.
 *
 * @return int
 *   The amount of active members of a group.
 */
function c4m_user_og_get_number_of_active_members($og_id = NULL) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'og_membership');
  $query->propertyCondition('type', 'og_membership_type_default');
  $query->propertyCondition('entity_type', 'user');
  $query->propertyCondition('group_type', 'node');
  $query->propertyCondition('state', OG_STATE_ACTIVE);

  if (is_numeric($og_id)) {
    $query->propertyCondition('gid', $og_id);
  }

  return (int) $query->count()->execute();
}

/**
 * Implements hook_c4m_content_statistics_info().
 */
function c4m_user_og_c4m_content_statistics_info() {
  return [
    'group' => [
      'c4m_og_user' => [
        'type' => 'user',
        'entity_type' => 'user',
        'bundles' => [],
        'singular' => 'Member',
        'plural' => 'Members',
        'state' => 1,
        'c4m_status' => [1],
        'scope' => 'group',
        'aggregate' => [],
        'weight' => 7,
        'feature_name' => 'c4m_features_og_members',
        'attributes' => [
          'class' => ['og-users'],
        ],
        'link' => [
          'path' => 'members',
        ],
      ],
    ],
    'project' => [
      'c4m_og_user' => [
        'type' => 'user',
        'entity_type' => 'user',
        'bundles' => [],
        'singular' => 'Administrator',
        'plural' => 'Administrators',
        'state' => 1,
        'c4m_status' => [1],
        'scope' => 'group',
        'aggregate' => [],
        'weight' => 7,
        'feature_name' => 'c4m_features_og_members',
        'attributes' => [
          'class' => ['og-users'],
        ],
        'link' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_user_og_c4m_helper_entity_metrics_info() {
  return [
    'c4m_og_contributors' => [
      'type' => 'contributors',
      'context' => 'group',
      'callback' => 'c4m_user_og_get_number_of_contributors',
      'weight' => 9,
    ],
    'c4m_og_pending_members' => [
      'type' => 'pending_members',
      'context' => 'group',
      'callback' => 'c4m_user_og_get_number_of_pending_members',
      'weight' => 11,
    ],
    'c4m_og_users' => [
      'type' => 'users',
      'context' => 'group',
      'callback' => 'c4m_og_group_user_metric',
      'weight' => 7,
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function c4m_user_og_theme() {
  $theme['c4m_group_visitor_cta'] = [
    'template' => 'c4m_group_visitor_cta',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'url' => NULL,
      'button_label' => NULL,
      'button_icon' => NULL,
      'login_url' => NULL,
    ],
  ];

  $theme['c4m_group_text_cta'] = [
    'template' => 'c4m_group_text_cta',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'text' => NULL,
      'icon' => NULL,
      'wrapper_class' => 'c4m-group-text-cta text-copy--small',
      'text_class' => NULL,
    ],
  ];

  $theme['c4m_group_follow_cta'] = [
    'template' => 'c4m_group_follow_cta',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'text' => NULL,
      'wrapper_class' => 'c4m-group-follow-cta text-copy--small',
      'text_class' => NULL,
    ],
  ];

  $theme['c4m_group_manage_cta'] = [
    'template' => 'c4m_group_manage_cta',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'links' => NULL,
      'title' => NULL,
      'highlight' => NULL,
    ],
  ];

  $theme['c4m_unified_workflow_register'] = [
    'template' => 'c4m_unified_workflow_register',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'join_phrase' => NULL,
      'group_title' => NULL,
      'group_type' => NULL,
      'login_link' => NULL,
    ],
  ];

  $theme['c4m_unified_workflow_login'] = [
    'template' => 'c4m_unified_workflow_login',
    'path' => drupal_get_path('module', 'c4m_user_og') . '/templates',
    'variables' => [
      'group_title' => NULL,
    ],
  ];

  return $theme;
}

/**
 * Implements hook_c4m_cta_block().
 */
function c4m_user_og_c4m_cta_block() {
  global $user;

  // Only add items if there is a group.
  if (!$group = c4m_og_current_group()) {
    return;
  }

  // A blocked (banned) user should not be able to see the CTA block.
  $user_role = c4m_user_og_get_role_in_group($user, $group);
  if ($user_role == 'blocked') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $group);
  // Do not present CTA block for archived group.
  if ($wrapper->c4m_og_status->value() == 'archived') {
    return;
  }

  $items = [];

  if ($item = c4m_user_og_group_management_cta($group)) {
    $items['management'] = $item;
  }

  if ($item = c4m_user_og_group_actions_cta($group)) {
    $items['actions'] = $item;
  }

  if ($group->type == 'group') {
    if ($item = c4m_user_og_c4m_join_cta($group)) {
      $items['join'] = $item;
    }
    if ($item = c4m_user_og_follow_group_cta($group)) {
      $items['follow'] = $item;
    }
  }

  return $items;
}

/**
 * Sets the CTA block for visitors.
 */
function c4m_user_og_c4m_visitor_cta($group) {
  $types = [
    'open' => [
      'button_label' => t('Join this group'),
      'button_icon' => 'fa-user-plus',
    ],
    'moderated' => [
      'button_label' => t('Request membership for this group'),
      'button_icon' => 'fa-unlock-alt',
    ],
  ];

  $login_url = '';
  if (!user_is_logged_in()) {
    $login_link = l(t('log in'), 'user/login', ['query' => ['destination' => request_path()]]);
    $login_url = t('Please !login-link first if you have a C4D account', ['!login-link' => $login_link]);
  }

  if ($membership_request_value = c4m_og_get_group_membership_request($group)) {
    return [
      '#theme' => 'c4m_group_visitor_cta',
      '#button_label' => $types[$membership_request_value]['button_label'],
      '#button_icon' => $types[$membership_request_value]['button_icon'],
      '#url' => url('group/join/' . $group->nid, ['absolute' => TRUE]),
      '#login_url' => $login_url,
      '#weight' => 10,
    ];
  }
}

/**
 * Sets the different actions an user can do in the group.
 *
 * Includes: manage group, pending membership requests and draft content.
 */
function c4m_user_og_group_actions_cta($group) {
  $items = [];
  global $user;

  // CTAs for the group owner and administrators: Manage group and number or
  // new membership requests.
  if (c4m_features_og_members_is_power_user($group, $user)) {
    $exclude_invited_memberships = TRUE;
    if ($pending_requests = c4m_og_get_all_group_memberships_by_state($group->nid, OG_STATE_PENDING, $exclude_invited_memberships)) {
      $pending_id = $group->nid . '_pending';

      $link_text = format_plural(count($pending_requests), 'There is <a href="@link">1 new membership</a> request', 'There are <a href="@link">@requests new membership</a> requests', [
        '@link' => url('members', ['query' => ['f[0]' => 'c4m_og_membership_type:' . $pending_id]]),
        '@requests' => count($pending_requests),
      ]);

      $items['memberships'] = [
        '#theme' => 'c4m_group_text_cta',
        '#icon' => 'fa-user',
        '#text' => $link_text,
      ];
    }
  }

  if (!c4m_features_og_members_is_power_user()) {
    return;
  }

  // CTAs for members of the group: Amount of unpublished content.
  $variables = [
    'bundles' => [
      'wiki_page',
      'photo',
      'photoalbum',
      'discussion',
      'event',
      'document',
      'news',
    ],
    'state' => NODE_NOT_PUBLISHED,
    'entity_type' => 'node',
    'og_id' => $group->nid,
  ];

  if ($unpublished_content = c4m_helper_entity_get_number_of_entities($variables)) {
    $items['new-content'] = [
      '#theme' => 'c4m_group_text_cta',
      '#icon' => 'fa-exclamation-triangle',
      '#text' => t('You have <a href="@content_url">!content_number draft</a> @items', [
        '@content_url' => url('draft-content', ['purl' => ['disabled' => FALSE]]),
        '!content_number' => $unpublished_content,
        '@items' => format_plural($unpublished_content, 'item', 'items'),
      ]),
    ];
  }

  // Help & guidance.
  $items['help_guidance'] = [
    '#theme' => 'c4m_group_text_cta',
    '#icon' => 'fa-question',
    '#text' => l(t('Help & guidance'), 'help-guidance/help-guidance', ['purl' => ['disabled' => TRUE]]),
  ];

  $items['#weight'] = 5;

  return $items;
}

/**
 * Sets the different CTA management links for a group.
 *
 * Currently contains the "Manage group" and "Edit membership" links.
 */
function c4m_user_og_group_management_cta($group) {
  $items = [];

  if (c4m_features_og_members_is_power_user($group)) {
    $items['#title'] = t("You're the manager of this !group_type", ['!group_type' => $group->type]);
    $items['#links'][] = [
      '#theme' => 'c4m_group_text_cta',
      '#icon' => 'fa-cogs',
      '#text' => l(t("Manage !group_type", ['!group_type' => $group->type]), 'manage'),
    ];

    // Add project highlight icon.
    if (c4m_user_is_site_admin() && $group->type == 'project') {
      $field = [
        'entity' => $group,
        'view_mode' => 'block_list',
        'formatter_settings' => [
          'ft' => ['lb-cl' => 'block-list'],
        ],
      ];

      module_load_include('inc', 'c4m_ds', 'includes/c4m_ds.theme.node');
      $items['#highlight'] = theme_c4m_ds_node_highlight($field);
    }
  }

  if ($item = c4m_user_og_c4m_leave_group_cta($group)) {
    $items['#links'][] = $item;
  }

  // Do not allow to invite users into read-only group.
  if ($item = c4m_user_og_c4m_invite_cta($group)) {
    $items['#links']['invite'] = $item;
  }

  if (isset($items['#links'])) {
    $items['#theme'] = 'c4m_group_manage_cta';
    $items['#weight'] = 0;
  }

  return $items;
}

/**
 * Sets the join group link CTA.
 *
 * Sets the join group link CTA for logged in users that are not members
 * of the group yet.
 */
function c4m_user_og_c4m_join_cta($group) {
  $wrapper = entity_metadata_wrapper('node', $group);
  // Joining to an archived group is forbidden.
  if ($wrapper->c4m_og_status->value() == 'archived') {
    return;
  }

  if (og_is_member('node', $group->nid, 'user', NULL, [OG_STATE_PENDING])) {
    $message = t("This is a moderated group. Your request is waiting for approval. Continue to explore group's content.");
    drupal_set_message($message);

    return [
      '#theme' => 'c4m_group_text_cta',
      '#text' => t('Membership waiting approval'),
      '#icon' => 'fa-hourglass-end',
      '#wrapper_class' => 'c4m-wide-gothic-btn',
      '#text_class' => 'btn text-small',
    ];
  }

  if (og_is_member('node', $group->nid)) {
    return;
  }

  return c4m_user_og_c4m_visitor_cta($group);
}

/**
 * Sets the Invite a member link CTA.
 *
 * Sets the Invite a member link CTA for any group member to invite other
 * existing users or new people to join the group.
 */
function c4m_user_og_c4m_invite_cta($group) {
  if (user_is_anonymous() || !c4m_user_og_invite_access($group)) {
    return;
  }

  $url = url('group/node/' . $group->nid . '/admin/people/invite-visitors', ['absolute' => TRUE]);

  return [
    '#theme' => 'c4m_group_text_cta',
    '#icon' => 'fa-user-plus',
    '#text' => l(t('Invite a member'), $url),
    '#weight' => 15,
  ];
}

/**
 * Sets the CTA request membership link.
 */
function c4m_user_og_c4m_membership_cta($group) {
  // Default state for og_is_member is active.
  if (og_is_member('node', $group->nid)) {
    drupal_set_message(t('Welcome to group %group', ['%group' => $group->title]));
    return;
  }

  if (og_is_member('node', $group->nid, 'user', NULL, [OG_STATE_PENDING])) {
    $message = t("This is a moderated group. Your request is waiting for approval. Continue to explore group's content.");
    drupal_set_message($message);

    return [
      '#theme' => 'c4m_group_text_cta',
      '#text' => t('Membership waiting approval'),
      '#icon' => 'fa-hourglass-end',
      '#wrapper_class' => 'c4m-wide-gothic-btn',
      '#text_class' => 'btn text-small',
    ];
  }

  return [
    '#theme' => 'c4m_group_visitor_cta',
    '#button_label' => t('Request membership for this group'),
    '#button_icon' => 'fa-unlock-alt',
    '#url' => url('group/node/' . $group->nid . '/subscribe', ['absolute' => TRUE]),
  ];
}

/**
 * Sets the CTA to leave a group.
 */
function c4m_user_og_c4m_leave_group_cta($group) {
  // Non members and power users should not see this link.
  if (!og_is_member('node', $group->nid) || c4m_features_og_members_is_power_user($group)) {
    return;
  }

  $link = 'group/node/' . $group->nid . '/unsubscribe';
  return [
    '#theme' => 'c4m_group_text_cta',
    '#icon' => 'fa-pencil-square-o',
    '#text' => l(t('Edit membership'), $link, ['absolute' => TRUE]),
  ];
}

/**
 * Sets the CTA to follow or unfollow group notifications.
 *
 * For projects we should display this flag for all users, although for Groups
 * only members should be able to use it.
 *
 * @param object $group
 *   The group to follow (type might be 'group' or 'project').
 *
 * @return array|bool
 *   The settings for this flag, or FALSE if user should not see this.
 */
function c4m_user_og_follow_group_cta($group) {
  if ($group->type == 'group' && !og_is_member('node', $group->nid)) {
    return FALSE;
  }

  $item = [
    '#theme' => 'c4m_group_follow_cta',
    '#text' => c4m_content_theme_toggle_group_notification_link(),
    '#weight' => 50,
  ];

  return $item;
}

/**
 * Implements hook_menu_alter().
 *
 * Alters the default unsubscription callback from OG to avoid group owners to
 * leave the group before transfering the control of it.
 */
function c4m_user_og_menu_alter(&$menu) {
  $menu['group/%/%/unsubscribe']['page callback'] = 'c4m_user_og_unsubscription_custom_callback';
}

/**
 * Custom page callback to prevent group owners to leave a group.
 */
function c4m_user_og_unsubscription_custom_callback($group_type, $gid) {
  $is_node = $group_type == 'node';
  $user_is_owner = c4m_og_user_is_owner('node', $gid);

  // If the group is not a node or the logged in user is not the owner of the
  // group we return the default OG menu callback.
  if (!$is_node || !$user_is_owner) {
    return og_ui_unsubscribe($group_type, $gid);
  }

  $message = t("You can't leave the group if you are the owner. <a href=\"@link\">Transfer the ownership first.</a>", ['@link' => url('group/node/' . $gid . '/admin/owner')]);
  drupal_set_message($message, 'warning');

  $group = node_load($gid);
  $url = entity_uri($group_type, $group);
  drupal_goto($url['path']);
}

/**
 * Implements hook_menu().
 */
function c4m_user_og_menu() {
  $items['group/join/%node'] = [
    'title' => 'Join group',
    'type' => MENU_CALLBACK,
    'page callback' => 'c4m_user_og_unified_workflow',
    'page arguments' => [2],
    'access callback' => 'c4m_user_og_unified_workflow_access',
    'access arguments' => [2],
    'file' => 'c4m_user_og.page.inc',
  ];

  return $items;
}

/**
 * Access callback.
 *
 * Checks if user is banned from the requested group.
 *
 * @param object $group
 *   The group object.
 *
 * @return bool
 *   Access.
 */
function c4m_user_og_unified_workflow_access($group) {
  if (!og_context('node', $group)) {
    return FALSE;
  }

  if (c4m_og_user_is_banned($group->nid)) {
    return FALSE;
  }

  $wrapper = entity_metadata_wrapper('node', $group);
  if ($wrapper->c4m_og_status->value() == 'archived') {
    return FALSE;
  }

  return node_access('view', $group);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_og_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  if (empty($_SESSION['c4m_unified_workflow_gid_join'])) {
    return;
  }

  $group = node_load($_SESSION['c4m_unified_workflow_gid_join']);

  list($join_phrase, $button_label) = _c4m_og_registration_form_labels_by_group($group->nid);

  $variables = [
    'join_phrase' => $join_phrase,
    'group_title' => $group->title,
    'group_type' => c4m_og_get_group_type_from_node($group, TRUE),
    'login_link' => l(t('Log in.'), 'user/login'),
  ];
  drupal_set_title(theme('c4m_unified_workflow_register', $variables), PASS_THROUGH);

  $form['#submit'][] = 'c4m_user_og_unified_workflow_register_submit';
  $form['actions']['submit']['#value'] = $button_label;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function c4m_user_og_form_user_login_alter(&$form, &$form_state, $form_id) {
  if (empty($_SESSION['c4m_unified_workflow_gid_join'])) {
    return;
  }

  $group = entity_metadata_wrapper('node', $_SESSION['c4m_unified_workflow_gid_join']);
  drupal_set_title(theme('c4m_unified_workflow_login', ['group_title' => $group->label()]), PASS_THROUGH);

  $btn_text = t('Join @bundle', ['@bundle' => $group->getBundle()]);
  $form['#submit'][] = 'c4m_user_og_unified_workflow_login_submit';
  $form['actions']['submit']['#value'] = $btn_text;
}

/**
 * A submit handler for the unified workflow (registration).
 *
 * Setting a message to the user and redirect back to the group.
 */
function c4m_user_og_unified_workflow_register_submit($form, &$form_state) {
  if (empty($_SESSION['c4m_unified_workflow_gid_join'])) {
    return;
  }

  $group = node_load($_SESSION['c4m_unified_workflow_gid_join']);
  // Removing the original message of the user_register_form.
  drupal_get_messages('status');
  $message = t('Hey @name, thank you for submitting your details. Please activate your account by clicking the link sent to your e-mail to join the @group_title group.', [
    '@name' => c4m_user_name($form_state['user']),
    '@group_title' => $group->title,
  ]);

  drupal_set_message($message);
  $form_state['redirect'] = drupal_get_path_alias('node/' . $group->nid);

  // Store the group ID + user ID in the database after registration completes.
  c4m_user_og_store_unified_workflow($form_state['user']->uid, $group->nid);

  // drupal_goto has a fallback to the 'destination' so we must remove it.
  unset($_GET['destination']);

  // User is registered, and the variable is now stored in the database, the
  // session variable should be destroyed.
  unset($_SESSION['c4m_unified_workflow_gid_join']);
}

/**
 * A submit handler for the unified workflow (login).
 *
 * Setting a message to the user and redirect back to the group.
 */
function c4m_user_og_unified_workflow_login_submit($form, &$form_state) {
  if (empty($_SESSION['c4m_unified_workflow_gid_join'])) {
    return;
  }

  $group = node_load($_SESSION['c4m_unified_workflow_gid_join']);

  // Associate the user to the group after login.
  c4m_user_og_group_unified_workflow($group);

  $form_state['redirect'] = drupal_get_path_alias('node/' . $group->nid);

  // drupal_goto has a fallback to the 'destination' so we must remove it.
  unset($_GET['destination']);

  // User is logged in, the session variable should be destroyed.
  unset($_SESSION['c4m_unified_workflow_gid_join']);
}

/**
 * Associate a user to a group for unified workflow.
 *
 * Also sets a message depending on the group context.
 *
 * @param object $group
 *   The object of the group.
 * @param bool $account
 *   The object of the user.
 *
 * @see og_group()
 */
function c4m_user_og_group_unified_workflow($group, $account = FALSE) {
  $membership_request_value = c4m_og_get_group_membership_request($group);
  $values = [
    'state' => $membership_request_value == 'open' ? OG_STATE_ACTIVE : OG_STATE_PENDING,
    'entity' => $account,
  ];

  if (!og_group('node', $group, $values)) {
    drupal_set_message(t('A problem occurred trying to join the group.'), 'error');
    return;
  }
  else {
    if ($membership_request_value == 'open') {
      drupal_set_message(t('Welcome to group %group', ['%group' => $group->title]));
    }
  }
}

/**
 * Implements hook_mail_alter().
 */
function c4m_user_og_mail_alter(&$message) {
  if ($message['id'] != 'user_registrationpassword_register') {
    return;
  }

  $user = user_load_by_mail($message['to']);
  if (empty($_SESSION['c4m_unified_workflow_gid_join'])) {
    if (!$results = c4m_user_og_fetch_unified_workflow_entries($user->uid)) {
      return;
    }
    $gid = reset($results)->gid;
  }
  else {
    $gid = $_SESSION['c4m_unified_workflow_gid_join'];
  }

  $group = node_load($gid);
  $path = drupal_get_path('module', 'c4m_user_og');

  $text = file_get_contents($path . '/messages/user_registrationpassword_register_to_group_body.html');
  $variables = [
    'group' => $group,
    'user' => $user,
  ];

  $site_name = variable_get('site_name');
  $message['subject'] = "Activate your " . $site_name . " account\n";
  $message['from'] = format_string('"The @site team"<@mail>', [
    '@site' => $site_name,
    '@mail' => variable_get('site_mail'),
  ]);

  $message['body'] = [
    token_replace($text, $variables, [
      'language' => user_preferred_language($user),
      'callback' => 'c4m_user_og_mail_tokens',
      'sanitize' => FALSE,
      'clear' => TRUE,
    ]),
  ];
}

/**
 * Store a group ID + user ID in the database.
 *
 * @param string $uid
 *   The user ID.
 * @param string $gid
 *   The group ID.
 */
function c4m_user_og_store_unified_workflow($uid, $gid) {
  try {
    db_insert('c4m_unified_workflow')->fields([
      'uid' => $uid,
      'gid' => $gid,
    ])->execute();
  }
  catch (PDOException $e) {
    // Duplicated entry.
    watchdog('c4m_unified_workflow', $e->errorInfo[2], [], WATCHDOG_ERROR);
  }
}

/**
 * Fetch the entries for a specific user.
 *
 * @param string $uid
 *   The user ID.
 *
 * @return array
 *   Array with the entries.
 */
function c4m_user_og_fetch_unified_workflow_entries($uid) {
  return db_select('c4m_unified_workflow', 'uw')
    ->fields('uw')
    ->condition('uid', $uid)
    ->execute()
    ->fetchAll();
}

/**
 * Fetch the entries for a specific user.
 *
 * @param string $uid
 *   The user ID.
 *
 * @return bool
 *   TRUE if deleted the entries, FALSE otherwise.
 */
function c4m_user_og_delete_unified_workflow_entries($uid) {
  return db_delete('c4m_unified_workflow')->condition('uid', $uid)->execute();
}

/**
 * Token callback to add unsafe tokens for user mails.
 *
 * @see c4m_content_group_mail_tokens()
 * @see user_registrationpassword_mail_tokens()
 */
function c4m_user_og_mail_tokens(array &$replacements, array $data, $options) {
  c4m_content_group_replace_mail_tokens($replacements, $data, $options);
  user_registrationpassword_mail_tokens($replacements, $data, $options);

  // Adding destination to the link in order to redirect to the group page
  // after the activation.
  $replacements['[user:registrationpassword-url]'] .= '?destination=' . drupal_get_path_alias('node/' . $data['group']->nid);
}

/**
 * Implements hook_user_update().
 */
function c4m_user_og_user_update(&$edit, $account, $category) {
  if ($account->original->status || !$account->status) {
    return;
  }

  // Associate the user to the group.
  foreach (c4m_user_og_fetch_unified_workflow_entries($account->uid) as $entry) {
    $group = node_load($entry->gid);
    c4m_user_og_group_unified_workflow($group, $account);
  }

  // Destroy the entry of this account.
  c4m_user_og_delete_unified_workflow_entries($account->uid);
}

/**
 * Check current user permission to invite new members to the group.
 *
 * SA, GO and GA can always invite to the group. GM can only invite to Open
 * groups (either public or restricted) but not to moderated or private groups.
 *
 * @param object $group
 *   (optional) The group object, if not given then the current group will take
 *    place.
 *
 * @return bool
 *   TRUE if the current user has access to invite people to a group.
 */
function c4m_user_og_invite_access($group = NULL) {
  global $user;

  // If a group was not provided, try to get the current group.
  if (!$group) {
    if (!$group = c4m_og_current_group()) {
      return FALSE;
    }
  }

  // SAs, GOs and GAs can invite new members.
  if (c4m_features_og_members_is_power_user($group)) {
    return TRUE;
  }

  // Get request type (open/moderated).
  $membership_request_value = c4m_og_get_group_membership_request($group);
  // Get access type (public/private).
  $access_type = c4m_og_get_access_type($group);

  // For private or moderated groups, return false. Else check for member.
  if ($access_type['type'] == 'private' || $membership_request_value == 'moderated') {
    return FALSE;
  }

  return og_is_member('node', $group->nid, 'user', $user);
}
