<?php

/**
 * @file
 * Code for the Events overview feature.
 */

include_once 'c4m_features_overview_events.features.inc';

define('C4M_FEATURES_OVERVIEW_EVENTS_SORT_BY_START_DATE', 'Start Date');
define('C4M_FEATURES_OVERVIEW_EVENTS_SORT_BY_RELEVANCE', 'Relevance');

/**
 * Implements hook_c4m_search_page_info().
 */
function c4m_features_overview_events_c4m_search_page_info() {
  return array(
    'search_api_views_c4m_overview_events' => array(
      'name' => t('Events'),
      'description' => t('Search events.'),
      'machine_name' => 'search_api_views_c4m_overview_events',
      'path' => 'events',
      'weight' => 4,
      'default' => FALSE,
      'type' => 'global',
    ),
  );
}

/**
 * Implements hook_search_api_sorts_get_default_sort_alter().
 *
 * Courtesy of https://www.drupal.org/node/1894502.
 * Unfortunately search_api_sorts module provides one sort block and not a
 * block per view, so we need to alter some stuff. Here the default sort.
 */
function c4m_features_overview_events_search_api_sorts_default_sort_alter(&$default_sort, $search_sorts, $keys) {
  // Change default sort into 'Start Date' for events overviews.
  if (FALSE === strpos(current_path(), 'events', 0)) {
    return;
  }

  $default_sort = $default_sort;
  foreach ($search_sorts as $search_sort) {
    if (C4M_FEATURES_OVERVIEW_EVENTS_SORT_BY_START_DATE === $search_sort->name) {
      // Sort past events on date descending.
      if (0 === strpos(current_path(), 'events/past', 0)) {
        $search_sort->default_order = 'desc';
      }
      $default_sort = $search_sort;
      break;
    }
  }
}

/**
 * Implements custom hook_search_api_sorts_alter().
 *
 * See Class c4m_views_handler_area_search_api_sorts.
 * Unfortunately search_api_sorts module provides one sort block and not a
 * block per view, so we need to alter some stuff. Here we remove superfluous
 * sorts and give ours a new name.
 */
function c4m_features_overview_events_search_api_sorts_alter(&$block, $view) {
  $views_global = array(
    'c4m_overview_events',
    'c4m_overview_events_landing',
  );

  $views_group = array(
    'c4m_overview_og_events',
    'c4m_overview_og_events_landing',
  );

  // Remove 'Start date' sort if this is not an events overview.
  if (!in_array($view->name, array_merge($views_group, $views_global))) {
    foreach ($block['content']['#items'] as $key => $item) {
      if (C4M_FEATURES_OVERVIEW_EVENTS_SORT_BY_START_DATE === $item['#name']) {
        unset($block['content']['#items'][$key]);
        break;
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function c4m_features_overview_events_block_info() {
  $blocks['event_views_links'] = array(
    'info' => t('Links to event views'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  $blocks['event_total_count'] = array(
    'info' => t('Total number of events'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function c4m_features_overview_events_block_view($delta = '') {
  module_load_include('inc', 'c4m_features_overview_events', 'includes/c4m_features_overview_events.block');
  $callback = '_c4m_features_overview_events_block_' . $delta;
  if (!function_exists($callback)) {
    return NULL;
  }

  return $callback();
}

/**
 * Implements hook_search_api_query_alter().
 *
 * Apply filter on search results in event overview.
 */
function c4m_features_overview_events_search_api_query_alter(SearchApiQueryInterface $query) {
  if (FALSE === strpos(current_path(), 'events', 0)) {
    return;
  }

  $params = drupal_get_query_parameters();
  if (empty($params['filter'])) {
    return;
  }

  global $user;

  switch ($params['filter']) {
    case 'groups':
      // Get groups.
      $groups = og_get_groups_by_user();
      if (isset($groups['node'])) {
        $groups = $groups['node'];
      }
      else {
        return;
      }

      // Create filter.
      $filter = $query->createFilter('OR');

      // Filter on groups.
      foreach ($groups as $group) {
        $filter->condition('og_group_ref', $group);
      }

      // Apply filter.
      $query->filter($filter);
      break;

    case 'interests':
      // Get user object.
      $user_wrapper = entity_metadata_wrapper('user', $user->uid);

      // Get interests & regions.
      $interests = $user_wrapper->c4m_vocab_topic->raw();
      $regions = $user_wrapper->c4m_vocab_geo->raw();
      if (empty($interests) && empty($regions)) {
        return;
      }

      // Create filter.
      $filter = $query->createFilter('OR');

      // Filter on interests.
      foreach ($interests as $interest) {
        $filter->condition('c4m_vocab_topic', $interest);
      }

      // Filter on geographic regions.
      foreach ($regions as $region) {
        $filter->condition('c4m_vocab_geo', $region);
      }

      // Apply filter.
      $query->filter($filter);
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function c4m_features_overview_events_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == '_c4m_features_overview_events_block_event_filter_form') {
    // Unset the hidden token field and form_build_id field.
    unset($form['form_id'], $form['#token'], $form['form_build_id'], $form['#build_id']);
  }
}

/**
 * Implements hook_node_view_alter().
 *
 * On the events overviews we should not display the author of the event.
 */
function c4m_features_overview_events_node_view_alter(&$build) {
  if (empty($build['#bundle']) || $build['#bundle'] != 'event') {
    return;
  }

  if (empty($build['#view_mode']) || $build['#view_mode'] != 'teaser') {
    return;
  }

  $allowed_paths = array(
    'events',
    'events/upcoming',
    'events/past',
  );

  $item = menu_get_item();
  if (empty($item['path']) || !in_array($item['path'], $allowed_paths)) {
    return;
  }

  // Removing the author line.
  $build['c4m_user_first_and_last_name']['#access'] = FALSE;
  $build['c4m_ds_type_insert_action']['#access'] = FALSE;
  $build['c4m_ds_content_type_icon']['#access'] = FALSE;
}

/**
 * Gets the number of events per group via it's original view.
 *
 * @param string $type
 *   The type of events (upcoming / past).
 *
 * @return int
 *   The number of events.
 */
function _c4m_features_overview_events_count_via_views($type) {
  // Mapping by the original name of the display.
  $mapped_views = array(
    'upcoming' => 'page',
    'past' => 'attachment_1',
  );

  return _c4m_helper_entity_total_count_via_views('c4m_overview_events_landing', $mapped_views[$type]);
}

/**
 * Implements hook_views_pre_render().
 *
 * Make sure the access checks are done for the event nodes.
 */
function c4m_features_overview_events_views_pre_render(&$view) {
  if ($view->name !== 'c4m_events_calendar') {
    return;
  }
  foreach ($view->result as $key => $result) {
    $node = node_load($result->nid);
    if (!node_access('view', $node)) {
      unset($view->result[$key]);
    }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function c4m_features_overview_events_preprocess_views_view(&$vars) {
  $view = $vars['view'];
  $week_path = 'events/calendar/week';
  $month_path = 'events/calendar';
  if ($vars['name'] == 'c4m_overview_events_landing') {
    if ($vars['display_id'] == 'page') {
      $vars['month_view_url'] = l(t('Switch to calendar view'), $month_path);
    }
  }

  if ($view->name != 'c4m_events_calendar') {
    return;
  }
  $calendar_displays = [
    'month',
    'week',
  ];
  if (!in_array($view->current_display, $calendar_displays)) {
    return;
  }
  if ($view->current_display == 'month') {
    if (!empty($view->args[0])) {
      $date = explode("-", $view->args[0]);
      if (!empty($date[0]) && !empty($date[1])) {
        $year = $date[0];
        $current_month = date("m");
        if ($current_month != $date[1]) {
          $calendar_date = date_create($view->args[0] . '-01');
          $year_start_date = date_create($year . '-01-01');
          $diff = date_diff($calendar_date, $year_start_date);
          $weeks = floor($diff->days / 7) + 1;
          $week_path .= "/" . $year . "-W" . $weeks;
        }
      }
    }
  }
  else {
    if (!empty($view->args[0])) {
      $date = explode("-", $view->args[0]);
      if (!empty($date[0]) && !empty($date[1])) {
        $year = $date[0];
        $week = str_replace("W", '', $date[1]);
        $year_start_date = date_create($year . "-01-01");
        $calendar_date = date_add($year_start_date, date_interval_create_from_date_string($week . " weeks"));
        $month = $calendar_date->format('m');
        $month_path .= "/" . $year . "-" . $month;
      }
    }
  }

  $vars['week_view_url'] = l(t('Week'), $week_path);
  $vars['month_view_url'] = l(t('Month'), $month_path);
  $vars['list_view_url'] = l(t('Switch to list view'), 'events');
}
