#!/bin/bash

# Exit if we encounter a problem
set -e


# Define the root of the GIT repository
ROOT=$(git rev-parse --show-toplevel)



# Load the configuration file.
source $ROOT/config.sh

# Load the colors
source $ROOT/scripts/helper-colors.sh



# Drush executable.
[[ $DRUSH && ${DRUSH-x} ]] || DRUSH=drush

# Move to the top directory.
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

# Build the profile itself.
(
  cd $PROFILE_NAME
  $DRUSH make --no-core --contrib-destination drupal-org.make .
  cd ..
)

# Build core and move the profile in place.
(
  # Save the sites/default directory if it exists.
  if [ -d www/sites/default ]; then
    echo -e "${LBLUE}> Create backup of the www/sites/default directory${RESTORE}"
    mv www/sites/default sites-backup
  else
    mkdir -p www/sites/default
  fi
  chmod +w www/sites/* || true
  rm -Rf www || true

  # Build core.
  $DRUSH make $PROFILE_NAME/drupal-org-core.make www

  # Restore the sites directory.
  if [ -d sites-backup ]; then
    echo -e "${LBLUE}> Restore backup of the www/sites/default directory${RESTORE}"
    rm -Rf www/sites/default
    mv sites-backup/ www/sites/default
  fi

  # Move the profile in place.
  echo -e "${LBLUE}> Create symbolic link to the $PROFILE_NAME profile${RESTORE}"
  ln -s ../../$PROFILE_NAME www/profiles/$PROFILE_NAME
)
