#!/bin/bash

################################################################################
#
# This script will reset a local copy of the capacity4more distribution.
#
# Do not change the content of this file, 
# all configuration variables are in the config.sh file.
#
################################################################################


# Define the root of the GIT repository
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

# Load the colors
source $ROOT/scripts/helper-colors.sh


# Check if we can load the config file
if [ ! -f $ROOT/config.sh ]; then
	echo
    echo -e  "${BGRED}                                                                 ${RESTORE}"
    echo -e "${BGLRED}  ERROR: No configuration file found!                            ${RESTORE}"
    echo -e  "${BGRED}  > Check if the ${BGLRED}config.sh${BGRED} file exists in the same               ${RESTORE}"
    echo -e  "${BGRED}    directory of the ${BGLRED}install.sh${BGRED} script.                          ${RESTORE}"
    echo -e  "${BGRED}  > If not create one by creating a copy of ${BGLRED}default.config.sh${BGRED}.   ${RESTORE}"
    echo -e  "${BGRED}                                                                 ${RESTORE}"
    echo
    exit 1
fi

# Include the configuration file
source $ROOT/config.sh


# Check if we have a working Drupal bootstrap
cd $ROOT/www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd $ROOT
if [ ! "$BOOTSTRAP_SUCCESS" ]; then
  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  No working Drupal installation!                                ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully.            ${RESTORE}"
  echo -e  "${BGRED}  > An update can only be run on a working environment.          ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e  "${BGRED}  Run the ${BGLRED}./install${BGRED} command to install the platform.             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1
fi




# Always ask confirmation before destroying the Database & Files!
echo 
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e "${BGLBLUE}  Reset capacity4more                                            ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo -e  "${BGBLUE}  > This will delete the database and the files directory.       ${RESTORE}"
echo -e  "${BGBLUE}  > This will install the capacity4more profile.                 ${RESTORE}"
echo -e  "${BGBLUE}  > Drupal core, contrib modules & themes will not be replaced.  ${RESTORE}"
echo -e  "${BGBLUE}                                                                 ${RESTORE}"
echo

echo -e -n "${LRED}Are you sure?${RESTORE} (Y/n) "
read -e -n 1 -r
if [[ ! $REPLY =~ ^[Y]$ ]]; then
  echo 
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo -e "${BGLYELLOW}  Reset aborted!                                                 ${RESTORE}"
  echo -e  "${BGYELLOW}                                                                 ${RESTORE}"
  echo
  exit 0
fi
echo



# Cleanup the www/sites/default directory
if [ -d $ROOT/www/sites ]; then
	echo -e "${LBLUE}> Cleaning up the www/sites/default directory${RESTORE}"
	chmod 777 $ROOT/www/sites/default
	rm -rf $ROOT/www/sites/default/files
	rm -f $ROOT/www/sites/default/settings.php
	echo
fi
# Backup in case of we need sudo powers to get rid of the files directory.
if [ -d $ROOT/www/sites/default/files ]; then
	echo -e "${LBLUE}> Cleaning up the sites/default/files directory with sudo power!${RESTORE}"
	sudo rm -rf $ROOT/www/sites/default/files
	echo
fi
if [ -f $ROOT/www/sites/default/settings.php ]; then
	echo -e "${LBLUE}> Cleaning up the sites/default/files directory with sudo power!${RESTORE}"
	sudo rm -rf $ROOT/www/sites/default/files
	echo
fi


# Install the capacity4more profile
echo -e "${LBLUE}> Install Drupal with the capacity4more install profile${RESTORE}"
cd $ROOT/www
drush si -y $PROFILE_NAME \
  --locale=en \
  --account-name=$ADMIN_USERNAME \
  --account-pass=$ADMIN_PASSWORD \
  --account-mail=$ADMIN_EMAIL \
  --db-url=mysql://$MYSQL_USERNAME:$MYSQL_PASSWORD@$MYSQL_HOSTNAME/$MYSQL_DB_NAME \
  --uri=$BASE_DOMAIN_URL
echo
cd ..


# Setup the files directory
if [ ! -d www/sites/default/files ]; then
  echo -e "${LBLUE}> Create the files directory (sites/default/files directory)${RESTORE}"
  mkdir -p www/sites/default/files
fi

echo -e "${LBLUE}> Set the file permissions on the sites/default/files directory${RESTORE}"
chmod -R 775 www/sites/default/files
umask 002 www/sites/default/files
chmod -R g+s www/sites/default/files
echo


# Enable the development modules
echo -e "${LBLUE}> Enabling the development modules${RESTORE}"
#drush en -y devel views_ui field_ui migrate_ui
echo



# Check if we have a working bootstrap
cd $ROOT/www
BOOTSTRAP_SUCCESS=`drush status grep "Drupal bootstrap" | grep "Successful"`
cd $ROOT

if [ ! "$BOOTSTRAP_SUCCESS" ]; then

  echo
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo -e "${BGLRED}  Reset failure!                                                 ${RESTORE}"
  echo -e  "${BGRED}  > Drupal Bootstrap could not complete successfully             ${RESTORE}"
  echo -e  "${BGRED}                                                                 ${RESTORE}"
  echo
  exit 1

fi


# If we managed to get to here, the reset was a success
echo
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo -e "${BGLGREEN}  Reset complete!                                                ${RESTORE}"
echo -e  "${BGGREEN}  > Visit the site : ${BGLGREEN}capacity4more.dev${BGGREEN}.                          ${RESTORE}"
echo -e  "${BGGREEN}                                                                 ${RESTORE}"
echo

exit 0
