<?php
/**
 * @file
 * Code for the Article content type feature.
 */

include_once 'c4m_content_article.features.inc';

/**
 * Implements hook_c4m_content_statistics_info().
 */
function c4m_content_article_c4m_content_statistics_info() {
  return array(
    'global' => array(
      'c4m_articles' => array(
        'type'        => 'article',
        'entity_type' => 'node',
        'bundles'     => array('article'),
        'singular'    => 'Article',
        'plural'      => 'Articles',
        'state'       => NULL,
        'aggregate'   => array(),
        'weight'      => -5,
        'attributes'  => array(
          'class' => array('articles'),
        ),
        'link' => array(
          'path' => 'articles',
        ),
      ),
    ),
    'topic' => array(
      'c4m_topic_articles' => array(
        'type'        => 'article',
        'entity_type' => 'node',
        'bundles'     => array('article'),
        'singular'    => 'Article',
        'plural'      => 'Articles',
        'state'       => NULL,
        'aggregate'   => array(),
        'weight'      => 2,
        'attributes'  => array(
          'class' => array('topic-articles'),
        ),
        'link' => array(
          'path' => 'articles',
          'options' => array(
            'query' => array(
              'f' => array(
                'c4m_vocab_topic:@TOPIC_ID',
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_node_update().
 *
 * Subscribe notable contributors to the node.
 */
function c4m_content_article_node_update($node) {
  // Only for articles.
  if ($node->type != 'article') {
    return;
  }

  // Get the correct flag object.
  $subscribe_c4m_follow_node_flag = flag_get_flag('subscribe_c4m_follow_node');

  // Get all contributors of the current article.
  $contributors_current = is_array(field_get_items('node', $node, 'c4m_related_user'))
    ? field_get_items('node', $node, 'c4m_related_user') : array();

  // Get all subscribed users in the database.
  $flagged_users = flag_get_entity_flags('node', $node->nid, 'subscribe_c4m_follow_node');

  foreach ($flagged_users as $flagged_user) {
    if ($user = user_load($flagged_user->uid)) {
      // If user is subscribed, but not present in contributors.
      if (!array_search($flagged_user->uid, array_column($contributors_current, 'target_id'))) {
        // Unsubscribe.
        $subscribe_c4m_follow_node_flag->flag('unflag', $node->nid, $user);
      }
    }
  }

  foreach ($contributors_current as $contributor) {
    if ($user = user_load($contributor['target_id'])) {
      // If user is contributor, but not subscribed.
      if (!$subscribe_c4m_follow_node_flag->is_flagged($node->nid, $user->uid)) {
        // Subscribe.
        $subscribe_c4m_follow_node_flag->flag('flag', $node->nid, $user);
      }
    }
  }
}
