<?php

/**
 * @file
 * Installation hooks for the Group News feature.
 */

/**
 * Implements hook_install().
 */
function c4m_features_og_news_install() {
  // Install this feature.
  c4m_og_feature_install('c4m_features_og_news');
}

/**
 * Implements hook_uninstall().
 */
function c4m_features_og_news_uninstall() {
  // Uninstall this feature.
  c4m_og_feature_uninstall('c4m_features_og_news');
}
