<?php

/**
 * @file
 * Code for the Theme settings feature.
 */

include_once 'c4m_features_theme.features.inc';

/**
 * Implements hook_bootstrap_colorize_text_alter().
 */
function c4m_features_theme_bootstrap_colorize_text_alter(&$texts) {
  // This matches the exact string: "My Unique Button Text".
  $texts['matches'][t('Log in')] = 'primary';
  $texts['matches'][t('Register to join')] = 'success';
  $texts['matches'][t('Join group')] = 'primary';
  $texts['matches'][t('Join project')] = 'primary';
  $texts['matches'][t('Request membership for group')] = 'success';
}

/**
 * Implements hook_form_alter().
 *
 * Moving the '#description' variable (for the help-text).
 */
function c4m_features_theme_form_alter(&$form, &$form_state, $form_id) {
  $item = menu_get_item();
  preg_match('/^admin\/.*$/', $item['path'], $matches);
  // Disable the switch under admin pages.
  if (!empty($matches[0])) {
    return;
  }

  _c4m_features_theme_set_what_is_this($form);
}

/**
 * Moving the '#description' variable (for the help-text).
 *
 * In order to display the help-text within a tooltip only, we should remove
 * the '#description' variable. The tooltip is being rendered on the
 * kapablo_form_element_label() by checking the '#what_is_this' variable on the
 * element.
 *
 * @param array $elements
 *   Originally this object is the form from the hook_form_alter(). Since it is
 *   a recursive function then it may change during the calls.
 */
function _c4m_features_theme_set_what_is_this(array &$elements) {

  foreach ($elements as &$element) {
    if (is_array($element)) {
      // The current $element is an array, hence we're keep checking its
      // children.
      _c4m_features_theme_set_what_is_this($element);
    }
    elseif (is_object($element)) {
      // Since we know that the #description is an array element and at the
      // point the current $element is not an array but an object we should
      // skip it.
      continue;
    }

    if (isset($element['#description']) && !isset($element['#what_is_this'])) {
      // Replace between the variables.
      $element['#what_is_this'] = $element['#description'];
      $element['#description'] = NULL;
    }
  }
}
