<?php
/**
 * @file
 * Code for the Project content type feature.
 */

include_once 'c4m_content_project.features.inc';

/**
 * Implements hook_c4m_og_vocab_info_groups().
 */
function c4m_content_project_c4m_og_vocab_info_groups() {
  return array(
    'project' => array(
      'c4m_vocab_category',
      'c4m_vocab_tag',
    ),
  );
}

/**
 * Implements hook_c4m_content_statistics_info().
 *
 * @todo add c4m_status when it's available in the project content type
 */
function c4m_content_project_c4m_content_statistics_info() {
  return array(
    'global' => array(
      'c4m_projects' => array(
        'type'        => 'project',
        'entity_type' => 'node',
        'bundles'     => array('project'),
        'singular'    => 'Project',
        'plural'      => 'Projects',
        'state'       => 1,
        'aggregate'   => array(),
        'weight'      => -3,
        'attributes'  => array(
          'class' => array('projects'),
        ),
        'link' => array(
          'path' => 'projects',
        ),
      ),
    ),
  );
}
