<?php

/**
 * @file
 * Code for the Wysiwyg Ckeditor module.
 */

include_once 'c4m_wysiwyg_ckeditor.features.inc';

/**
 * Implements hook_ckeditor_plugin().
 */
function c4m_wysiwyg_ckeditor_ckeditor_plugin() {
  $module_path = drupal_get_path('module', 'c4m_wysiwyg_ckeditor');
  $plugins = array();

  // Widget plugin.
  $plugins['widget'] = array(
    'name' => 'widget',
    'desc' => t('CKEditor: Widget plugin'),
    'path' => $module_path . '/ckeditor-plugins/widget/',
    'default' => 't',
  );

  // Line utils plugin.
  $plugins['lineutils'] = array(
    'name' => 'lineutils',
    'desc' => t('CKEditor: Line utils plugin'),
    'path' => $module_path . '/ckeditor-plugins/lineutils/',
    'default' => 't',
  );

  // Oembed plugin.
  $plugins['oembed'] = array(
    'name' => 'oembed',
    'desc' => t('CKEditor: Oembed plugin'),
    'path' => $module_path . '/ckeditor-plugins/oembed/',
    'default' => 't',
    'buttons' => array(
      'oembed' => array(
        'label' => 'Oembed',
        'icon' => 'icons/oembed.png',
      ),
    ),
  );

  // Tableresize plugin.
  $plugins['tableresize'] = array(
    'name' => 'tableresize',
    'desc' => t('CKEditor: Tableresize plugin'),
    'path' => $module_path . '/ckeditor-plugins/tableresize/',
    'default' => 't',
  );

  return $plugins;
}

/**
 * Implements hook_form_alter().
 *
 * Hide the URL settings in the popup.
 */
function c4m_wysiwyg_ckeditor_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id !== 'file_entity_add_upload' && $form_id !== 'media_wysiwyg_format_form') {
    return;
  }

  // Don't present the redirects options on a file upload.
  if (isset($form['redirect'])) {
    unset($form['redirect']);
  }

  if (isset($form['#formats'])) {
    unset($form['#formats']['node_gallery_api_admin_thumbnail']);
    unset($form['#formats']['c4m_preview']);
  }
}

/**
 * Implements hook_media_wysiwyg_format_form_prepare_alter().
 *
 * @see https://www.drupal.org/node/2460885
 */
function c4m_wysiwyg_ckeditor_media_wysiwyg_format_form_prepare_alter(
  &$form,
  &$form_state,
  $file
) {
  // Attach JavaScript to automatically embed files.
  $form['#attached']['js'][] = drupal_get_path(
      'module',
      'c4m_wysiwyg_ckeditor'
    ) . '/c4m_wysiwyg_ckeditor.js';
}
