<?php

/**
 * @file
 * Code for the Comment feature.
 */

include_once 'c4m_comment.features.inc';

/**
 * Implements hook_module_implements_alter().
 *
 * In order to be able to alter the node form after the "Comment" module,
 * we have to make sure that the hook "form_alter" of the "c4m_comment" module
 * called last.
 * Note that we use "form_alter" hook here even though we actually implement
 * "form_BASE_FORM_ID_alter", but this is correct :-)
 *
 * @see hook_module_implements_alter()
 */
function c4m_comment_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['c4m_comment'])) {
    $group = $implementations['c4m_comment'];
    unset($implementations['c4m_comment']);
    $implementations['c4m_comment'] = $group;
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function c4m_comment_form_node_form_alter(array &$form, array $form_state) {
  $node = $form['#node'];

  // Remove the comment settings if the default is set to be closed.
  // --> Project specific approach!
  $comment_default_mode = variable_get('comment_' . check_plain($node->type), NULL);
  if ($comment_default_mode == COMMENT_NODE_CLOSED) {
    $form['comment_settings']['#access'] = FALSE;
    return;
  }

  // We only allow general access to the comment settings for OG content.
  if (!og_is_group_content_type('node', $node->type)) {
    return;
  }

  // If the user has access to the node form, he can also change the comment
  // settings for this content entry.
  $form['comment_settings']['#access'] = TRUE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for comment_form().
 */
function c4m_comment_form_comment_form_alter(array &$form, array $form_state) {
  if (isset($form_state['comment']->cid)) {
    $comment = $form_state['comment'];
    if (!c4m_user_is_site_admin()) {
      $form['author']['#access'] = FALSE;
      // If the user is not SA, but edits a comment (is GA) the author needs to
      // be changed. comment_form() sets the current user and we need to use the
      // original user.
      $form['author']['name']['#value'] = !$comment->uid && $comment->name ? $comment->name : $comment->registered_name;
    }
  }
  else {
    // Add "Post Activity" checkbox.
    $form['post_activity'] = [
      '#type' => 'checkbox',
      '#title' => t('Post Activity'),
      '#default_value' => TRUE,
      '#access' => _c4m_comment_post_activity_access(),
    ];

    // Add "Send Notification" checkbox.
    $form['send_notification'] = [
      '#type' => 'checkbox',
      '#title' => t('Send Notification'),
      '#default_value' => TRUE,
    ];

    // Don't display author info.
    $form['author']['#access'] = FALSE;
  }
}

/**
 * Implements hook_field_attach_submit().
 *
 * Sets the _skip_message flag, if needed, for comment entity.
 */
function c4m_comment_field_attach_submit($entity_type, $entity, $form, &$form_state) {
  if ($entity_type !== 'comment') {
    return;
  }
  $skip_message = _c4m_comment_post_activity_access() && empty($form_state['values']['post_activity']);
  if ($skip_message) {
    $entity->_skip_message = TRUE;
  }

  $entity->c4m_send_notification = !empty($form_state['values']['send_notification']);
}

/**
 * Access callback for the "Post Activity" checkbox.
 *
 * @return bool
 *   TRUE if the checkbox should be displayed.
 */
function _c4m_comment_post_activity_access() {
  return c4m_user_is_site_admin();
}

/**
 * Implements hook_c4m_content_statistics_info().
 */
function c4m_comment_c4m_content_statistics_info() {
  return array(
    'global' => array(
      'c4m_comment' => array(
        'type' => 'comment',
        'entity_type' => 'comment',
        'bundles' => array(),
        'singular' => 'Post',
        'plural' => 'Posts',
        'state' => 1,
        'skip_access_check' => TRUE,
        'aggregate' => array(
          'type' => 'posts',
        ),
        'weight' => 1,
        'attributes' => array(
          'class' => array('posts'),
        ),
      ),
    ),
    'group' => array(
      'c4m_og_comment' => array(
        'type' => 'comment',
        'entity_type' => 'comment',
        'bundles' => array(),
        'singular' => 'Comment',
        'plural' => 'Comments',
        'state' => 1,
        'aggregate' => array(),
        'weight' => 6,
        'attributes' => array(
          'class' => array('og-comments'),
        ),
      ),
    ),
    'project' => array(
      'c4m_og_comment' => array(
        'type' => 'comment',
        'entity_type' => 'comment',
        'bundles' => array(),
        'singular' => 'Comment',
        'plural' => 'Comments',
        'state' => 1,
        'aggregate' => array(),
        'weight' => 6,
        'attributes' => array(
          'class' => array('og-comments'),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_c4m_helper_entity_metrics_info().
 */
function c4m_comment_c4m_helper_entity_metrics_info() {
  return array(
    'c4m_og_comments' => array(
      'type'      => 'comment',
      'context'   => 'group',
      'callback'  => 'c4m_og_group_comment_metric',
      'weight'    => 0,
    ),
    'c4m_user_comments' => array(
      'type' => 'comments',
      'context'   => 'user',
      'callback'  => 'c4m_comment_get_comments_by_user',
    ),
  );
}

/**
 * Returns the number of comments for a particular user.
 *
 * @param int $uid
 *   User ID.
 *
 * @return int
 *   Number of comments.
 */
function c4m_comment_get_comments_by_user($uid) {
  $arguments = array(
    'entity_type' => 'comment',
    'uid' => $uid,
  );

  return c4m_helper_entity_get_number_of_entities($arguments);
}

/**
 * Implements hook_node_view_alter().
 *
 * @see comment_node_view()
 * @see comment_node_page_additions()
 */
function c4m_comment_node_view_alter(&$build) {
  $node = $build['#node'];
  $view_mode = $build['#view_mode'];

  // Remove the comment form on all archived group's content for non SA.
  if (($group = c4m_og_get_group_of_content($node)) && $group->type == 'group') {
    $group_wrapper = entity_metadata_wrapper('node', $group);
    if ($group_wrapper->c4m_og_status->value() == 'archived') {
      if (!c4m_user_is_site_admin()) {
        unset($build['comments']);

        return;
      }
    }
  }

  // Only append comments when we are building a node on its own node detail
  // page. We compare $node and $page_node to ensure that comments are not
  // appended to other nodes shown on the page, for example a node_reference
  // displayed in 'full' view mode within another node.
  if ($node->comment && $view_mode == 'full' && node_is_page(
      $node
    ) && empty($node->in_preview)
  ) {
    // There are no comments yet but comments are enabled.
    if (user_is_anonymous() && $node->comment == COMMENT_NODE_OPEN) {
      $register_link = l(t('Register'), 'user/register');
      $login_link = l(
        t('log in'),
        'user/login',
        array(
          'query' => array('destination' => request_path()),
        )
      );

      $text = '<p class="comment-wrapper margin--top">' . t(
          '!register or !login to comment',
          array(
            '!register' => $register_link,
            '!login' => $login_link,
          )
        ) . '</p>';

      if (empty($build['comments'])) {
        $build['comments'] = array(
          '#markup' => $text,
        );
      }
      else {
        $build['comments']['comments'][] = array(
          '#markup' => $text,
        );
      }
    }
  }
}

/**
 * Implements hook_c4m_helper_entity_label_info().
 */
function c4m_comment_c4m_helper_entity_label_info() {
  return array(
    'comment' => array(
      'article' => t('a'),
      'singular' => t('comment'),
      'plural' => t('comments'),
      'insert action' => t('commented on'),
      'update action' => t('updated a comment'),
      'icon' => 'fa-comments',
    ),
  );
}

/**
 * Implements hook_user_cancel().
 *
 * Since we use a different method, we should cover the anonymize content for
 * comments manually as well.
 */
function c4m_comment_user_cancel($edit, $account, $method) {
  if (!in_array($method, c4m_user_profile_get_cancel_methods_to_reassign())) {
    return;
  }

  $comments = comment_load_multiple(array(), array('uid' => $account->uid));
  foreach ($comments as $comment) {
    $comment->uid = 0;
    // The comment instance saves the original username as well.
    $comment->name = t('Anonymous');
    comment_save($comment);
  }
}

/**
 * Implements hook_comment_view().
 *
 * When a user is forbidden to take actions on a comment we should display the
 * links only once, hence we remove it from all comments.
 *
 * Add edit link for GO/GA/PO/PA which don't have the "administer comments"
 * permission.
 */
function c4m_comment_comment_view($comment, $view_mode, $langcode) {
  // The comment is not forbidden for actions.
  if (!empty($comment->content['links']['comment']['#links']['comment_forbidden'])) {
    unset($comment->content['links']['comment']['#links']['comment_forbidden']);
  }

  if (empty($comment->content['links'])) {
    return;
  }

  // Check if the link is already there.
  if (isset($comment->content['links']['comment']['#links']['comment-edit'])) {
    return;
  }

  // Check if the user has permissions to see the edit link.
  if (!c4m_comment_edit_access_check($comment)) {
    return;
  }

  // Prepend the edit link to keep the same order of links as for SA.
  $edit_link = [
    'comment-edit' => [
      'title' => t('edit'),
      'href' => 'comment/' . $comment->cid . '/edit',
    ],
  ];
  $comment->content['links']['comment']['#links'] = $edit_link + $comment->content['links']['comment']['#links'];

}

/**
 * Access callback for editing comments.
 *
 * @see comment_access()
 */
function c4m_comment_edit_access_check($comment) {
  global $user;

  if (user_access('administer comments')) {
    return TRUE;
  }

  if ($user->uid && $user->uid == $comment->uid && $comment->status == COMMENT_PUBLISHED && user_access('edit own comments')) {
    return TRUE;
  }

  if (c4m_features_og_members_is_power_user()) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Gets the ID of the group context of the comment.
 *
 * @param object $comment
 *   The object of the comment.
 *
 * @return bool|int
 *   The ID of the group or FALSE if not part of a group.
 */
function c4m_comment_get_group_id($comment) {
  if (og_is_group('node', $comment->nid)) {
    return $comment->nid;
  }
  elseif ($group = c4m_og_get_group_of_content($comment->nid)) {
    return $group->nid;
  }

  return FALSE;
}

/**
 * Implements hook_menu_alter().
 */
function c4m_comment_menu_alter(&$items) {
  // Alter the comment callback to check the purl access.
  $items['comment/%']['page callback'] = 'c4m_comment_permalink';

  // Alter the access callback for edit comment.
  if (isset($items['comment/%comment/edit'])) {
    $items['comment/%comment/edit']['access callback'] = 'c4m_comment_edit_access_check';
    $items['comment/%comment/edit']['access arguments'] = [1];
  }
}

/**
 * Access callback for comments.
 *
 * A comment that is part of a group content must be seeing under its context.
 */
function c4m_comment_permalink($cid) {
  if ($comment = comment_load($cid)) {
    if ($gid = c4m_comment_get_group_id($comment)) {
      // This is a comment of a group content and must be seeing under its
      // relevant context (group) only.
      $context = og_context();
      if (!$context || $gid !== $context['gid']) {
        // Try loading the node and redirect to the group context.
        $options = array(
          'absolute' => TRUE,
          'purl' => array(
            'provider' => 'og_purl|node',
            'id' => $gid,
          ),
          'fragment' => 'comment-' . $comment->cid,
        );

        // Use the same URL structure/fragment, only add the purl provider.
        drupal_goto('comment/' . $comment->cid, $options);
      }
    }
  }

  return comment_permalink($cid);
}
