<?php
/**
 * @file
 * Code for the User Profile feature.
 */

include_once 'c4m_user_profile.features.inc';
/**
 * @file
 * capacity4more User Profile module
 */

/**
 * Implements hook_field_extra_fields_alter()
 */
function c4m_user_profile_field_extra_fields_alter(&$info) {
  // Make sure that the Account fields are always at the top of the
  // user profile.
  if (isset($info['user']['user']['form']['account']['weight'])) {
    $info['user']['user']['form']['account']['weight'] = -100;
  }
}

/******************************************************************************
 * BLOCK
 ******************************************************************************/
/**
 * Implements hook_block_info().
 */
function c4m_user_profile_block_info() {
  $blocks['user_welcome'] = array(
    'info' => t('Welcome the user in the top bar'),
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  $blocks['user_notifications'] = array(
    'info' => t('Display the user notifications etc...'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function c4m_user_profile_block_view($delta = '') {
  $module_name = 'c4m_user_profile';
  module_load_include('inc', $module_name, "{$module_name}.block");
  $callback = "_{$module_name}_block_" . $delta;
  if (!function_exists($callback)) {
    return NULL;
  }

  return $callback();
}

/**
 * Helper function to render user first and last name in one string using the
 * user entity.
 *
 * @param $user
 *
 * @return string
 */
function c4m_user_profile_name($user) {
  $wrapper = entity_metadata_wrapper('user', $user);

  if ($user->uid == 0) {
    return t('Anonymous');
  }

  $fullname = trim($wrapper->c4m_first_name->value()) . ' '
    . trim($wrapper->c4m_last_name->value());

  if (!trim($fullname)) {
    $fullname = $user->name;
  }

  return trim($fullname);
}

/**
 * Implements hook_token_info().
 */
function c4m_user_profile_token_info() {
  $info['tokens']['user']['full-name'] = array(
    'name'        => t('User Full Name'),
    'description' => t('Returns the User Full Name)'),
  );
  $info['tokens']['user']['url-with-name'] = array(
    'name' => t("User profile URL with fallback for anonymous users"),
    'description' => t("The URL of the account profile page, with fallback if anonymous."),
  );

  return $info;
}

/**
 * Implements hook_tokens().
 */
function c4m_user_profile_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $url_options = array('absolute' => TRUE);

  if ($type == 'user' && !empty($data['user'])) {
    $account = $data['user'];
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'full-name':
          $replacements[$original] = c4m_user_profile_name($account);
          break;
        case 'url-with-name':
          $name = c4m_user_profile_name($account);
          $replacements[$original] = !empty($account->uid) ? l(
            $name, "user/$account->uid", $url_options
          ) : $name;
          break;
      }
    }
  }

  return $replacements;
}

/**
 * Return the initials (max 2) of a user's full name.
 *
 * @param $account
 *
 * @return string
 */
function c4m_user_profile_initials($account) {
  $name = c4m_user_profile_name($account);
  $words = preg_split("/[\s,_-]+/", $name);
  $initials = '';

  foreach ($words as $w) {
    $initials .= $w[0];
  }

  return substr($initials, 0, 2);
}

/**
 * Return the themed initials (max 2) of a user's full name.
 *
 * @param $account
 *
 * @return string
 */
function c4m_user_profile_initials_themed($account, $linked = TRUE) {
  $initials = c4m_user_profile_initials($account);
  static $colors;

  if (empty($colors)) {
    $colors = _c4m_user_profile_initials_colors();
  }

  if ($linked) {
    $output = l($initials, 'user/' . $account->uid);
  }
  else {
    $output = $initials;
  }

  $tag = array(
    'element' => array(
      '#tag' => 'div',
      '#attributes' => array(
        'class' => array(
          'no-avatar',
          'initials',
          'bg-' . $colors[mt_rand(0, count($colors) - 1)]
        ),
      ),
      '#value' => $output,
    ),
  );

  return theme_html_tag($tag);
}

/**
 * Get some background classes (random colors).
 *
 * @return array
 */
function _c4m_user_profile_initials_colors() {
  return array(
    'dark-navy',
    'pastel-pink',
    'beige',
    'brown',
    'brown-light',
    'blue',
    'salmon',
    'pastel-orange',
    'green',
    'green-light',
    'pink-dark',
  );
}