<?php
/**
 * @file
 * Code for the user admin module.
 */

include_once 'c4m_user_admin.features.inc';

/**
 * Implements hook_action_info().
 */
function c4m_user_admin_action_info() {
  module_load_include('inc', 'c4m_user_admin', 'actions/c4m_user_admin.action');
  return _c4m_user_admin_action_info();
}

/**
 * Implements hook_views_data().
 */
function c4m_user_admin_views_data() {
  $data['users']['activate_user'] = array(
    'field' => array(
      'title' => t('Activate user link'),
      'help' => t('Provide a simple link to activate the user.'),
      'handler' => 'views_handler_field_user_link_activate',
    ),
  );
  return $data;
}

/**
 * Implements hook_menu().
 */
function c4m_user_admin_menu() {
  $items['user/%user/activate'] = array(
    'title' => 'Activate user',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('c4m_user_admin_user_activate_form', 1),
    'access arguments' => array('administer users'),
    'file' => 'c4m_user_admin.pages.inc',
  );

  return $items;
}
