<?php
/**
 * @file
 * General Organic Groups functionality.
 */

include_once 'c4m_og.features.inc';
include_once 'c4m_og.access.inc';

/**
 * The access realm of C4M group member.
 */
define('C4M_OG_ACCESS_REALM', 'c4m_og_access');

/**
 * The values of the groups access level as defined on its field base.
 */
define('C4M_OG_MODERATED_GROUP', 0);
define('C4M_OG_OPEN_GROUP', 1);

/**
 * Helper to get the current active group (based on og_context()).
 *
 * @return object|FALSE
 *   The group entity, or FALSE if no context was found.
 */
function c4m_og_current_group() {
  $context = og_context();
  if (!$context) {
    return FALSE;
  }

  $group = node_load($context['gid']);
  if (!$group) {
    return FALSE;
  }

  return $group;
}

/**
 * Helper to get the current active group id (based on og_context()).
 *
 * @return NULL|int
 *   The group id, or NULL if no context was found.
 */
function c4m_og_current_group_id() {
  $context = og_context();
  if (!$context) {
    return NULL;
  }

  return $context['gid'];
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function c4m_og_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
  elseif ($module == 'entityreference' && !empty($plugin)) {
    return "plugins/entityreference/$plugin";
  }
  elseif ($module == 'pluggable_node_access') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Helper function to get the human readable name of a group type.
 *
 * @param object $node
 *    The node object.
 *
 * @internal param object $group
 *
 * @return string
 *    Human readable name of group type.
 */
function c4m_og_get_group_type_name($node = NULL) {
  if (!$node) {
    $node = c4m_og_current_group();
  }
  if (!$node || !og_is_group_type('node', $node->type)) {
    return NULL;
  }

  return strtolower(node_type_get_name($node));
}

/**
 * Implements hook_form_alter().
 */
function c4m_og_form_alter(&$form, $form_state) {
  if (empty($form['#node_edit_form'])
    || !og_is_group_type(
      'node',
      $form['#node']->type
    )
  ) {
    return;
  }
  $form['og_purl']['purl']['value']['#title'] = t('Group path');
  $form['og_purl']['purl']['value']['#type'] = 'machine_name';
  $form['og_purl']['purl']['value']['#machine_name'] = array(
    'source' => array('title'),
    'label' => t('Group path'),
    'exists' => 'c4m_og_purl_exists',
    'replace' => '-',
    'replace_pattern' => '[^a-z0-9_-]+',
  );
}

/**
 * Implements hook_menu().
 */
function c4m_og_menu() {
  $items['group/%/%/admin/owner'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('c4m_og_replace_owner_build_form', 1, 2),
    'access callback' => 'c4m_og_user_is_owner',
    'access arguments' => array(1, 2),
    'title' => 'Replace Owner',
  );
  $items['project/%/%/admin/owner'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('c4m_og_replace_owner_build_form', 1, 2),
    'access callback' => 'c4m_og_user_is_owner',
    'access arguments' => array(1, 2),
    'title' => 'Replace Owner',
  );

  return $items;
}

/**
 * Implements hook_og_ui_get_group_admin_alter().
 *
 * Adding a link to the replace owner page.
 */
function c4m_og_og_ui_get_group_admin_alter(&$data, $context) {
  if (!c4m_og_user_is_owner($context['entity_type'], $context['etid'])) {
    return;
  }

  $data['replace_owner'] = array(
    'title' => t('Replace Owner'),
    'description' => t('Replacing the owner of the group or project.'),
    'href' => 'admin/owner',
  );
}

/**
 * Form builder.
 *
 * Group owner replace form.
 */
function c4m_og_replace_owner_build_form($form, $form_state, $entity_type, $etid) {
  og_set_breadcrumb($entity_type, $etid, array(l(t('Group'), "$entity_type/$etid/group")));

  $admins = array();
  // Setting the list of the group admins.
  foreach (c4m_og_get_group_admins($etid) as $admin) {
    $admins[$admin->uid] = c4m_user_name($admin);
  }

  $form['new_owner'] = array(
    '#type' => 'select',
    '#required' => TRUE,
    '#options' => $admins,
    '#title' => t('Select new owner'),
    '#description' => t('Select the name of the member you wish to be the new owner.'),
  );

  $form['group'] = array(
    '#type' => 'value',
    '#value' => $etid,
  );

  $form['type'] = array(
    '#type' => 'value',
    '#value' => $entity_type,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Replace'),
  );

  return $form;
}

/**
 * Submit handler.
 *
 * Replacing the owner of a group.
 */
function c4m_og_replace_owner_build_form_submit($form, &$form_state) {
  $new_owner = array(
    'uid' => $form_state['values']['new_owner'],
    'name' => $form['new_owner']['#options'][$form_state['values']['new_owner']],
  );
  c4m_og_replace_owner($form_state['values']['type'], $form_state['values']['group'], $new_owner);

  // Redirect back to the group page.
  $form_state['redirect'] = $form_state['values']['type'] . '/' . $form_state['values']['group'] . '/group';
}

/**
 * Replacing the owner of a group.
 *
 * After replacing the owner of the group we grant "group administrator member"
 * role to the old owner and revoke this role from the new one.
 *
 * @param string $group_type
 *   The type of the group.
 * @param int $gid
 *   The ID of the group.
 * @param array $new_owner
 *   An array containing the ID and the name of the new owner.
 */
function c4m_og_replace_owner($group_type, $gid, $new_owner) {
  $group = entity_load_single($group_type, $gid);
  $old_owner_id = $group->uid;

  // Update the uid on the entity.
  $group->uid = $new_owner['uid'];

  // Save the entity.
  if (entity_save($group_type, $group)) {
    drupal_set_message(t('Failed to change manager to @user.', array('@user' => $new_owner['name'])), 'error');
  }
  else {
    drupal_set_message(t('Owner changed to @user.', array('@user' => $new_owner['name'])));

    $group_admin_role = c4m_og_user_role_load_by_name('administrator member', 'group');
    // Grant admin role to the old owner.
    og_role_grant($group_type, $gid, $old_owner_id, $group_admin_role->rid);
    // Revoke admin role from the new owner.
    og_role_revoke($group_type, $gid, $new_owner['uid'], $group_admin_role->rid);
  }
}

/**
 * Access callback for the "Replace owner" form.
 *
 * @param string $group_type
 *   The type of the group.
 * @param int $gid
 *   The ID of the group.
 *
 * @return bool
 *   TRUE if the current user has access to the group, FALSE otherwise.
 */
function c4m_og_user_is_owner($group_type, $gid) {
  global $user;

  $group = entity_load_single($group_type, $gid);
  if (!$group || !og_is_group($group_type, $group)) {
    return FALSE;
  }

  // Make sure the current user is the group manager.
  return user_access('administer groups', $user) || $user->uid == $group->uid;
}

/**
 * Fetches an og user role by its name and group bundle.
 *
 * @param string $role_name
 *   A string representing the role name.
 * @param string $group_bundle
 *   A string representing the group bundle.
 *
 * @return mixed
 *   A fully-loaded og role object if a role with the given name and group
 *   bundle exists, or FALSE otherwise.
 */
function c4m_og_user_role_load_by_name($role_name, $group_bundle) {
  $cache = &drupal_static(__FUNCTION__);
  if (!isset($cache)) {
    $cache = db_select('og_role', 'r')
      ->fields('r')
      ->condition('name', $role_name)
      ->condition('group_bundle', $group_bundle)
      ->execute()
      ->fetchObject();
  }

  return $cache;
}

/**
 * Fetch all group admins.
 *
 * @param int $gid
 *   The ID of the group.
 *
 * @return array
 *   An array of all group admins.
 */
function c4m_og_get_group_admins($gid) {
  $group_admin_role = c4m_og_user_role_load_by_name('administrator member', 'group');
  $admins = c4m_og_get_users_by_roles($gid, array($group_admin_role->rid));
  foreach ($admins as &$admin) {
    $admin = $admin->uid;
  }

  return user_load_multiple($admins);
}

/**
 * Implements hook_module_implements_alter().
 */
function c4m_og_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['c4m_og'])) {
    $c4m_og = $implementations['c4m_og'];
    unset($implementations['c4m_og']);
    $implementations['c4m_og'] = $c4m_og;
  }
}

/**
 * Function to check if a path is a purl path.
 *
 * @param string $value
 *    Group path.
 *
 * @return bool
 *    TRUE or FALSE.
 */
function c4m_og_purl_exists($value) {
  return FALSE;
}

/**
 * Function to get roles per group bundle.
 *
 * @return array
 *    Array of roles per group bundle
 */
function c4m_og_get_group_bundles() {
  $roles = array();
  $result = db_select('og_role', 'ogr')
    ->fields('ogr', array('group_bundle', 'rid', 'name'))
    ->execute()
    ->fetchAll();
  foreach ($result as $row) {
    $roles[$row->group_bundle][$row->rid] = $row->name;
  }

  return $roles;
}

/**
 * Function to get OG permissions by OG role.
 *
 * @param int $rid
 *   The role ID.
 *
 * @return array
 *    Array of OG permissions
 */
function c4m_og_get_permissions_by_role($rid, $module = 'c4m_og') {
  $perms = array();
  $result = db_select('og_role_permission', 'ogrp')
    ->fields('ogrp', array('permission'))
    ->condition('rid', $rid)
    ->condition('module', $module)
    ->execute()
    ->fetchAll();
  foreach ($result as $row) {
    $perms[$row->permission] = $row->permission;
  }

  return $perms;
}

/**
 * Function to get OG roles by OG permission.
 *
 * @param string $permission
 *    The permission.
 * @param string $module
 *    The module name.
 *
 * @return array
 *    Array of role ids.
 */
function c4m_og_get_roles_by_permission($permission, $module = 'c4m_og') {
  $roles = array();
  $result = db_select('og_role_permission', 'ogrp')
    ->fields('ogrp', array('rid'))
    ->condition('permission', $permission)
    ->condition('module', $module)
    ->execute()
    ->fetchAll();
  foreach ($result as $row) {
    $roles[$row->rid] = $row->rid;
  }

  return $roles;
}

/**
 * Get all the users with certain roles in a group.
 *
 * @param int $gid
 *   The group unique ID.
 * @param array $rids
 *   Array with the role IDs to query.
 */
function c4m_og_get_users_by_roles($gid, $rids = array()) {
  $query = db_select('og_users_roles', 'og_users_roles');

  return $query->fields('og_users_roles', array('uid'))
    ->condition('gid', $gid)
    ->condition('rid', $rids, 'IN')
    ->execute()
    ->fetchAll();
}

/**
 * Implements hook_views_api().
 */
function c4m_og_views_api() {
  return array('api' => 3.0);
}

/**
 * Access callback for the c4m_og_access_plugin access plugin.
 *
 * @param string $feature
 *   Determine if the specified user has access to a given feature.
 * @param object $account
 *   If the $account argument is omitted, the current user is used.
 *
 * @return bool
 *    TRUE or FALSE whether access is granted or not.
 */
function c4m_og_access($feature = NULL, $account = NULL) {
  // Check if the user has access to the group context.
  $og_context = og_context();
  if (!$og_context) {
    return FALSE;
  }

  // Check if the feature is enabled.
  if (empty($feature) || c4m_og_feature_enabled($feature)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_og_permission().
 *
 * Add group permissions.
 */
function c4m_og_og_permission() {
  return array(
    'view unpublished group content' => array(
      'title' => t('View unpublished group content'),
      'description' => t("Allow user to view unpublished content of a group."),
      'roles' => array(OG_AUTHENTICATED_ROLE),
      'default role' => array(OG_ANONYMOUS_ROLE, OG_ADMINISTRATOR_ROLE),
    ),
  );
}

/**
 * Function to filter all groups of a user by a certain permission.
 *
 * It returns only the gids of the groups for which the user has the permission.
 *
 * We do this by retrieving roles of the user for the groups
 * and then check per role if it has that permission.
 *
 * We assemble all the permissions this user has in a group and with those we
 * filter out the groups which do not contain the desired permission.
 *
 * @param string $uid
 *    User id needed to collect the user roles for this user.
 * @param string $perm
 *    The permission to check on.
 * @param array $gids
 *    The group ID's to fetch the permissions for.
 */
function c4m_og_user_has_permission_in($uid, $perm, array &$gids) {
  foreach ($gids as $membership_id => $gid) {
    $roles = og_get_user_roles('node', $gid, $uid);
    $rids = array_keys($roles);
    $perms_for_gid = array();
    foreach ($rids as $rid) {
      $perms_for_gid = array_merge(
        $perms_for_gid,
        c4m_og_get_permissions_by_role($rid)
      );
    }
    if (!in_array($perm, $perms_for_gid)) {
      unset($gids[$gid]);
    }
  }
}

/**
 * Implements hook_node_grants().
 */
function c4m_og_node_grants($account, $op) {
  switch ($op) {
    case 'view':
      // Only grant group members and users with the appropriate role within
      // the group the right to view unpublished nodes.
      if ($groups = og_get_entity_groups('user', $account)) {
        // We need to know if the user has the right role within these
        // groups, meaning a role with the right permission.
        foreach ($groups as $group_type => $gids) {
          $perm = 'view unpublished group content';
          c4m_og_user_has_permission_in($account->uid, $perm, $gids);
          foreach ($gids as $gid) {
            $realm = C4M_OG_ACCESS_REALM . ':' . $perm;
            $grants[$realm][] = $gid;
          }
        }
        return !empty($grants) ? $grants : array();
      }
      break;
  }
}

/**
 * Implements hook_node_access_records_alter().
 *
 * We could use hook_node_access_records for this because node module and
 * og_access module do not deliver grants for unpublished nodes so there is no
 * real need to alter grants.
 * But then we would have an implementation of hook_node_access_records and
 * possibly in the future one of hook_node_access_records_alter.
 *
 * It's clearer to have our node_access_records logic in one place.
 */
function c4m_og_node_access_records_alter(&$grants, $node) {
  // Allow group members with the right permission to view unpublished group
  // content nodes.
  if (empty($node->status) && og_is_group_content_type('node', $node->type)) {
    // Node is unpublished, so og_access will not deliver grants, nor will node
    // (module).
    // We allow a view grant within our realm
    // 'c4m_og_access:view unpublished group content' for the groups of
    // which this node is content.
    $perm = 'view unpublished group content';
    // Retrieve groups of this node.
    $entity_groups = og_get_entity_groups('node', $node);
    foreach ($entity_groups as $group_type => $values) {
      foreach ($values as $gid) {
        $list_gids[$group_type][] = $gid;
        $grants[] = array(
          'realm' => C4M_OG_ACCESS_REALM . ':' . $perm,
          'gid' => $gid,
          'grant_view' => 1,
          'grant_update' => 0,
          'grant_delete' => 0,
          'priority' => 0,
        );
      }
    }
  }
}

/**
 * Counts the number of members in a given group.
 *
 * @param object $group
 *    The group entity.
 * @param int $state
 *    The status of the membership, Defaults to active.
 *
 * @return int
 *    The count of members in the group.
 */
function c4m_og_get_members_count($group, $state = OG_STATE_ACTIVE) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'og_membership')
    // This is the group ID.
    ->propertyCondition('gid', $group->nid)
    // Get only the active members.
    ->propertyCondition('state', $state)
    ->propertyCondition('entity_type', 'user')
    ->addTag('user_not_blocked')
    ->count()
    ->execute();

  return $result;
}

/**
 * Implements hook_query_TAG_alter().
 */
function c4m_og_query_user_not_blocked_alter(QueryAlterableInterface $query) {
  // Make sure to count only user who are not blocked.
  $query->innerjoin("users", "u", "u.uid = og_membership.etid AND u.status = '1'");
}

/**
 * Counts the number of posts in a given group.
 *
 * @param object $group
 *    The group entity.
 *
 * @return int
 *    The count of posts in the group.
 */
function c4m_og_get_posts_count($group) {
  $query = db_select('node', 'n');
  $query->join('og_membership', 'ogm', 'n.nid = ogm.etid');
  $query->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('ogm.gid', (int) $group->nid)
    ->condition('ogm.entity_type', 'node');

  return (int) $query->countQuery()->execute()->fetchField();
}

/**
 * Implements hook_entity_property_info_alter().
 */
function c4m_og_entity_property_info_alter(&$info) {
  $info['node']['properties']['c4m_og_group_type'] = array(
    'type' => 'text',
    'label' => t('Group type'),
    'sanitized' => TRUE,
    'getter callback' => '_c4m_og_group_type_getter_callback',
  );
}

/**
 * Getter callback for created_week_day property.
 *
 * @param object $item
 *    The group object.
 *
 * @return string
 *    Type of group access.
 */
function _c4m_og_group_type_getter_callback($item) {
  // Get group type information.
  $group_access = c4m_og_get_access_type($item);
  if (!empty($group_access['type'])) {
    return ucfirst($group_access['type']);
  }
}

/**
 * Get the group nid of the given entity.
 *
 * @param object $entity
 *   The entity we want the group id of.
 *
 * @return NULL|int
 *   The group ID if any.
 */
function c4m_og_get_gid_from_entity($entity) {
  // Check if entity has the "type" property.
  if (!property_exists($entity, 'type')) {
    return NULL;
  }

  if (og_is_group_type('node', $entity->type)) {
    return (int) $entity->nid;
  }

  if (og_is_group_content_type('node', $entity->type)
    && isset($entity->og_group_ref[LANGUAGE_NONE][0]['target_id'])
  ) {
    return (int) $entity->og_group_ref[LANGUAGE_NONE][0]['target_id'];
  }

  return NULL;
}

/**
 * Load all group features info from implemented c4m_og_feature hooks.
 *
 * @param string $feature
 *   Only return data for a given feature.
 *
 * @return array
 *   Configuration as collected trough the implemented
 *   hook_c4m_og_feature_info hooks.
 */
function c4m_og_feature_info($feature = NULL) {
  $cache_key = 'c4m_og:feature_info';
  $data = &drupal_static($cache_key);

  // Retrieve from Cache if not loaded before.
  if (!isset($data)) {
    if (($cache = cache_get($cache_key)) && !empty($cache->data)) {
      $data = $cache->data;
    }
    else {
      $hook = 'c4m_og_feature_info';
      $data = module_invoke_all($hook);
      uasort($data, 'drupal_sort_weight');
      cache_set($cache_key, $data);
    }
  }

  // Only return data for a given feature.
  if (isset($data[$feature])) {
    return $data[$feature];
  }

  // Return all data.
  return $data;
}

/**
 * Check if a given feature is enabled.
 *
 * @param string $feature
 *   The feature to check.
 *
 * @return bool
 *   True if the feature is enabled for the active group.
 */
function c4m_og_feature_enabled($feature) {
  // Check if the feature exists.
  $og_feature = c4m_og_feature_info($feature);
  if (!isset($og_feature['machine_name'])) {
    return FALSE;
  }

  // Check if the feature is enabled.
  $settings = variable_get('c4m_og_features_group', array());
  if (isset($settings[$feature]) && $settings[$feature] === $feature) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Get a list of enabled features for the active group.
 *
 * @return array
 *   An array with the features that are enabled for the active group.
 */
function c4m_og_feature_enabled_features() {
  $features = variable_get('c4m_og_features_group');

  foreach ($features as $feature => $status) {
    if (!$status) {
      unset($features[$feature]);
    }
  }

  return array_keys($features);
}

/**
 * Get a list of enabled features for the active group.
 *
 * @return array
 *   An array with the features that are enabled for the active group.
 */
function c4m_og_feature_disabled_features() {
  $features = variable_get('c4m_og_features_group');

  foreach ($features as $feature => $status) {
    if ($status) {
      unset($features[$feature]);
    }
  }

  return array_keys($features);
}

/**
 * Get a list of enabled content types for the active group.
 *
 * @return array
 *   An array with the content types that are enabled for the active group.
 */
function c4m_og_feature_enabled_content_types() {
  $content_types = array();

  $feature_info = c4m_og_feature_info();
  $features = c4m_og_feature_enabled_features();

  foreach ($features as $feature) {
    $group_content_types = $feature_info[$feature]['content_types'];
    $content_types = array_merge($content_types, $group_content_types);
  }

  return $content_types;
}

/**
 * Check if a given content type is enabled within the current group context.
 *
 * @param string $type
 *   The node type.
 *
 * @return bool
 *   Enabled?
 */
function c4m_og_feature_is_content_type_enabled($type) {
  $enabled_types = c4m_og_feature_enabled_content_types();
  return in_array($type, $enabled_types);
}

/**
 * Get a list of disabled content types for the active group.
 *
 * @return array
 *   An array with the content types that are disabled for the active group.
 */
function c4m_og_feature_disabled_content_types() {
  $content_types = array();

  $feature_info = c4m_og_feature_info();
  $features = c4m_og_feature_disabled_features();

  foreach ($features as $feature) {
    $group_content_types = $feature_info[$feature]['content_types'];
    $content_types = array_merge($content_types, $group_content_types);
  }

  return $content_types;
}

/**
 * Install a given feature.
 *
 * @param string $feature
 *   The feature to install.
 * @param bool $enabled
 *   Optional, if the feature should be enabled by default (default = TRUE).
 */
function c4m_og_feature_install($feature, $enabled = TRUE) {
  $settings = variable_get('c4m_og_features_group');
  if ($enabled) {
    $settings[$feature] = $feature;
  }
  else {
    $settings[$feature] = 0;
  }
  variable_set('c4m_og_features_group', $settings);
}

/**
 * Uninstall a given feature.
 *
 * @param string $feature
 *   The feature to uninstall.
 */
function c4m_og_feature_uninstall($feature) {
  $settings = variable_get('c4m_og_features_group');
  unset($settings[$feature]);
  variable_set('c4m_og_features_group', $settings);
}

/**
 * Get the group IDs of all the group nodes.
 *
 * For specific node type a user is an
 * approved member of.
 *
 * @param string $bundle
 *    (optional) The group node type.
 * @param object $account
 *    (optional) The user object to fetch group memberships for. Defaults to the
 *   acting user.
 *
 * @return array $groups
 *    Returns array of group nodes IDs of specific node type.
 */
function c4m_og_get_user_group_nodes_by_bundle(
  $bundle = NULL,
  $account = NULL
) {
  $groups = og_get_groups_by_user($account, 'node');

  if (!$groups || !$bundle) {
    return $groups;
  }

  foreach ($groups as $key => $gid) {
    $wrapper = entity_metadata_wrapper('node', $gid);
    $node_type = $wrapper->getBundle();
    if ($node_type != $bundle) {
      unset($groups[$key]);
    }
  }
  return $groups;
}

/**
 * Implements hook_node_update().
 */
function c4m_og_node_update($node) {
  if (!og_is_group_type('node', $node->type)) {
    return;
  }

  _c4m_og_handle_pending_members_when_going_private($node);
  c4m_og_open_group_access_activate_pending_members($node);
}

/**
 * Delete all pending memberships from a group the go private.
 *
 * @param object $node
 *   The node object of the group.
 */
function _c4m_og_handle_pending_members_when_going_private($node) {
  $access = c4m_og_get_access_type($node);
  if ($access['type'] != 'private') {
    return;
  }

  // Delete all pending memberships of this group.
  $ids = c4m_og_get_all_group_memberships_by_state($node->nid, OG_STATE_PENDING);
  og_membership_delete_multiple($ids);
}

/**
 * Activate pending members when access level of a group is changed.
 *
 * When changing the access level from 'Moderated' to 'Open', all pending
 * members should become active group members.
 *
 * @param object $node
 *   The node object while being updated.
 *
 * @throws \Exception
 *   When the node object doesn't contain the 'original' property.
 */
function c4m_og_open_group_access_activate_pending_members($node) {
  if (empty($node->original)) {
    throw new Exception('Node object must contain the original property.');
  }

  $wrapper = entity_metadata_wrapper('node', $node);
  $original_wrapper = entity_metadata_wrapper('node', $node->original);

  if ($wrapper->field_membership_open_request->value() != C4M_OG_OPEN_GROUP) {
    // Group is not "Open".
    return;
  }

  if ($original_wrapper->field_membership_open_request->value() != C4M_OG_MODERATED_GROUP) {
    // Previous group setting was not "Moderated".
    return;
  }

  // Activate all pending members of this group.
  $ids = c4m_og_get_all_group_memberships_by_state($node->nid, OG_STATE_PENDING);
  foreach (og_membership_load_multiple($ids) as $membership) {
    $membership->state = OG_STATE_ACTIVE;
    $membership->save();

    // Send activation message to member.
    $message = message_create('c4m_welcome_to_group', array('uid' => $membership->etid));
    c4m_message_load__c4m_welcome_to_group($message);

    $wrapper = entity_metadata_wrapper('message', $message);
    $wrapper->field_group_node->set($membership->gid);
    // Message will be saved in message_notify_send_message().
    message_notify_send_message($wrapper->value());
  }
}

/**
 * Get the group membership entity by user, group and state.
 *
 * @param int $gid
 *   The group ID.
 * @param int $state
 *   The user current state.
 *
 * @return array
 *   Array of members UIDs, or an empty array.
 */
function c4m_og_get_all_group_memberships_by_state($gid, $state) {
  $cache = &drupal_static(__FUNCTION__, array());

  $identifier = $gid . ':' . $state;

  if (isset($cache[$identifier])) {
    return $cache[$identifier];
  }

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'og_membership')
    ->propertyCondition('gid', $gid)
    ->propertyCondition('state', $state)
    ->propertyCondition('group_type', 'node')
    ->propertyCondition('entity_type', 'user')
    ->execute();

  $cache[$identifier] = !empty($result['og_membership']) ? array_keys($result['og_membership']) : array();

  return $cache[$identifier];
}

/**
 * Load all metrics info from implementations of hook_c4m_og_metrics_info().
 *
 * @return array
 *   Configuration as collected through the implementations of
 *   hook_c4m_og_metrics_info() hooks.
 */
function c4m_og_metrics_info() {
  $cache_key = 'c4m_og:metrics_info';
  $data = &drupal_static($cache_key);

  // Retrieve from cache if not loaded before.
  if (!isset($data)) {
    if (($cache = cache_get($cache_key)) && !empty($cache->data)) {
      $data = $cache->data;
    }
    else {
      $data = module_invoke_all('c4m_og_metrics_info');

      // Sort the contexts.
      foreach ($data as $key => $info) {
        uasort($info, 'drupal_sort_weight');
        $data[$key] = $info;
      }

      // Save in cache.
      cache_set($cache_key, $data);
    }
  }

  return $data;
}

/**
 * Get the metrics specific for the given group.
 *
 * @param integer $og_id
 *   The Organic Group ID to gather the metrics for.
 *
 * @return array
 *   The collected metrics.
 */
function c4m_og_get_group_metrics($og_id) {
  $data = &drupal_static(__FUNCTION__);

  if (!isset($data[$og_id])) {
    if (!is_numeric($og_id)) {
      return array();
    }

    $data[$og_id] = array();
    $list = c4m_og_metrics_info();

    foreach ($list as $key => &$info) {
      $type = isset($info['type'])
        ? $info['type']
        : NULL;

      $callback = isset($info['callback'])
        ? $info['callback']
        : '';

      $arguments = array($og_id);
      if (isset($info['arguments'])) {
        $arguments = array_merge($arguments, $info['arguments']);
      }

      if ($type && $callback && function_exists($callback)) {
        $data[$og_id][$type] = call_user_func_array($callback, $arguments);
      }
    }
  }

  return $data[$og_id];
}

/**
 * Get a specific metric for the given group.
 *
 * @param integer $og_id
 *   The Organic Group ID to gather the metrics for.
 * @param string $type
 *   The metric type.
 *
 * @return string | integer
 *   The value of the metric.
 */
function c4m_og_get_group_metric_value($og_id, $type) {
  if (!is_numeric($og_id) || empty($type)) {
    return NULL;
  }

  $metrics = c4m_og_get_group_metrics($og_id);

  if (isset($metrics[$type])) {
    return $metrics[$type];
  }

  return NULL;
}

/**
 * Returns the amount of nodes in the group of the specified bundles.
 *
 * @param integer $og_id
 *   The Organic Group ID to gather the metrics for.
 * @param array $bundles
 *   The bundles to query for.
 *
 * @return integer
 *   The amount of nodes in the group.
 */
function c4m_og_group_node_metric($og_id, $bundles) {
  $arguments = array(
    'entity_type' => 'node',
    'bundles' => $bundles,
    'state' => 1,
    'og_id' => $og_id,
    'topic' => NULL,
    'c4m_status' => NULL,
  );

  return c4m_helper_entity_get_number_of_entities($arguments);
}

/**
 * Returns the amount of users in the group of the specified bundles.
 *
 * @param integer $og_id
 *   The Organic Group ID to gather the metrics for.
 *
 * @return integer
 *   The amount of users in the group.
 */
function c4m_og_group_user_metric($og_id) {
  $arguments = array(
    'entity_type' => 'user',
    'bundles' => array(),
    'state' => 1,
    'og_id' => $og_id,
    'topic' => NULL,
    'c4m_status' => NULL,
  );

  return c4m_helper_entity_get_number_of_entities($arguments);
}

/**
 * Returns the amount of comments in the group.
 *
 * @param integer $og_id
 *   The Organic Group ID to gather the metrics for.
 *
 * @return integer
 *   The amount of comments in the group.
 */
function c4m_og_group_comment_metric($og_id) {
  $arguments = array(
    'entity_type' => 'comment',
    'bundles' => array(),
    'state' => 1,
    'og_id' => $og_id,
    'topic' => NULL,
    'c4m_status' => NULL,
  );

  return c4m_helper_entity_get_number_of_entities($arguments);
}

/**
 * Implements hook_c4m_og_metrics_info().
 */
function c4m_og_c4m_og_metrics_info() {
  return array(
    'c4m_og_content_recommendations' => array(
      'type'     => 'content_recommendations',
      'callback' => 'c4m_og_get_content_recommendations',
      'weight'   => 100,
    ),
  );
}

/**
 * Returns the total amount of recommendations on content of a group.
 *
 * @param integer $og_id
 *   The Organic group ID to limit the query for.
 *
 * @return integer
 *   The total amount of recommendations on the group content.
 */
function c4m_og_get_content_recommendations($og_id = NULL) {
  if (!is_numeric($og_id)) {
    return 0;
  }

  $query = db_select('node', 'n');
  $query->join('og_membership', 'ogm', 'ogm.etid = n.nid');
  $query->join('flag_counts', 'fc', 'fc.entity_id = n.nid');
  $query->join('flag', 'f', 'f.fid = fc.fid');
  $query->condition('n.status', 1);
  $query->condition('ogm.gid', (int) $og_id);
  $query->condition('ogm.entity_type', 'node');
  $query->condition('fc.entity_type', 'node');
  $query->condition('f.name', 'c4m_og_content_recommend');
  $query->addExpression('SUM(fc.count)', 'recommendations');

  return $query->execute()->fetchField();
}
