<?php
/**
 * @file
 * Module to create demo content using the Migrate module.
 */


/**
 * Name used to group the migration classes.
 */
define('C4M_DEMO_CONTENT_MIGRATION_GROUP', 'c4m_demo_content');

/**
 * Implements hook_migrate_api().
 */
function c4m_demo_content_migrate_api() {
  $migrations = array();

  $classes = array(
    'C4mDemoContentCreateUsers',
    'C4mDemoContentCreateTopics',
    'C4mDemoContentCreateRegionTerms',
    'C4mDemoContentCreateRegionNodes',
    'C4mDemoContentCreateGroups',
    'C4mDemoContentCreateProjects',
    'C4mDemoContentCreateArticles',
    'C4mDemoContentCreateCategories',
    'C4mDemoContentCreateTags',
    'C4mDemoContentCreatePhotoalbums',
    'C4mDemoContentCreateEvents',
    'C4mDemoContentCreateDocuments',
    'C4mDemoContentCreateBlogs',
  );

  $group_name = 'c4m_demo_content';

  foreach ($classes as $class_name) {
    $migrations[$class_name] = array(
      'class_name' => $class_name,
      'group_name' => $group_name,
    );
  }

  $api = array(
    'api'        => 2,
    'groups'     => array(
      $group_name => array(
        'title' => t('Demo content'),
      ),
    ),
    'migrations' => $migrations,
  );

  return $api;
}
