<?php
/**
 * @file
 */

/**
 * Implements hook_migrate_api().
 */
function c4m_demo_content_migrate_api() {
  $migrations = array();

  $classes = array(
    'C4mDemoContent_CreateUsers',
    'C4mDemoContent_CreateTopics',
    'C4mDemoContent_CreateRegionTerms',
    'C4mDemoContent_CreateRegionNodes',
    'C4mDemoContent_CreateGroups',
  );

  foreach ($classes as $class_name) {
    $migrations[$class_name] = array('class_name' => $class_name);
  }

  $api = array(
    'api' => 2,
    'migrations' => $migrations,
  );
  return $api;
}
